Repository Azure/azure-sdk-for-python, pull requests merged in 2018-02, with the labels that each got.

#1949 [AutoPR compute/resource-manager] Add missing properties for Vmss zone GA
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_scale_set.py
Labels: RestPRMerged

#1829 Automatic PR of restapi_auto_jaredmoo_sqlCoreRefactor into master
  azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  azure-mgmt-sql/azure/mgmt/sql/models/sql_management_client_enums.py
  azure-mgmt-sql/azure/mgmt/sql/operations/__init__.py
  azure-mgmt-sql/azure/mgmt/sql/operations/backup_long_term_retention_policies_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/backup_long_term_retention_vaults_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/capabilities_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/data_masking_policies_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/data_masking_rules_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/database_blob_auditing_policies_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/database_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/database_threat_detection_policies_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/database_usages_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/databases_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/elastic_pool_activities_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/elastic_pool_database_activities_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/elastic_pools_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/encryption_protectors_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/failover_groups_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/firewall_rules_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/geo_backup_policies_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/recommended_elastic_pools_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/recoverable_databases_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/replication_links_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/restorable_dropped_databases_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/restore_points_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/server_azure_ad_administrators_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/server_communication_links_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/server_connection_policies_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/server_dns_aliases_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/server_keys_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/server_usages_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/servers_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/service_objectives_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/service_tier_advisors_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/subscription_usages_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/sync_agents_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/sync_groups_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/sync_members_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/transparent_data_encryption_activities_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/transparent_data_encryptions_operations.py
  azure-mgmt-sql/azure/mgmt/sql/operations/virtual_network_rules_operations.py
  azure-mgmt-sql/azure/mgmt/sql/sql_management_client.py
Labels: RestPRMerged

#1951 [AutoPR sql/resource-manager] Py version for SQL build
  azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  azure-mgmt-sql/azure/mgmt/sql/models/database_restore_point.py
  azure-mgmt-sql/azure/mgmt/sql/models/database_restore_point_paged.py
  azure-mgmt-sql/azure/mgmt/sql/operations/__init__.py
  azure-mgmt-sql/azure/mgmt/sql/operations/database_restore_points_operations.py
  azure-mgmt-sql/azure/mgmt/sql/sql_management_client.py
  azure-mgmt-sql/azure/mgmt/sql/version.py
Labels: RestPRMerged

#1878 [ApplicationInsights] Update
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/application_insights_management_client.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/__init__.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_proactive_detection_configuration.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/application_insights_component_proactive_detection_configuration_rule_definitions.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/__init__.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/proactive_detection_configurations_operations.py
Labels: RestPRMerged

#1891 [Monitor] Added the new Voice action and increased the API version for this change
  azure-mgmt-monitor/azure/mgmt/monitor/models/__init__.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_patch_body.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/automation_runbook_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/azure_app_push_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/itsm_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/voice_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/action_groups_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/activity_log_alerts_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/activity_logs_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/alert_rule_incidents_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/alert_rules_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/autoscale_settings_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/diagnostic_settings_category_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/diagnostic_settings_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/event_categories_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/log_profiles_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/metric_baseline_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/metric_definitions_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/metrics_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/tenant_activity_logs_operations.py
Labels: RestPRMerged

#1927 [AutoPR monitor/resource-manager] [Monitor] Make all attributes of EventData class readonly (#2254)
  azure-mgmt-monitor/azure/mgmt/monitor/models/event_data.py
Labels: RestPRMerged

#1936 [AutoPR cognitiveservices/data-plane/ContentModerator] Classify changes Update
  azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/__init__.py
  azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/classification.py
  azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/classification_category1.py
  azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/classification_category2.py
  azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/classification_category3.py
Labels: RestPRMerged

#1955 [AutoPR advisor/resource-manager] Adding x-ms-pageable tag for configuration list command.
  azure-mgmt-advisor/azure/mgmt/advisor/models/__init__.py
  azure-mgmt-advisor/azure/mgmt/advisor/models/config_data_paged.py
  azure-mgmt-advisor/azure/mgmt/advisor/operations/configurations_operations.py
  azure-mgmt-advisor/azure/mgmt/advisor/version.py
  azure-mgmt-advisor/tests/test_mgmt_advisor.py
Labels: RestPRMerged

#1978 Updated storage package versions to 1.1.0 for the azure mega-package
  azure/setup.py
Labels: Packaging

#1980 Azure 3.0.0
  azure-mgmt/README.rst
  azure-mgmt/setup.py
  azure/README.rst
  azure/setup.py
Labels: Packaging

#1973 [AutoPR eventgrid/data-plane] [EventGrid/ACR] Add schema of ACR events published to Event Grid
  azure-eventgrid/azure/eventgrid/models/__init__.py
  azure-eventgrid/azure/eventgrid/models/container_registry_event_actor.py
  azure-eventgrid/azure/eventgrid/models/container_registry_event_data.py
  azure-eventgrid/azure/eventgrid/models/container_registry_event_request.py
  azure-eventgrid/azure/eventgrid/models/container_registry_event_source.py
  azure-eventgrid/azure/eventgrid/models/container_registry_event_target.py
  azure-eventgrid/azure/eventgrid/models/container_registry_image_deleted_event_data.py
  azure-eventgrid/azure/eventgrid/models/container_registry_image_pushed_event_data.py
Labels: RestPRMerged

#1984 [AutoPR automation/resource-manager] Move automation py to 0.2.0
  azure-mgmt-automation/azure/mgmt/automation/version.py
Labels: RestPRMerged

#1987 [AutoPR hdinsight/resource-manager] HDInsight Python conf
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/hd_insight_management_client.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_endpoint.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_https_endpoint.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_properties.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/capabilities_result.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_create_parameters_extended.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_create_properties.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_definition.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_get_properties.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_list_persisted_script_actions_result.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_list_runtime_script_action_detail_result.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_monitoring_request.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_monitoring_response.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_patch_parameters.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/cluster_resize_parameters.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/compute_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/connectivity_endpoint.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/data_disks_groups.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/errors.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/execute_script_action_parameters.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/extension.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/hardware_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/http_connectivity_settings.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/linux_operating_system_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/operation.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/operation_display.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/operation_resource.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/os_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/quota_capability.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/quota_info.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/regional_quota_capability.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/regions_capability.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/resource.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/role.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/runtime_script_action.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/script_action.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/script_action_execution_summary.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/script_action_persisted_get_response_spec.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/security_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/ssh_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/ssh_public_key.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/storage_account.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/storage_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/version_spec.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/versions_capability.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/virtual_network_profile.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/vm_size_compatibility_filter.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/vm_sizes_capability.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/applications_operations.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/clusters_operations.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/configurations_operations.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/extension_operations.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/location_operations.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/operations.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/script_actions_operations.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/script_execution_history_operations.py
Labels: RestPRMerged

#1995 [AutoPR web/resource-manager] Update available stacks API
  azure-mgmt-web/azure/mgmt/web/models/__init__.py
  azure-mgmt-web/azure/mgmt/web/models/application_stack.py
  azure-mgmt-web/azure/mgmt/web/models/application_stack_paged.py
  azure-mgmt-web/azure/mgmt/web/models/stack_major_version.py
  azure-mgmt-web/azure/mgmt/web/models/stack_minor_version.py
  azure-mgmt-web/azure/mgmt/web/operations/app_service_certificate_orders_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/app_service_environments_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/app_service_plans_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/certificate_registration_provider_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/certificates_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/deleted_web_apps_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/diagnostics_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/domain_registration_provider_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/domains_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/provider_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/recommendations_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/top_level_domains_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
  azure-mgmt-web/azure/mgmt/web/web_site_management_client.py
Labels: RestPRMerged

#2009 [AutoPR monitor/resource-manager] Update monitor Py conf
  azure-mgmt-monitor/azure/mgmt/monitor/version.py
Labels: RestPRMerged

#2007 [AutoPR monitor/resource-manager] [DO NOT MERGE, until feb 20] Adding 2018-01-01 version for metrics API
  azure-mgmt-monitor/azure/mgmt/monitor/models/__init__.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/event_data.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/metric_definition.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/response.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/voice_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/monitor_management_client.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/action_groups_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/metric_definitions_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/metrics_operations.py
Labels: RestPRMerged

#1993 [AutoPR authorization/resource-manager] fix the hardcoding of api version for classicadmin in powershell
  azure-mgmt-authorization/azure/mgmt/authorization/operations/classic_administrators_operations.py
  azure-mgmt-authorization/azure/mgmt/authorization/operations/permissions_operations.py
  azure-mgmt-authorization/azure/mgmt/authorization/operations/provider_operations_metadata_operations.py
  azure-mgmt-authorization/azure/mgmt/authorization/operations/role_assignments_operations.py
  azure-mgmt-authorization/azure/mgmt/authorization/operations/role_definitions_operations.py
Labels: RestPRMerged

#1816 [ServiceBus] Automatic PR from RestAPI-PR2267
  azure-mgmt-servicebus/HISTORY.rst
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/access_keys.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/action.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/authorization_rule_properties.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/capture_description.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/check_name_availability.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/check_name_availability_result.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/correlation_filter.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/destination.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/error_response.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/message_count_details.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/operation.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/operation_display.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/premium_messaging_regions_properties.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/regenerate_access_key_parameters.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/resource.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_sku.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_subscription.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/sql_filter.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/disaster_recovery_configs_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/event_hubs_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/namespaces_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/premium_messaging_regions_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/queues_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/regions_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/rules_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/subscriptions_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/topics_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/version.py
Labels: ARM, Non breaking

#1945 [AutoPR hanaonazure/resource-manager] Add Hana storage information
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/disk.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/ip_address.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/storage_profile.py
Labels: RestPRMerged

#2003 [AutoPR resources/resource-manager] Change statusMessage property to wildcard type.
  azure-mgmt-resource/azure/mgmt/resource/features/v2015_12_01/operations/features_operations.py
  azure-mgmt-resource/azure/mgmt/resource/links/v2016_09_01/operations/resource_links_operations.py
  azure-mgmt-resource/azure/mgmt/resource/locks/v2015_01_01/operations/management_locks_operations.py
  azure-mgmt-resource/azure/mgmt/resource/locks/v2016_09_01/operations/management_locks_operations.py
  azure-mgmt-resource/azure/mgmt/resource/managedapplications/operations/application_definitions_operations.py
  azure-mgmt-resource/azure/mgmt/resource/managedapplications/operations/applications_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2015_10_01_preview/operations/policy_assignments_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2015_10_01_preview/operations/policy_definitions_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2016_04_01/operations/policy_assignments_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2016_04_01/operations/policy_definitions_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2016_12_01/operations/policy_assignments_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2016_12_01/operations/policy_definitions_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2017_06_01_preview/operations/policy_assignments_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2017_06_01_preview/operations/policy_definitions_operations.py
  azure-mgmt-resource/azure/mgmt/resource/policy/v2017_06_01_preview/operations/policy_set_definitions_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/operations/deployment_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/operations/deployments_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/operations/providers_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/operations/resource_groups_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/operations/resources_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_02_01/operations/tags_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/deployment_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/deployments_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/providers_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/resource_groups_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/resources_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2016_09_01/operations/tags_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/operations/deployment_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/operations/deployments_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/operations/providers_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/operations/resource_groups_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/operations/resources_operations.py
  azure-mgmt-resource/azure/mgmt/resource/resources/v2017_05_10/operations/tags_operations.py
  azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/operations/subscriptions_operations.py
  azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2016_06_01/operations/tenants_operations.py
Labels: RestPRMerged

#2013 [AutoPR graphrbac/data-plane] Added custom key identifier
  azure-graphrbac/azure/graphrbac/models/key_credential.py
  azure-graphrbac/azure/graphrbac/operations/applications_operations.py
  azure-graphrbac/azure/graphrbac/operations/domains_operations.py
  azure-graphrbac/azure/graphrbac/operations/groups_operations.py
  azure-graphrbac/azure/graphrbac/operations/objects_operations.py
  azure-graphrbac/azure/graphrbac/operations/service_principals_operations.py
  azure-graphrbac/azure/graphrbac/operations/users_operations.py
  azure-graphrbac/azure/graphrbac/version.py
Labels: RestPRMerged

#1999 [AutoPR consumption/resource-manager] Updating $filter parameter sample values in examples. Earlier version had incorrect format for the date values.
  azure-mgmt-consumption/azure/mgmt/consumption/operations/budgets_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/marketplaces_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/price_sheet_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/reservations_details_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/reservations_summaries_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/usage_details_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/version.py
  azure-mgmt-consumption/tests/recordings/test_mgmt_consumption.test_consumption_subscription_price_sheet.yaml
Labels: RestPRMerged

#1968 [AutoPR resources/resource-manager/managementgroups/resource-manager] Move ManagementGroups out of Resources to a separate folder
  azure-mgmt-managementgroups/HISTORY.rst
  azure-mgmt-managementgroups/MANIFEST.in
  azure-mgmt-managementgroups/README.rst
  azure-mgmt-managementgroups/azure/__init__.py
  azure-mgmt-managementgroups/azure/mgmt/__init__.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/__init__.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/management_groups_api.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/__init__.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/create_management_group_request.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/error_details.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/error_response.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_group.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_group_child_info.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_group_details.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_group_info.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_group_info_paged.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/operation.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/operation_display.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/operation_paged.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/parent_group_info.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/__init__.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_group_subscriptions_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_groups_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/version.py
  azure-mgmt-managementgroups/azure_bdist_wheel.py
  azure-mgmt-managementgroups/setup.cfg
  azure-mgmt-managementgroups/setup.py
Labels: RestPRMerged

#1975 [AutoPR commerce/resource-manager] Add type and format specifiers on quantity property.
  azure-mgmt-commerce/HISTORY.rst
  azure-mgmt-commerce/README.rst
  azure-mgmt-commerce/azure/mgmt/commerce/models/error_response.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/info_field.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/meter_info.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/monetary_commitment.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/monetary_credit.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/offer_term_info.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/rate_card_query_parameters.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/recurring_charge.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/resource_rate_card_info.py
  azure-mgmt-commerce/azure/mgmt/commerce/models/usage_aggregation.py
  azure-mgmt-commerce/azure/mgmt/commerce/operations/rate_card_operations.py
  azure-mgmt-commerce/azure/mgmt/commerce/operations/usage_aggregates_operations.py
  azure-mgmt-commerce/azure/mgmt/commerce/usage_management_client.py
  azure-mgmt-commerce/azure/mgmt/commerce/version.py
  azure-mgmt-commerce/setup.py
  azure-mgmt-commerce/tests/recordings/test_mgmt_commerce.test_commerce.yaml
  azure-mgmt-commerce/tests/test_mgmt_commerce.py
Labels: RestPRMerged

#2031 [AutoPR web/resource-manager] Suppress RPC R3019 per discussion at https://github.com/Azure/azure-r…
  azure-mgmt-web/azure/mgmt/web/version.py
Labels: RestPRMerged

#2028 [AutoPR relay/resource-manager] Relay: Added the missing API discovered in ARM_RP_Fundamentals
  azure-mgmt-relay/azure/mgmt/relay/models/access_keys.py
  azure-mgmt-relay/azure/mgmt/relay/models/authorization_rule.py
  azure-mgmt-relay/azure/mgmt/relay/models/check_name_availability.py
  azure-mgmt-relay/azure/mgmt/relay/models/check_name_availability_result.py
  azure-mgmt-relay/azure/mgmt/relay/models/error_response.py
  azure-mgmt-relay/azure/mgmt/relay/models/operation.py
  azure-mgmt-relay/azure/mgmt/relay/models/operation_display.py
  azure-mgmt-relay/azure/mgmt/relay/models/regenerate_access_key_parameters.py
  azure-mgmt-relay/azure/mgmt/relay/models/resource.py
  azure-mgmt-relay/azure/mgmt/relay/models/sku.py
  azure-mgmt-relay/azure/mgmt/relay/operations/hybrid_connections_operations.py
  azure-mgmt-relay/azure/mgmt/relay/operations/namespaces_operations.py
  azure-mgmt-relay/azure/mgmt/relay/operations/operations.py
  azure-mgmt-relay/azure/mgmt/relay/operations/wcf_relays_operations.py
  azure-mgmt-relay/azure/mgmt/relay/version.py
Labels: RestPRMerged

#2047 [AutoPR locationbasedservices/resource-manager] locationbasedservices py conf
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/__init__.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/client.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/__init__.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/client_enums.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/error.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/error_details_item.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_account.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_account_create_parameters.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_account_keys.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_account_paged.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_account_update_parameters.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_accounts_move_request.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_key_specification.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_operations_value_item.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_operations_value_item_display.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/location_based_services_operations_value_item_paged.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/resource.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/models/sku.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/operations/__init__.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/operations/accounts_operations.py
  azure-mgmt-locationbasedservices/azure/mgmt/locationbasedservices/version.py
Labels: RestPRMerged

#2049 [AutoPR servicebus/resource-manager] ServiceBus: Added enableBatchedOperations property to ServiceBus Queue
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/sb_queue.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/disaster_recovery_configs_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/event_hubs_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/namespaces_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/premium_messaging_regions_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/queues_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/regions_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/rules_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/subscriptions_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/topics_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/version.py
Labels: RestPRMerged

#2064 [AutoPR web/resource-manager] Web Python conf
  azure-mgmt-web/azure/mgmt/web/version.py
Labels: RestPRMerged
