Repository Azure/azure-sdk-for-python, pull requests merged in 2018-05, with the labels that each got.

#2506 [AutoPR apimanagement/resource-manager] Paths to examples fixed
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/api_management_client.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_release_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_version_set_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/authorization_server_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/authorization_server_update_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/backend_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/backend_reconnect_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/certificate_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/diagnostic_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/email_template_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/group_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/identity_provider_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/issue_attachment_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/issue_comment_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/issue_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/logger_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/notification_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/openid_connect_provider_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/operation_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/policy_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/portal_delegation_settings_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/portal_signin_settings_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/portal_signup_settings_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/product_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/property_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/recipient_email_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/recipient_user_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/schema_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/subscription_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/tag_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/tag_description_contract_py3.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/user_contract_py3.py
Labels: RestPRMerged

#2436 [AutoPR web/resource-manager] Fix for https://github.com/Azure/azure-rest-api-specs/issues/2907
  azure-mgmt-web/azure/mgmt/web/models/__init__.py
  azure-mgmt-web/azure/mgmt/web/models/data_table_response_column.py
  azure-mgmt-web/azure/mgmt/web/models/data_table_response_object.py
  azure-mgmt-web/azure/mgmt/web/models/detector_info.py
  azure-mgmt-web/azure/mgmt/web/models/detector_response.py
  azure-mgmt-web/azure/mgmt/web/models/detector_response_paged.py
  azure-mgmt-web/azure/mgmt/web/models/diagnostic_data.py
  azure-mgmt-web/azure/mgmt/web/models/rendering.py
  azure-mgmt-web/azure/mgmt/web/models/web_site_management_client_enums.py
  azure-mgmt-web/azure/mgmt/web/operations/diagnostics_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Labels: RestPRMerged

#2501 [AutoPR compute/resource-manager] fixed formatting
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/data_disk.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/data_disk_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_disk.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_disk_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_scale_set_os_disk.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/virtual_machine_scale_set_os_disk_py3.py
Labels: RestPRMerged

#2479 [AutoPR trafficmanager/resource-manager] Introduce Azure Traffic Manager 2018-03-01 API version with custom he…
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/__init__.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/endpoint.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/endpoint_properties_custom_headers_item.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/heat_map_model.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/monitor_config.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/monitor_config_custom_headers_item.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/monitor_config_expected_status_code_ranges_item.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/profile.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/proxy_resource.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/resource.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/tracked_resource.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/traffic_manager_geographic_hierarchy.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/models/traffic_manager_user_metrics_key_model.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/operations/__init__.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/operations/endpoints_operations.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/operations/geographic_hierarchies_operations.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/operations/heat_map_operations.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/operations/profiles_operations.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/operations/traffic_manager_user_metrics_keys_operations.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/traffic_manager_management_client.py
  azure-mgmt-trafficmanager/azure/mgmt/trafficmanager/version.py
Labels: RestPRMerged

#2513 [AutoPR monitor/resource-manager] Minor Updates - description text
  azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/source.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/source_py3.py
Labels: RestPRMerged

#2523 [AutoPR signalr/resource-manager] update CheckNameAvailability resource to add extra location in its route
  azure-mgmt-signalr/azure/mgmt/signalr/operations/signal_roperations.py
Labels: RestPRMerged

#2528 [AutoPR automation/resource-manager] Edit property names for SourceControlSyncJob
  azure-mgmt-automation/azure/mgmt/automation/models/__init__.py
  azure-mgmt-automation/azure/mgmt/automation/models/automation_client_enums.py
  azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_configuration_create_or_update_parameters.py
  azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_configuration_create_or_update_parameters_properties.py
  azure-mgmt-automation/azure/mgmt/automation/models/hybrid_runbook_worker.py
  azure-mgmt-automation/azure/mgmt/automation/models/job.py
  azure-mgmt-automation/azure/mgmt/automation/models/job_collection_item.py
  azure-mgmt-automation/azure/mgmt/automation/models/linux_properties.py
  azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job.py
  azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id.py
  azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_by_id_errors.py
  azure-mgmt-automation/azure/mgmt/automation/models/webhook.py
  azure-mgmt-automation/azure/mgmt/automation/models/windows_properties.py
  azure-mgmt-automation/azure/mgmt/automation/operations/dsc_node_configuration_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/hybrid_runbook_worker_group_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/job_schedule_operations.py
Labels: RestPRMerged

#2533 [AutoPR web/resource-manager] Fix for https://github.com/Azure/azure-rest-api-specs/issues/2907. Missed the production slot APIs earlier.
  azure-mgmt-web/azure/mgmt/web/operations/app_service_environments_operations.py
  azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Labels: RestPRMerged

#2122 [AutoPR] policyinsights/resource-manager
  azure-mgmt-policyinsights/HISTORY.rst
  azure-mgmt-policyinsights/MANIFEST.in
  azure-mgmt-policyinsights/README.rst
  azure-mgmt-policyinsights/azure/__init__.py
  azure-mgmt-policyinsights/azure/mgmt/__init__.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/__init__.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/__init__.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/operation.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/operation_display.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/operation_display_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/operation_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/operations_list_results.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/operations_list_results_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_assignment_summary.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_assignment_summary_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_definition_summary.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_definition_summary_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_event.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_event_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_events_query_results.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_events_query_results_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_insights_client_enums.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_state.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_state_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_states_query_results.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_states_query_results_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_failure.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_failure_error.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_failure_error_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_failure_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_options.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_options_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/summarize_results.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/summarize_results_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/summary.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/summary_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/summary_results.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/summary_results_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/__init__.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/operations.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/policy_events_operations.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/policy_states_operations.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/policy_insights_client.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/version.py
  azure-mgmt-policyinsights/azure_bdist_wheel.py
  azure-mgmt-policyinsights/setup.cfg
  azure-mgmt-policyinsights/setup.py
Labels: ServicePR

#2535 [AutoPR] cognitiveservices/data-plane/VisualSearch
  azure-cognitiveservices-search-visualsearch/HISTORY.rst
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/filters.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/filters_py3.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/image_info.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/image_info_py3.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/knowledge_request.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/knowledge_request_py3.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/visual_search_request.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/models/visual_search_request_py3.py
  azure-cognitiveservices-search-visualsearch/azure/cognitiveservices/search/visualsearch/version.py
Labels: ServicePR

#2413 [AutoPR] signalr/resource-manager
  azure-mgmt-signalr/HISTORY.rst
  azure-mgmt-signalr/MANIFEST.in
  azure-mgmt-signalr/README.rst
  azure-mgmt-signalr/azure/__init__.py
  azure-mgmt-signalr/azure/mgmt/__init__.py
  azure-mgmt-signalr/azure/mgmt/signalr/__init__.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/__init__.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/metric_specification.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/metric_specification_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability_parameters.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability_parameters_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/operation.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/operation_display.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/operation_display_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/operation_paged.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/operation_properties.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/operation_properties_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/operation_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/regenerate_key_parameters.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/regenerate_key_parameters_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/resource.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/resource_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/service_specification.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/service_specification_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_parameters.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_parameters_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rkeys.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rkeys_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rmanagement_client_enums.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_paged.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rupdate_parameters.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rupdate_parameters_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/tracked_resource.py
  azure-mgmt-signalr/azure/mgmt/signalr/models/tracked_resource_py3.py
  azure-mgmt-signalr/azure/mgmt/signalr/operations/__init__.py
  azure-mgmt-signalr/azure/mgmt/signalr/operations/operations.py
  azure-mgmt-signalr/azure/mgmt/signalr/operations/signal_roperations.py
  azure-mgmt-signalr/azure/mgmt/signalr/signal_rmanagement_client.py
  azure-mgmt-signalr/azure/mgmt/signalr/version.py
  azure-mgmt-signalr/azure_bdist_wheel.py
  azure-mgmt-signalr/setup.cfg
  azure-mgmt-signalr/setup.py
Labels: ServicePR

#2526 [AutoPR maps/resource-manager] Azure maps resource provider
  azure-mgmt-maps/HISTORY.rst
  azure-mgmt-maps/MANIFEST.in
  azure-mgmt-maps/README.rst
  azure-mgmt-maps/azure/__init__.py
  azure-mgmt-maps/azure/mgmt/__init__.py
  azure-mgmt-maps/azure/mgmt/maps/__init__.py
  azure-mgmt-maps/azure/mgmt/maps/maps_management_client.py
  azure-mgmt-maps/azure/mgmt/maps/models/__init__.py
  azure-mgmt-maps/azure/mgmt/maps/models/error.py
  azure-mgmt-maps/azure/mgmt/maps/models/error_details_item.py
  azure-mgmt-maps/azure/mgmt/maps/models/error_details_item_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/error_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_create_parameters.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_create_parameters_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_keys.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_keys_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_paged.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_update_parameters.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_account_update_parameters_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_accounts_move_request.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_accounts_move_request_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_key_specification.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_key_specification_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_management_client_enums.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_operations_value_item.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_operations_value_item_display.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_operations_value_item_display_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_operations_value_item_paged.py
  azure-mgmt-maps/azure/mgmt/maps/models/maps_operations_value_item_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/resource.py
  azure-mgmt-maps/azure/mgmt/maps/models/resource_py3.py
  azure-mgmt-maps/azure/mgmt/maps/models/sku.py
  azure-mgmt-maps/azure/mgmt/maps/models/sku_py3.py
  azure-mgmt-maps/azure/mgmt/maps/operations/__init__.py
  azure-mgmt-maps/azure/mgmt/maps/operations/accounts_operations.py
  azure-mgmt-maps/azure/mgmt/maps/version.py
  azure-mgmt-maps/azure_bdist_wheel.py
  azure-mgmt-maps/setup.cfg
  azure-mgmt-maps/setup.py
Labels: RestPRInProgress

#2539 [AutoPR eventgrid/data-plane] Add ServiceBus Messaging Integration Events with EventGrid to the Eve…
  azure-eventgrid/azure/eventgrid/models/__init__.py
  azure-eventgrid/azure/eventgrid/models/service_bus_active_messages_available_with_no_listeners_event_data.py
  azure-eventgrid/azure/eventgrid/models/service_bus_active_messages_available_with_no_listeners_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/service_bus_deadletter_messages_available_with_no_listeners_event_data.py
  azure-eventgrid/azure/eventgrid/models/service_bus_deadletter_messages_available_with_no_listeners_event_data_py3.py
Labels: RestPRMerged

#2545 [AutoPR postgresql/resource-manager] Add serverSecurityAlertPolicies APIs for postgresql servers
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/__init__.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/postgre_sql_management_client_enums.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_security_alert_policy.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_security_alert_policy_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/__init__.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/server_security_alert_policies_operations.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/postgre_sql_management_client.py
Labels: RestPRMerged

#2531 [AutoPR datalake-analytics/data-plane] [ADLA] - Catalog - Support table preview
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/__init__.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_preview.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_preview_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/operations/catalog_operations.py
Labels: RestPRMerged

#2505 [AutoPR compute/resource-manager] added autoOSUpgradePolicy to UpgradePolicy
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/__init__.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/auto_os_upgrade_policy.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/auto_os_upgrade_policy_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/upgrade_policy.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/upgrade_policy_py3.py
Labels: RestPRMerged

#2551 [AutoPR containerservices/resource-manager] [AKS] remove unsupported VM types
  azure-mgmt-containerservice/azure/mgmt/containerservice/container_service_client.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_agent_pool_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_agent_pool_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_client_enums.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_master_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_master_profile_py3.py
Labels: RestPRMerged

#2554 [AutoPR managementgroups/resource-manager] Fix error in the possible values for an enum - Management Groups
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request_py3.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_groups_api_enums.py
Labels: RestPRMerged

#2481 [AutoPR cosmos-db/resource-manager] Swagger changes to introduce REST APIs for offline and online region for the Cosmos DB account
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/cosmos_db.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/__init__.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/error_response.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/error_response_py3.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/region_for_online_offline.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/region_for_online_offline_py3.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/database_accounts_operations.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/version.py
Labels: RestPRMerged

#2565 [AutoPR hanaonazure/resource-manager] HanaOnAzure: Remove incorrectly-added SKU from enum
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile.py
Labels: RestPRMerged

#2548 [AutoPR batchai/resource-manager] BatchAI. Several fixes
  azure-mgmt-batchai/azure/mgmt/batchai/models/cluster_py3.py
  azure-mgmt-batchai/azure/mgmt/batchai/models/experiment_py3.py
  azure-mgmt-batchai/azure/mgmt/batchai/models/file_server_py3.py
  azure-mgmt-batchai/azure/mgmt/batchai/models/job_create_parameters.py
  azure-mgmt-batchai/azure/mgmt/batchai/models/job_create_parameters_py3.py
  azure-mgmt-batchai/azure/mgmt/batchai/models/job_py3.py
  azure-mgmt-batchai/azure/mgmt/batchai/models/workspace_py3.py
  azure-mgmt-batchai/azure/mgmt/batchai/operations/experiments_operations.py
Labels: RestPRMerged

#2571 [AutoPR eventgrid/data-plane] EventGrid Dataplane: Added schemas corresponding to SubscriptionValidationEvent/Response and SubscriptionDeletedEvent
  azure-eventgrid/azure/eventgrid/models/__init__.py
  azure-eventgrid/azure/eventgrid/models/container_registry_image_deleted_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/container_registry_image_pushed_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/iot_hub_device_created_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/iot_hub_device_deleted_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/subscription_deleted_event_data.py
  azure-eventgrid/azure/eventgrid/models/subscription_deleted_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/subscription_validation_event_data.py
  azure-eventgrid/azure/eventgrid/models/subscription_validation_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/subscription_validation_response.py
  azure-eventgrid/azure/eventgrid/models/subscription_validation_response_py3.py
Labels: RestPRMerged

#2027 [AutoPR] hanaonazure/resource-manager
  azure-mgmt-hanaonazure/HISTORY.rst
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/disk.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/ip_address.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/storage_profile.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/hana_instances_operations.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/operations.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: ServicePR

#2587 [AutoPR eventgrid/data-plane] Adding Media Services Event Grid schema
  azure-eventgrid/azure/eventgrid/models/__init__.py
  azure-eventgrid/azure/eventgrid/models/event_grid_client_enums.py
  azure-eventgrid/azure/eventgrid/models/media_job_state_change_event_data.py
  azure-eventgrid/azure/eventgrid/models/media_job_state_change_event_data_py3.py
Labels: RestPRMerged

#2581 [AutoPR managementgroups/resource-manager] Add Management Groups 2018-03-01-preview version
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/management_groups_api.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/__init__.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request_py3.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/entity_info.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/entity_info_py3.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_groups_api_enums.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/tenant_backfill_status_result.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/tenant_backfill_status_result_py3.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/entities_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_group_subscriptions_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_groups_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/version.py
Labels: RestPRMerged

#2592 [AutoPR monitor/resource-manager] Add "autoMitigate" to Metric Alert API spec for 2018-03-01
  azure-mgmt-monitor/azure/mgmt/monitor/models/action_group_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/activity_log_alert_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/alert_rule_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/alerting_action_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/autoscale_setting_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/az_ns_action_group_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_category_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/diagnostic_settings_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/location_threshold_rule_condition_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/log_profile_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/log_search_rule_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/management_event_rule_condition_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource_patch.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource_patch_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/metric_alert_single_resource_multiple_metric_criteria_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/rule_email_action_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/rule_management_event_data_source_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/rule_metric_data_source_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/rule_webhook_action_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/source.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/source_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/threshold_rule_condition_py3.py
Labels: RestPRMerged

#2582 [AutoPR automation/resource-manager] Fixing responses for update management swagger
  azure-mgmt-automation/azure/mgmt/automation/automation_client.py
  azure-mgmt-automation/azure/mgmt/automation/models/__init__.py
  azure-mgmt-automation/azure/mgmt/automation/models/automation_client_enums.py
  azure-mgmt-automation/azure/mgmt/automation/models/dsc_node_configuration_create_or_update_parameters.py
  azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_stream.py
  azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_stream_by_id.py
  azure-mgmt-automation/azure/mgmt/automation/models/source_control_sync_job_stream_paged.py
  azure-mgmt-automation/azure/mgmt/automation/operations/__init__.py
  azure-mgmt-automation/azure/mgmt/automation/operations/software_update_configuration_machine_runs_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/software_update_configuration_runs_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/software_update_configurations_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/source_control_sync_job_streams_operations.py
Labels: RestPRMerged

#2580 [AutoPR compute/resource-manager] Upgrade Compute API version and Fix the response of POST response
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/__init__.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/access_uri.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/access_uri_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/api_error.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/api_error_base.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/api_error_base_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/api_error_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/inner_error.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/inner_error_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/operation_status_response.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/operation_status_response_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/operations/disks_operations.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/operations/snapshots_operations.py
Labels: RestPRMerged

#2583 [AutoPR containerservices/resource-manager] [AKS] add POST endpoint for fetching accessProfiles
  azure-mgmt-containerservice/azure/mgmt/containerservice/container_service_client.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/container_service_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/managed_cluster_access_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/models/managed_cluster_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/operations/managed_clusters_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/version.py
Labels: RestPRMerged

#2599 [AutoPR managementgroups/resource-manager] Fix typo in enum
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/check_name_availability_request_py3.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/management_groups_api_enums.py
Labels: RestPRMerged

#2567 [AutoPR servicefabric/resource-manager] Fix SFRP map types and error model
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/__init__.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_delta_health_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_health_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_parameter.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_resource.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_resource_update.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_type_resource.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_type_version_resource.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_type_version_resource_list.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/application_upgrade_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_health_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_update_parameters.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_upgrade_delta_health_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_upgrade_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/error_model.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/error_model_error.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/node_type_description.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/proxy_resource.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/resource.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/rolling_upgrade_monitoring_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/server_certificate_common_name.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/server_certificate_common_names.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_correlation_description.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_fabric_management_client_enums.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_load_metric_description.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_resource.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_resource_properties.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_resource_properties_base.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_resource_update.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_resource_update_properties.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_type_delta_health_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_type_health_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/service_type_health_policy_map_item.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/stateful_service_properties.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/stateful_service_update_properties.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/stateless_service_properties.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/stateless_service_update_properties.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/__init__.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/application_type_versions_operations.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/application_types_operations.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/applications_operations.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/cluster_versions_operations.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/clusters_operations.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/operations.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/operations/services_operations.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/service_fabric_management_client.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/version.py
Labels: RestPRMerged

#2613 [AutoPR applicationinsights/resource-manager] [AppInsights] Added webtests-by-component API to 2015-05-01
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py
Labels: RestPRMerged

#2627 [AutoPR sql/resource-manager] Use common Resource & Sku definitions in all Sql specs
  azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  azure-mgmt-sql/azure/mgmt/sql/models/database.py
  azure-mgmt-sql/azure/mgmt/sql/models/database_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/elastic_pool.py
  azure-mgmt-sql/azure/mgmt/sql/models/elastic_pool_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/job_agent.py
  azure-mgmt-sql/azure/mgmt/sql/models/job_agent_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_database.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_database_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/server.py
  azure-mgmt-sql/azure/mgmt/sql/models/server_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/sku.py
  azure-mgmt-sql/azure/mgmt/sql/models/sku_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/tracked_resource.py
  azure-mgmt-sql/azure/mgmt/sql/models/tracked_resource_py3.py
  azure-mgmt-sql/azure/mgmt/sql/version.py
Labels: RestPRMerged

#2629 [AutoPR servermanagement/resource-manager] Fix Python conf of servermanager
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/__init__.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/__init__.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/encryption_jwk_resource.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/encryption_jwk_resource_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/error.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/error_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_parameters.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_parameters_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_profile.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_profile_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_resource.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_resource_paged.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_resource_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_status.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/gateway_status_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/node_parameters.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/node_parameters_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/node_resource.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/node_resource_paged.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/node_resource_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_parameters.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_parameters_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_result.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_result_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_results.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_results_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_status.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_command_status_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_session_resource.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_session_resource_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_session_resources.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_session_resources_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_tab_completion_parameters.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_tab_completion_parameters_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_tab_completion_results.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/power_shell_tab_completion_results_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/prompt_field_description.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/prompt_field_description_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/prompt_message_response.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/prompt_message_response_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/resource.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/resource_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/server_management_enums.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/session_parameters.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/session_parameters_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/session_resource.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/session_resource_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/version.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/models/version_py3.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/operations/__init__.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/operations/gateway_operations.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/operations/node_operations.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/operations/power_shell_operations.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/operations/session_operations.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/server_management.py
  azure-mgmt-servermanagement/azure/mgmt/servermanagement/version.py
Labels: RestPRMerged

#2634 [AutoPR] sql/resource-manager
  azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  azure-mgmt-sql/azure/mgmt/sql/models/database.py
  azure-mgmt-sql/azure/mgmt/sql/models/database_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/elastic_pool.py
  azure-mgmt-sql/azure/mgmt/sql/models/elastic_pool_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/job_agent.py
  azure-mgmt-sql/azure/mgmt/sql/models/job_agent_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_database.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_database_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/server.py
  azure-mgmt-sql/azure/mgmt/sql/models/server_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/sku.py
  azure-mgmt-sql/azure/mgmt/sql/models/sku_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/tracked_resource.py
  azure-mgmt-sql/azure/mgmt/sql/models/tracked_resource_py3.py
Labels: ServicePR

#2643 [AutoPR keyvault/data-plane] RSA key size examples, ECC descriptions
  azure-keyvault/azure/keyvault/key_vault_client.py
  azure-keyvault/azure/keyvault/models/certificate_attributes_py3.py
  azure-keyvault/azure/keyvault/models/deleted_certificate_bundle_py3.py
  azure-keyvault/azure/keyvault/models/deleted_certificate_item_py3.py
  azure-keyvault/azure/keyvault/models/deleted_key_bundle_py3.py
  azure-keyvault/azure/keyvault/models/deleted_key_item_py3.py
  azure-keyvault/azure/keyvault/models/deleted_secret_bundle_py3.py
  azure-keyvault/azure/keyvault/models/deleted_secret_item_py3.py
  azure-keyvault/azure/keyvault/models/key_attributes_py3.py
  azure-keyvault/azure/keyvault/models/key_create_parameters.py
  azure-keyvault/azure/keyvault/models/key_create_parameters_py3.py
  azure-keyvault/azure/keyvault/models/key_properties.py
  azure-keyvault/azure/keyvault/models/key_properties_py3.py
  azure-keyvault/azure/keyvault/models/key_vault_client_enums.py
  azure-keyvault/azure/keyvault/models/secret_attributes_py3.py
  azure-keyvault/build.json
Labels: RestPRMerged

#2652 [AutoPR network/resource-manager] Fix foir Azure Networking swagger
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/__init__.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_authentication_certificate.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_authentication_certificate_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_backend_address_pool.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_backend_address_pool_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_backend_http_settings.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_backend_http_settings_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_frontend_ip_configuration.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_frontend_ip_configuration_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_frontend_port.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_frontend_port_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_http_listener.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_http_listener_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_ip_configuration.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_ip_configuration_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_path_rule.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_path_rule_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_probe.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_probe_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_redirect_configuration.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_redirect_configuration_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_request_routing_rule.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_request_routing_rule_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_ssl_certificate.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_ssl_certificate_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_ssl_predefined_policy.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_ssl_predefined_policy_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_url_path_map.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/application_gateway_url_path_map_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/express_route_circuit_arp_table.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/express_route_circuit_arp_table_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/express_route_circuit_routes_table.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/express_route_circuit_routes_table_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/express_route_circuit_routes_table_summary.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/express_route_circuit_routes_table_summary_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/flow_log_information.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/flow_log_information_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/flow_log_status_parameters.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/flow_log_status_parameters_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/network_management_client_enums.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/traffic_analytics_configuration_properties.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/traffic_analytics_configuration_properties_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/traffic_analytics_properties.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/traffic_analytics_properties_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/virtual_network_gateway_sku.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/models/virtual_network_gateway_sku_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/operations/network_watchers_operations.py
Labels: RestPRMerged

#2598 [AutoPR consumption/resource-manager] Adding swagger for new api-version consumption 2018-05-31, introducing new Forecast api swagger
  azure-mgmt-consumption/azure/mgmt/consumption/consumption_management_client.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/__init__.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/budget.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/budget_paged.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/budget_time_period.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/consumption_management_client_enums.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/cost_tag.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/cost_tags.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/current_spend.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/filters.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/forecast.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/forecast_paged.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/forecast_properties_confidence_levels_item.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/marketplace.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/marketplace_paged.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/meter_details.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/notification.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/price_sheet_properties.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/price_sheet_result.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/proxy_resource.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/query_options.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_details.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_details_paged.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_recommendations.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_summaries.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/reservation_summaries_paged.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/resource_attributes.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/tag.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/tags.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/usage_detail.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/usage_detail_paged.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/__init__.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/budgets_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/cost_tags_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/forecasts_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/marketplaces_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/price_sheet_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/reservations_details_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/reservations_summaries_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/tags_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/usage_details_operations.py
Labels: RestPRMerged

#2668 [AutoPR network/resource-manager] reverted methods removal
  azure-mgmt-network/azure/mgmt/network/v2018_04_01/operations/virtual_network_gateways_operations.py
Labels: RestPRMerged

#2664 [AutoPR compute/resource-manager] [Disk swagger] Removing resourceUpdate, adding contents to diskupdate and snapshotupdate
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/__init__.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/disk_update.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/disk_update_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/resource_update.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/resource_update_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/snapshot_update.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/snapshot_update_py3.py
Labels: RestPRMerged

#2640 [AutoPR sql/resource-manager] Adding new value to VA baseline name
  azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  azure-mgmt-sql/azure/mgmt/sql/models/sql_management_client_enums.py
  azure-mgmt-sql/azure/mgmt/sql/operations/database_vulnerability_assessment_rule_baselines_operations.py
  azure-mgmt-sql/azure/mgmt/sql/version.py
Labels: RestPRMerged

#2626 [AutoPR mysql/resource-manager/postgresql/resource-manager] ORCASQL VNET with API Version 2017-12-01 for Public Preview.
  azure-mgmt-rdbms/HISTORY.rst
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/__init__.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/configuration_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/database_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/firewall_rule_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/log_file_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/my_sql_management_client_enums.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server_properties_for_default_create_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server_properties_for_geo_restore_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server_properties_for_restore_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/server_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/tracked_resource_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/virtual_network_rule.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/virtual_network_rule_paged.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/models/virtual_network_rule_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/my_sql_management_client.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/operations/__init__.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/mysql/operations/virtual_network_rules_operations.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/__init__.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/configuration_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/database_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/firewall_rule_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/log_file_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/postgre_sql_management_client_enums.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_default_create_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_geo_restore_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_properties_for_restore_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_security_alert_policy.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/server_security_alert_policy_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/tracked_resource_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/virtual_network_rule.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/virtual_network_rule_paged.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/models/virtual_network_rule_py3.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/__init__.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/server_security_alert_policies_operations.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/operations/virtual_network_rules_operations.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/postgresql/postgre_sql_management_client.py
  azure-mgmt-rdbms/azure/mgmt/rdbms/version.py
  azure-mgmt-rdbms/sdk_packaging.toml
  azure-mgmt-rdbms/setup.py
Labels: RestPRMerged

#2672 [AutoPR iotcentral/resource-manager] Add specs for Microsoft.IoTCentral RP
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/__init__.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/iot_central_client.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/__init__.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_name_availability_info.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_name_availability_info_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_paged.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_patch.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_patch_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_sku_info.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/app_sku_info_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/error_details.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/error_details_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/iot_central_client_enums.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/operation.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/operation_display.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/operation_display_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/operation_inputs.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/operation_inputs_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/operation_paged.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/operation_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/resource.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/models/resource_py3.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/operations/__init__.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/operations/apps_operations.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/operations/operations.py
  azure-mgmt-iotcentral/azure/mgmt/iotcentral/version.py
Labels: RestPRMerged
