Repository Azure/azure-sdk-for-python, pull requests merged in 2019-09, with the labels that each got.

#6894 [EventHub] IoTHub management operations improvement and bug fixing
  sdk/eventhub/azure-eventhubs/azure/eventhub/_consumer_producer_mixin.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/tests/asynctests/test_iothub_receive_async.py
  sdk/eventhub/azure-eventhubs/tests/test_iothub_receive.py
Labels: Event Hubs

#7030 [AutoPR sql/resource-manager] chore: jsonfmt sql
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/private_endpoint_connection.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/private_endpoint_connection_paged.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/private_endpoint_connection_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/private_endpoint_property.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/private_endpoint_property_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/private_link_service_connection_state_property.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/private_link_service_connection_state_property_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/__init__.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/private_endpoint_connections_operations.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/sql_management_client.py
Labels: RestPRMerged

#6997 [AutoPR machinelearningservices/resource-manager] [READY TO MERGE] Adding workspace level quota management APIs in version 2019-06-01
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/_azure_machine_learning_workspaces.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/__init__.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_azure_machine_learning_workspaces_enums.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_models.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_models_py3.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_paged_models.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/__init__.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_quotas_operations.py
Labels: RestPRMerged

#7026 [EventHub] Retry refactor
  sdk/eventhub/azure-eventhubs/azure/eventhub/_consumer_producer_mixin.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_consumer_producer_mixin_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/error_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/error.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
Labels: Event Hubs

#7033 [AutoPR attestation/resource-manager] adding readme for attestation service
  sdk/attestation/azure-mgmt-attestation/HISTORY.rst
  sdk/attestation/azure-mgmt-attestation/MANIFEST.in
  sdk/attestation/azure-mgmt-attestation/README.rst
  sdk/attestation/azure-mgmt-attestation/azure/__init__.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/__init__.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/__init__.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/_attestation_management_client.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/_configuration.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/models/__init__.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/models/_attestation_management_client_enums.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/models/_models.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/models/_models_py3.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/operations/__init__.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/operations/_attestation_providers_operations.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/operations/_operations.py
  sdk/attestation/azure-mgmt-attestation/azure/mgmt/attestation/version.py
  sdk/attestation/azure-mgmt-attestation/sdk_packaging.toml
  sdk/attestation/azure-mgmt-attestation/setup.cfg
  sdk/attestation/azure-mgmt-attestation/setup.py
Labels: RestPRMerged

#7015 [AutoPR] storagecache/resource-manager
  sdk/storage/azure-mgmt-storagecache/HISTORY.rst
  sdk/storage/azure-mgmt-storagecache/MANIFEST.in
  sdk/storage/azure-mgmt-storagecache/README.rst
  sdk/storage/azure-mgmt-storagecache/azure/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/_configuration.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/_storage_cache_mgmt_client.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_models.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_models_py3.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_paged_models.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_storage_cache_mgmt_client_enums.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_caches_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_skus_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_storage_targets_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_usage_models_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/version.py
  sdk/storage/azure-mgmt-storagecache/sdk_packaging.toml
  sdk/storage/azure-mgmt-storagecache/setup.cfg
  sdk/storage/azure-mgmt-storagecache/setup.py
Labels: ServicePR

#6957 [azure-appconfig] make appconfig pylint clean
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/azure_configuration_client_async.py
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/azure_appconfiguration_client.py
Labels: AzConfig

#6964 Add kwargs to get_token
  sdk/core/azure-core/azure/core/credentials.py
  sdk/identity/azure-identity/azure/identity/_browser_auth.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
  sdk/identity/azure-identity/azure/identity/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/credentials.py
  sdk/identity/azure-identity/azure/identity/credentials.py
Labels: Azure.Identity, Client

#7036 [AutoPR azure-kusto/resource-manager] Update Kusto.json with TSVE data format
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/_kusto_management_client_enums.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/_models.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/_models_py3.py
Labels: RestPRMerged

#6870 [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to add version stable/2019-03-22
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/_iot_hub_client.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/__init__.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models_py3.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_certificates_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_resource_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_resource_provider_common_operations.py
Labels: RestPRMerged

#6992 [Core] Fix aiohttp auto-headers
  sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_universal_http.py
  sdk/core/azure-core/tests/test_requests_universal.py
Labels: Azure.Core

#6951 [Core] Added tracing to policies module init
  sdk/core/azure-core/azure/core/pipeline/policies/__init__.py
  sdk/core/azure-core/examples/test_example_sync.py
Labels: Azure.Core

#6939 Perform encrypt/verify/wrap locally when possible
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/__init__.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/_internal.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithm.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/__init__.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/aes_cbc.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/aes_cbc_hmac.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/aes_kw.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/ecdsa.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/rsa_encryption.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/rsa_signing.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/algorithms/sha_2.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/ec_key.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/jose.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/key.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/rsa_key.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/symmetric_key.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_internal/transform.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/client.py
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_ec_verify_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_encrypt_and_decrypt.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_encrypt_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_rsa_verify_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_sign_and_verify.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_wrap_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_ec_verify_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_encrypt_and_decrypt.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_encrypt_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_rsa_verify_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_sign_and_verify.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_wrap_local.yaml
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
  sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto.py
  sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto_async.py
  sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
Labels: Client, KeyVault

#7109 Eventhubs blobstorage checkpointstore merge to preview3
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/HISTORY.md
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/LICENSE
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/MANIFEST.in
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/README.md
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/blobstoragepm.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/conftest.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/dev_requirements.txt
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/examples/event_processor_blob_storage_example.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/sdk_packaging.toml
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.cfg
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.py
Labels: Client, Event Hubs

#6947 [AutoPR security/resource-manager] Improve API documentation and add DeviceSecurityGroups to stable API
  sdk/security/azure-mgmt-security/azure/mgmt/security/_security_center.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_paged_models.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_security_center_enums.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_device_security_groups_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_io_tsecurity_solutions_analytics_aggregated_alerts_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_io_tsecurity_solutions_analytics_recommendation_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_io_tsecurity_solutions_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_io_tsecurity_solutions_resource_group_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_iot_security_solution_analytics_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_iot_security_solution_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_iot_security_solutions_analytics_aggregated_alert_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_iot_security_solutions_analytics_recommendation_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_pricings_operations.py
Labels: RestPRMerged

#7164 [AutoPR compute/resource-manager] chore: jsonfmt compute
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Labels: RestPRMerged

#7133 Fix tracing if method raise exception
  sdk/core/azure-core/azure/core/tracing/decorator.py
  sdk/core/azure-core/azure/core/tracing/decorator_async.py
  sdk/core/azure-core/tests/test_tracing_decorator.py
Labels: Azure.Core, Client

#7169 Fix readme link
  sdk/identity/azure-identity/HISTORY.md
Labels: Azure.Identity, Client

#7139 Eventhubs preview3 documentation update
  sdk/eventhub/azure-eventhubs/HISTORY.md
  sdk/eventhub/azure-eventhubs/README.md
  sdk/eventhub/azure-eventhubs/azure/eventhub/__init__.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/eventprocessor/event_processor.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/eventprocessor/partition_manager.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/eventprocessor/partition_processor.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/common.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
  sdk/eventhub/azure-eventhubs/tests/test_longrunning_send.py
Labels: Client, Event Hubs

#7172 msal_extensions -> msal-extensions
  sdk/identity/azure-identity/setup.py
  shared_requirements.txt
Labels: Azure.Identity, Client

#7151 Key Vault: added example and fixed link in Certificates README
  sdk/keyvault/azure-keyvault-certificates/README.md
Labels: Client, KeyVault

#7132 Key Vault: fixed certificate docstring errors
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/client.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/client.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/models.py
  sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates.py
  sdk/keyvault/azure-keyvault-certificates/tests/test_examples_certificates_async.py
Labels: Client, KeyVault

#7182 [AutoPR containerregistry/resource-manager] [ACR] Adding scopemap spec file for new SDK build
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/_container_registry_management_client.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/_container_registry_management_client.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/__init__.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_container_registry_management_client_enums.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models_py3.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_paged_models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/operations/__init__.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/operations/_registries_operations.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/operations/_scope_maps_operations.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/operations/_tokens_operations.py
Labels: RestPRMerged

#7128 Key Vault: added certificate changelog
  sdk/keyvault/azure-keyvault-certificates/HISTORY.md
Labels: Client, KeyVault

#7125 azure-keyvault-nspkg
  .docsettings.yml
  scripts/devops_tasks/common_tasks.py
  sdk/keyvault/azure-keyvault-certificates/MANIFEST.in
  sdk/keyvault/azure-keyvault-certificates/dev_requirements.txt
  sdk/keyvault/azure-keyvault-certificates/setup.py
  sdk/keyvault/azure-keyvault-keys/MANIFEST.in
  sdk/keyvault/azure-keyvault-keys/dev_requirements.txt
  sdk/keyvault/azure-keyvault-keys/setup.py
  sdk/keyvault/azure-keyvault-nspkg/MANIFEST.in
  sdk/keyvault/azure-keyvault-nspkg/README.md
  sdk/keyvault/azure-keyvault-nspkg/azure/__init__.py
  sdk/keyvault/azure-keyvault-nspkg/azure/keyvault/__init__.py
  sdk/keyvault/azure-keyvault-nspkg/sdk_packaging.toml
  sdk/keyvault/azure-keyvault-nspkg/setup.cfg
  sdk/keyvault/azure-keyvault-nspkg/setup.py
  sdk/keyvault/azure-keyvault-secrets/MANIFEST.in
  sdk/keyvault/azure-keyvault-secrets/dev_requirements.txt
  sdk/keyvault/azure-keyvault-secrets/setup.py
  shared_requirements.txt
Labels: Client, KeyVault

#7187 [AutoPR batch/resource-manager] [Batch] Update documentation around app packages
  sdk/batch/azure-mgmt-batch/README.rst
  sdk/batch/azure-mgmt-batch/azure/__init__.py
  sdk/batch/azure-mgmt-batch/azure/mgmt/__init__.py
  sdk/batch/azure-mgmt-batch/azure/mgmt/batch/models/_paged_models.py
  sdk/batch/azure-mgmt-batch/azure/mgmt/batch/operations/_application_package_operations.py
  sdk/batch/azure-mgmt-batch/setup.py
Labels: RestPRMerged

#7202 [AutoPR datafactory/resource-manager] [DataFactory] Add a alternateKeyName property in dynamics sink
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Labels: RestPRMerged

#7205 [AutoPR apimanagement/resource-manager] Orphan property removed
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/authentication_settings_contract.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/authentication_settings_contract_py3.py
Labels: RestPRMerged

#7207 add cryptography dependency
  sdk/keyvault/azure-keyvault-keys/setup.py
Labels: Client, KeyVault

#7150 Eventhubs blobstorage merge to master
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/HISTORY.md
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/LICENSE
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/MANIFEST.in
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/README.md
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/__init__.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/azure/eventhub/extensions/checkpointstoreblobaio/blobstoragepm.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/dev_requirements.txt
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/examples/event_processor_blob_storage_example.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/sdk_packaging.toml
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.cfg
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/tests/test_storage_blob_partition_manager.py
  shared_requirements.txt
Labels: Client, Event Hubs

#7211 Increment Key Vault versions
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_version.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py
Labels: Client, KeyVault

#7176 increment azure-identity version
  sdk/identity/azure-identity/azure/identity/_version.py
Labels: Azure.Identity, Client

#7212 KeyVault: Removing JsonWeb prefix from enums
  sdk/keyvault/azure-keyvault-certificates/HISTORY.md
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/__init__.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/__init__.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/enums.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/models.py
  sdk/keyvault/azure-keyvault-keys/HISTORY.md
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/__init__.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/enums.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/models.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
Labels: Client, KeyVault

#7216 Eventhubs blobstorage docs update
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/README.md
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/dev_requirements.txt
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.py
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/tests/test_storage_blob_partition_manager.py
  sdk/eventhub/azure-eventhubs/README.md
  sdk/eventhub/tests.yml
  shared_requirements.txt
Labels: Client, Event Hubs

#7278 [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to add version preview/2019-07-01-preview
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/_iot_hub_client.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/__init__.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_iot_hub_client_enums.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/models/_models_py3.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_certificates_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_iot_hub_resource_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/_resource_provider_common_operations.py
Labels: RestPRMerged

#7281 [AutoPR appconfiguration/resource-manager] Updated 2019-02-01-preview api version to include the listKeyValue operation.
  sdk/appconfiguration/azure-mgmt-appconfiguration/README.rst
  sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/__init__.py
  sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/_models.py
  sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/models/_models_py3.py
  sdk/appconfiguration/azure-mgmt-appconfiguration/azure/mgmt/appconfiguration/operations/_configuration_stores_operations.py
  sdk/appconfiguration/azure-mgmt-appconfiguration/setup.py
Labels: RestPRMerged

#7283 [AutoPR automation/resource-manager] fix: Double word "the" in automation
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_compilation_job_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_configuration_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_node_configuration_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_node_operations.py
Labels: RestPRMerged

#7271 [AutoPR applicationinsights/resource-manager] Add purge API details.
  sdk/applicationinsights/azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/_components_operations.py
Labels: RestPRMerged

#7260 Fix error creating EnvironmentCredential with username/password
  sdk/identity/azure-identity/HISTORY.md
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py
  sdk/identity/azure-identity/azure/identity/credentials.py
  sdk/identity/azure-identity/tests/test_identity.py
Labels: Azure.Identity, Client

#7268 Correct return type for list_secrets, _versions
  sdk/keyvault/azure-keyvault-secrets/HISTORY.md
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/client.py
Labels: Client, KeyVault

#7329 [AutoPR sql/resource-manager] Adding SQL managedDatabases swagger for API v2018-06-01-preview
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/_sql_management_client.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_models_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_paged_models.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/_sql_management_client_enums.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/__init__.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_managed_database_restore_details_operations.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/_managed_databases_operations.py
Labels: RestPRMerged

#7311 [AutoPR containerregistry/resource-manager] [ACR] Scope map updates
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/__init__.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_container_registry_management_client_enums.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01_preview/models/_models_py3.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/__init__.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_container_registry_management_client_enums.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models_py3.py
Labels: RestPRMerged

#7086 More useful exceptions for Key Vault errors
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/exceptions.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/client.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/exceptions.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/exceptions.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/client.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/client.py
Labels: Client, KeyVault

#7224 Key Vault sample tidying
  sdk/keyvault/azure-keyvault-certificates/samples/backup_restore_operations.py
  sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations.py
  sdk/keyvault/azure-keyvault-keys/samples/backup_restore_operations_async.py
  sdk/keyvault/azure-keyvault-keys/samples/hello_world.py
  sdk/keyvault/azure-keyvault-keys/samples/hello_world_async.py
  sdk/keyvault/azure-keyvault-keys/samples/list_operations.py
  sdk/keyvault/azure-keyvault-keys/samples/list_operations_async.py
  sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations.py
  sdk/keyvault/azure-keyvault-keys/samples/recover_purge_operations_async.py
  sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations.py
  sdk/keyvault/azure-keyvault-secrets/samples/backup_restore_operations_async.py
  sdk/keyvault/azure-keyvault-secrets/samples/hello_world.py
  sdk/keyvault/azure-keyvault-secrets/samples/hello_world_async.py
  sdk/keyvault/azure-keyvault-secrets/samples/list_operations.py
  sdk/keyvault/azure-keyvault-secrets/samples/list_operations_async.py
  sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations.py
  sdk/keyvault/azure-keyvault-secrets/samples/recover_purge_operations_async.py
Labels: Client, KeyVault

#7331 Enable check enforcer.
  eng/CHECKENFORCER
Labels: EngSys

#7302 [AutoPR frontdoor/resource-manager] [AFD WAF] Add defaultState and defaultAction to managed rule set definitions
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_definition.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_definition_py3.py
Labels: RestPRMerged

#7251 [AutoPR reservations/resource-manager] [Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/__init__.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_azure_reservation_api_enums.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models_py3.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/_azure_reservation_api_operations.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/_reservation_operations.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/_reservation_order_operations.py
Labels: RestPRMerged

#7359 [AutoPR billing/resource-manager] chore: jsonfmt billing
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/__init__.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_management_client_enums.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/customer_policy.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/customer_policy_py3.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/invoice_section_with_create_sub_permission.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/invoice_section_with_create_sub_permission_paged.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/invoice_section_with_create_sub_permission_py3.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/billing_accounts_operations.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/billing_property_operations.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/policies_operations.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/products_operations.py
Labels: RestPRMerged

#7361 [AutoPR databoxedge/resource-manager] chore: jsonfmt databoxedge
  sdk/databoxedge/azure-mgmt-databoxedge/HISTORY.rst
  sdk/databoxedge/azure-mgmt-databoxedge/MANIFEST.in
  sdk/databoxedge/azure-mgmt-databoxedge/README.rst
  sdk/databoxedge/azure-mgmt-databoxedge/azure/__init__.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/__init__.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/__init__.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/_configuration.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/_data_box_edge_management_client.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/__init__.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_data_box_edge_management_client_enums.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_models.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_models_py3.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/models/_paged_models.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/__init__.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_alerts_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_bandwidth_schedules_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_devices_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_jobs_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_nodes_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_operations_status_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_orders_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_roles_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_shares_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_storage_account_credentials_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_triggers_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/operations/_users_operations.py
  sdk/databoxedge/azure-mgmt-databoxedge/azure/mgmt/databoxedge/version.py
  sdk/databoxedge/azure-mgmt-databoxedge/sdk_packaging.toml
  sdk/databoxedge/azure-mgmt-databoxedge/setup.cfg
  sdk/databoxedge/azure-mgmt-databoxedge/setup.py
Labels: RestPRMerged

#7322 [AutoPR datamigration/resource-manager] Fix eligibility typo
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Labels: RestPRMerged

#7324 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] LUIS Runtime V3.0
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_luis_runtime_client.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models_py3.py
Labels: RestPRMerged

#7299 [AutoPR azure-kusto/resource-manager] [Hub Generated] Review request for Microsoft.Kusto to add version stable/2019-09-07
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/__init__.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/_configuration.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/_kusto_management_client.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/__init__.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_kusto_management_client_enums.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_models.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_models_py3.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_paged_models.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/__init__.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/_clusters_operations.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/_data_connections_operations.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/_databases_operations.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/_operations.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/version.py
Labels: RestPRMerged

#7277 [AutoPR containerservice/resource-manager] fix getting agent pool available versions api path
  sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_06_01/operations/_agent_pools_operations.py
  sdk/containerservice/azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_08_01/operations/_agent_pools_operations.py
Labels: RestPRMerged

#7308 Update msrest and regenerate swagger.
  sdk/storage/azure-storage-blob/setup.py
  sdk/storage/azure-storage-blob/tests/recordings/test_container.test_list_blobs_with_include_metadata.yaml
  sdk/storage/azure-storage-blob/tests/recordings/test_container.test_list_blobs_with_include_multiple.yaml
  sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_list_blobs_with_include_metadata.yaml
  sdk/storage/azure-storage-blob/tests/recordings/test_container_async.test_list_blobs_with_include_multiple.yaml
  sdk/storage/azure-storage-blob/tests/test_container.py
  sdk/storage/azure-storage-blob/tests/test_container_async.py
  sdk/storage/azure-storage-file/azure/storage/file/_generated/models/_models.py
  sdk/storage/azure-storage-file/azure/storage/file/_generated/models/_models_py3.py
  sdk/storage/azure-storage-file/setup.py
  sdk/storage/azure-storage-queue/setup.py
  shared_requirements.txt
Labels: Storage

#7353 Remove create_config from READMEs
  sdk/keyvault/azure-keyvault-certificates/README.md
  sdk/keyvault/azure-keyvault-keys/README.md
  sdk/keyvault/azure-keyvault-secrets/README.md
Labels: Client, Docs, KeyVault

#7332 [AutoPR managednetwork/resource-manager] Update ManagedNetwork
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/__init__.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/_configuration.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/_managed_network_management_client.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/models/__init__.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_managed_network_management_client_enums.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_models.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_models_py3.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_paged_models.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/__init__.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_managed_network_groups_operations.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_managed_network_peering_policies_operations.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_managed_networks_operations.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_operations.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_scope_assignments_operations.py
  sdk/Microsoft.ManagedNetwork/v2019_06_01_pre/version.py
  sdk/managednetwork/azure-mgmt-managednetwork/HISTORY.rst
  sdk/managednetwork/azure-mgmt-managednetwork/MANIFEST.in
  sdk/managednetwork/azure-mgmt-managednetwork/README.rst
  sdk/managednetwork/azure-mgmt-managednetwork/azure/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/_configuration.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/_managed_network_management_client.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/models/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_managed_network_management_client_enums.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_models.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_models_py3.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/models/_paged_models.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_managed_network_groups_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_managed_network_peering_policies_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_managed_networks_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/operations/_scope_assignments_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/Microsoft.ManagedNetwork/v2019_06_01_pre/version.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/_configuration.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/_managed_network_management_client.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/models/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/models/_managed_network_management_client_enums.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/models/_models.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/models/_models_py3.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/models/_paged_models.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/operations/__init__.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/operations/_managed_network_groups_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/operations/_managed_network_peering_policies_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/operations/_managed_networks_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/operations/_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/operations/_scope_assignments_operations.py
  sdk/managednetwork/azure-mgmt-managednetwork/azure/mgmt/managednetwork/version.py
  sdk/managednetwork/azure-mgmt-managednetwork/sdk_packaging.toml
  sdk/managednetwork/azure-mgmt-managednetwork/setup.cfg
  sdk/managednetwork/azure-mgmt-managednetwork/setup.py
Labels: RestPRMerged

#7366 [AutoPR vmwarevirtustream/resource-manager] VMware by Virtustream API 2019-08-09-preview
  sdk/compute/azure-mgmt-vmwarevirtustream/HISTORY.rst
  sdk/compute/azure-mgmt-vmwarevirtustream/MANIFEST.in
  sdk/compute/azure-mgmt-vmwarevirtustream/README.rst
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/__init__.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/__init__.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/__init__.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/_azure_vmware_solutionby_virtustream_api.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/_configuration.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/models/__init__.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/models/_azure_vmware_solutionby_virtustream_api_enums.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/models/_models.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/models/_models_py3.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/models/_paged_models.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/operations/__init__.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/operations/_clusters_operations.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/operations/_operations.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/operations/_private_clouds_operations.py
  sdk/compute/azure-mgmt-vmwarevirtustream/azure/mgmt/vmwarevirtustream/version.py
  sdk/compute/azure-mgmt-vmwarevirtustream/sdk_packaging.toml
  sdk/compute/azure-mgmt-vmwarevirtustream/setup.cfg
  sdk/compute/azure-mgmt-vmwarevirtustream/setup.py
Labels: RestPRMerged

#7351 [AutoPR machinelearningservices/resource-manager] Restoring quota patch overwritten during 2019-06-01 version update
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_usages_operations.py
Labels: RestPRMerged

#7383 [AutoPR datamigration/resource-manager] Add aad domain name for windows login migration support
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Labels: RestPRMerged

#7266 [AutoPR] resources/resource-manager
  sdk/resources/azure-mgmt-resource/HISTORY.rst
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/models/_models.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/models/_models_py3.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_08_01/operations/_deployments_operations.py
Labels: ServicePR

#7380 use xdist in live tests (optional) and in nightly tests (default)
  eng/pipelines/templates/jobs/archetype-sdk-tests.yml
  eng/tox/tox.ini
  scripts/devops_tasks/setup_execute_tests.py
Labels: EngSys

#7376 [AutoPR security/resource-manager] Add ProtectionMode to Microsoft.Security applicationWhitelistings
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models_py3.py
Labels: RestPRMerged

#7334 [AutoPR datafactory/resource-manager] [DataFactory] - Add CosmosDbSqlApi dataset
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/_data_factory_management_client.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_paged_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_data_flow_debug_session_operations.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_data_flows_operations.py
Labels: RestPRMerged

#7369 [AutoPR cosmos-db/resource-manager] Add Sql StoredProcedures, UDFs and Triggers for CosmosDB resources
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/_cosmos_db.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/__init__.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_cosmos_db_enums.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_models.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_models_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/_paged_models.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/__init__.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_cassandra_resources_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_collection_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_collection_partition_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_collection_partition_region_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_collection_region_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_database_account_region_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_database_accounts_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_database_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_gremlin_resources_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_mongo_db_resources_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_partition_key_range_id_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_partition_key_range_id_region_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_percentile_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_percentile_source_target_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_percentile_target_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_sql_resources_operations.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/operations/_table_resources_operations.py
Labels: RestPRMerged

#7394 [AutoPR securityinsights/resource-manager] Added Data Connectors check requirements to security insights.
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/__init__.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aad_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aad_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aatp_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aatp_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/action_request.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/action_request_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/action_response.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/action_response_paged.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/action_response_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/asc_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/asc_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aws_cloud_trail_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aws_cloud_trail_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/bookmark_relation.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/bookmark_relation_paged.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/bookmark_relation_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/case_relation.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/case_relation_paged.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/case_relation_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connector_requirements_state.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connector_requirements_state_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connectors_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connectors_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mcas_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mcas_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mdatp_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mdatp_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/office_data_connector_requirements_check.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/office_data_connector_requirements_check_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/relation_base.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/relation_base_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/relation_node.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/relation_node_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/relations_model_input.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/relations_model_input_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/security_insights_enums.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/ti_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/ti_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/__init__.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/actions_operations.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/alert_rules_operations.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/bookmark_relations_operations.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/case_relations_operations.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/data_connector_requirements_operations.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/security_insights.py
Labels: RestPRMerged

#7432 [AutoPR datafactory/resource-manager] [Data Factory] Remove unnecessary additional property for data flow entity
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Labels: RestPRMerged

#7424 [AutoPR azure-kusto/resource-manager] [Hub Generated] Review request for Microsoft.Kusto to add version stable/2019-09-07
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/_kusto_management_client.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/__init__.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_kusto_management_client_enums.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_models.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_models_py3.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/models/_paged_models.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/__init__.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/_attached_database_configurations_operations.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/_clusters_operations.py
  sdk/azure-mgmt-kusto/azure/mgmt/kusto/operations/_databases_operations.py
Labels: RestPRMerged

#7452 Patch os.environ in Identity mock tests
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/identity/azure-identity/tests/test_identity_async.py
Labels: Azure.Identity, Client

#6473 Fix problem with message label not being set.
  sdk/servicebus/azure-servicebus/azure/servicebus/common/message.py
Labels: Client, Service Bus, customer-reported

#6923 [AutoPR] peering/resource-manager
  sdk/peering/azure-mgmt-peering/HISTORY.rst
  sdk/peering/azure-mgmt-peering/MANIFEST.in
  sdk/peering/azure-mgmt-peering/README.rst
  sdk/peering/azure-mgmt-peering/azure/__init__.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/__init__.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/__init__.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/_configuration.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/_peering_management_client.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/models/__init__.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/models/_models.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/models/_models_py3.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/models/_paged_models.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/models/_peering_management_client_enums.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/__init__.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_legacy_peerings_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peer_asns_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peering_locations_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peering_management_client_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peering_service_locations_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peering_service_prefixes_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peering_service_providers_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peering_services_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_peerings_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/operations/_prefixes_operations.py
  sdk/peering/azure-mgmt-peering/azure/mgmt/peering/version.py
  sdk/peering/azure-mgmt-peering/sdk_packaging.toml
  sdk/peering/azure-mgmt-peering/setup.cfg
  sdk/peering/azure-mgmt-peering/setup.py
Labels: ServicePR

#7445 [AutoPR storage/resource-manager] [SRP] Add new storage account property largeFileSharesState
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_storage_management_client_enums.py
Labels: RestPRMerged

#7422 [AutoPR security/resource-manager] Jit api add justification
  sdk/security/azure-mgmt-security/azure/mgmt/security/_security_center.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_models_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_paged_models.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/_security_center_enums.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_jit_network_access_policies_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/_sub_assessments_operations.py
Labels: RestPRMerged

#7448 [AutoPR securityinsights/resource-manager] Reverting requirements check from Sentinel
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/__init__.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aad_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aad_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aatp_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aatp_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/asc_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/asc_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aws_cloud_trail_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/aws_cloud_trail_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connector_requirements_state.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connector_requirements_state_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connectors_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/data_connectors_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mcas_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mcas_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mdatp_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/mdatp_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/office_data_connector_requirements_check.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/office_data_connector_requirements_check_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/security_insights_enums.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/ti_check_requirements.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/ti_check_requirements_py3.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/__init__.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/data_connector_requirements_operations.py
  sdk/azure-mgmt-securityinsight/azure/mgmt/securityinsight/security_insights.py
Labels: RestPRMerged

#7436 [AutoPR databox/resource-manager] Databox stable/2019-09-01 API Version
  sdk/azure-mgmt-databox/azure/mgmt/databox/__init__.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/_configuration.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/_data_box_management_client.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/models/__init__.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/models/_data_box_management_client_enums.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/models/_models.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/models/_models_py3.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/models/_paged_models.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/operations/__init__.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/operations/_jobs_operations.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/operations/_operations.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/operations/_service_operations.py
  sdk/azure-mgmt-databox/azure/mgmt/databox/version.py
Labels: RestPRMerged

#7464 [AutoPR datashare/resource-manager] SQL changes
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/__init__.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_data_share_management_client_enums.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_models.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_models_py3.py
Labels: RestPRMerged

#7444 [AutoPR datafactory/resource-manager] [Data Factory] Add data flow compute property in IR.
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_data_flow_debug_session_operations.py
Labels: RestPRMerged

#7153 Eventhub tracing
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/dev_requirements.txt
  sdk/eventhub/azure-eventhubs-checkpointstoreblob-aio/setup.py
  sdk/eventhub/azure-eventhubs/HISTORY.md
  sdk/eventhub/azure-eventhubs/azure/eventhub/__init__.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/eventprocessor/event_processor.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/common.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
  sdk/eventhub/azure-eventhubs/dev_requirements.txt
  sdk/eventhub/azure-eventhubs/setup.py
  shared_requirements.txt
Labels: Client, Event Hubs

#7431 [EventHubs] Eventhubs runtime metric
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/common.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/examples/async_examples/recv_track_last_enqueued_event_info_async.py
  sdk/eventhub/azure-eventhubs/examples/recv_track_last_enqueued_event_info.py
  sdk/eventhub/azure-eventhubs/tests/asynctests/test_receive_async.py
  sdk/eventhub/azure-eventhubs/tests/test_receive.py
Labels: Event Hubs

#7482 [AutoPR datashare/resource-manager] fixing datashare readme - python section
  sdk/datashare/azure-mgmt-datashare/HISTORY.rst
  sdk/datashare/azure-mgmt-datashare/MANIFEST.in
  sdk/datashare/azure-mgmt-datashare/README.rst
  sdk/datashare/azure-mgmt-datashare/azure/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/_configuration.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/_data_share_management_client.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_data_share_management_client_enums.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_models.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_models_py3.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_paged_models.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_accounts_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_consumer_invitations_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_consumer_source_data_sets_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_data_set_mappings_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_data_sets_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_invitations_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_provider_share_subscriptions_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_share_subscriptions_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_shares_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_synchronization_settings_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_triggers_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/version.py
  sdk/datashare/azure-mgmt-datashare/sdk_packaging.toml
  sdk/datashare/azure-mgmt-datashare/setup.cfg
  sdk/datashare/azure-mgmt-datashare/setup.py
Labels: RestPRInProgress

#7458 [AutoPR billing/resource-manager] Added new properties in Invoicing APIs
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/__init__.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_management_client_enums.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/payment_properties.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/payment_properties_py3.py
Labels: RestPRMerged

#7486 [AutoPR datashare/resource-manager] chore: jsonfmt datashare
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/_configuration.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/_data_share_management_client.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_data_share_management_client_enums.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_models.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_models_py3.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/models/_paged_models.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/__init__.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_accounts_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_consumer_invitations_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_consumer_source_data_sets_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_data_set_mappings_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_data_sets_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_invitations_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_provider_share_subscriptions_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_share_subscriptions_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_shares_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_synchronization_settings_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/operations/_triggers_operations.py
  sdk/datashare/azure-mgmt-datashare/azure/mgmt/datashare/version.py
Labels: RestPRMerged

#7384 Update readme CLI snippets
  sdk/keyvault/azure-keyvault-certificates/README.md
  sdk/keyvault/azure-keyvault-keys/README.md
  sdk/keyvault/azure-keyvault-secrets/README.md
Labels: Client, KeyVault

#7498 Key Vault: renamed c_rl_sign enum to crl_sign
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/client.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/client.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/enums.py
Labels: Client, KeyVault

#7379 Implement authorization code flow
  sdk/identity/azure-identity/HISTORY.md
  sdk/identity/azure-identity/azure/identity/__init__.py
  sdk/identity/azure-identity/azure/identity/_constants.py
  sdk/identity/azure-identity/azure/identity/_credentials/__init__.py
  sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
  sdk/identity/azure-identity/azure/identity/_internal/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/aad_client.py
  sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
  sdk/identity/azure-identity/azure/identity/aio/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
  sdk/identity/azure-identity/azure/identity/aio/_internal/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/_internal/aad_client.py
  sdk/identity/azure-identity/azure/identity/aio/_internal/msal_transport_adapter.py
  sdk/identity/azure-identity/dev_requirements.txt
  sdk/identity/azure-identity/tests/test_aad_client.py
  sdk/identity/azure-identity/tests/test_aad_client_async.py
  sdk/identity/azure-identity/tests/test_auth_code.py
  sdk/identity/azure-identity/tests/test_auth_code_async.py
Labels: Azure.Identity, Client
