Repository Azure/azure-sdk-for-python, pull requests merged in 2019-07, with the labels that each got.

#5715 [AutoPR healthcareapis/resource-manager] [Hub Generated] Review request for Microsoft.HealthcareApis to add version preview/2018-08-20-preview
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/healthcare_apis_management_client.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/move_resources_parameters.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/move_resources_parameters_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_authentication_configuration_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_authentication_configuration_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cors_configuration_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cors_configuration_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cosmos_db_configuration_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cosmos_db_configuration_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_properties.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_properties_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/move_resources_status_operations.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/services_operations.py
Labels: RestPRMerged

#6179 [AutoPR reservations/resource-manager] chore: jsonfmt reservations
  sdk/reservations/azure-mgmt-reservations/README.rst
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/__init__.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models_py3.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/_reservation_operations.py
  sdk/reservations/azure-mgmt-reservations/setup.py
Labels: RestPRMerged

#6047 [AutoPR security/resource-manager] Changes to the JIT API for Firewall Support
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/jit_network_access_policy_virtual_machine.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/jit_network_access_policy_virtual_machine_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/jit_network_access_request_port.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/jit_network_access_request_port_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/server_vulnerability_assessment.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/server_vulnerability_assessment_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/server_vulnerability_assessments_list.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/server_vulnerability_assessments_list_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/server_vulnerability_assessment_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/security_center.py
Labels: RestPRMerged

#6176 Update MSAL dependency
  sdk/identity/azure-identity/azure/identity/_authn_client.py
  sdk/identity/azure-identity/setup.py
  shared_requirements.txt
Labels: Azure.Identity, Client

#6198 Fix storage sample readme links
  sdk/storage/azure-storage-blob/README.md
  sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
  sdk/storage/azure-storage-queue/README.md
Labels: Client, Storage

#6209 [AutoPR managedservices/resource-manager] API version is a client constant
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/operations.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_assignments_operations.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_definitions_operations.py
Labels: RestPRMerged

#5885 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Update LUIS Runtime swagger to an auto generated version
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_luis_runtime_client.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/api_error.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/api_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_child_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_child_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_entity_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_entity_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_resolution.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_resolution_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_score.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_score_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/intent_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/intent_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/sentiment.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/sentiment_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/_prediction_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/prediction_operations.py
Labels: RestPRMerged

#6221 Storage file readme link fixes
  sdk/storage/azure-storage-file/README.md
Labels: Client, Storage

#6196 add abstract span that wraps the implementation specific spans.
  sdk/core/azure-core/azure/core/trace/abstract_span.py
Labels: Azure.Core, Client

#5768 [AutoPR] sqlvirtualmachine/resource-manager
  sdk/sql/azure-mgmt-sqlvirtualmachine/HISTORY.rst
  sdk/sql/azure-mgmt-sqlvirtualmachine/README.rst
  sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/models/__init__.py
  sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/models/sql_virtual_machine.py
  sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/models/sql_virtual_machine_management_client_enums.py
  sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/models/sql_virtual_machine_py3.py
  sdk/sql/azure-mgmt-sqlvirtualmachine/azure/mgmt/sqlvirtualmachine/version.py
  sdk/sql/azure-mgmt-sqlvirtualmachine/setup.py
Labels: ReadyforRelease, ServicePR

#6214 Apply build tag to nightlies
  eng/pipelines/templates/jobs/archetype-sdk-client.yml
Labels: EngSys

#6149 [AutoPR compute/resource-manager] Dev/ccelik/dedicated host swagger
  sdk/compute/azure-mgmt-compute/README.rst
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/_compute_management_client.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/_compute_management_client.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_paged_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/__init__.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_dedicated_host_groups_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_dedicated_hosts_operations.py
  sdk/compute/azure-mgmt-compute/setup.py
Labels: RestPRMerged

#6213 Update release histories
  sdk/identity/azure-identity/HISTORY.md
  sdk/keyvault/azure-keyvault-keys/HISTORY.md
  sdk/keyvault/azure-keyvault-secrets/HISTORY.md
Labels: Azure.Identity, Client, KeyVault

#5675 [AutoPR] netapp/resource-manager
  sdk/netapp/azure-mgmt-netapp/HISTORY.rst
  sdk/netapp/azure-mgmt-netapp/README.rst
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/azure_net_app_files_management_client.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/azure_net_app_files_management_client_enums.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_py3.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/resource_name_availability_request.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/resource_name_availability_request_py3.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_py3.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/mount_targets_operations.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/operations.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/pools_operations.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/snapshots_operations.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/operations/volumes_operations.py
  sdk/netapp/azure-mgmt-netapp/azure/mgmt/netapp/version.py
  sdk/netapp/azure-mgmt-netapp/setup.py
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_account.test_create_delete_account.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_account.test_get_account_by_name.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_account.test_list_accounts.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_account.test_patch_account.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_mounttarget.test_list_mount_target.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_pool.test_create_delete_pool.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_pool.test_get_pool_by_name.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_pool.test_list_pools.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_pool.test_patch_pool.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_pool.test_update_pool.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_snapshot.test_create_delete_snapshot.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_snapshot.test_get_snapshot_by_name.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_snapshot.test_list_snapshots.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_volume.test_create_delete_list_volume.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_volume.test_get_volume_by_name.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_volume.test_list_volumes.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_volume.test_patch_volume.yaml
  sdk/netapp/azure-mgmt-netapp/tests/recordings/test_volume.test_update_volume.yaml
  sdk/netapp/azure-mgmt-netapp/tests/setup.py
  sdk/netapp/azure-mgmt-netapp/tests/test_pool.py
  sdk/netapp/azure-mgmt-netapp/tests/test_snapshot.py
  sdk/netapp/azure-mgmt-netapp/tests/test_volume.py
Labels: ServicePR

#5751 [AutoPR] managedservices/resource-manager
  sdk/managedservices/azure-mgmt-managedservices/HISTORY.rst
  sdk/managedservices/azure-mgmt-managedservices/README.rst
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/managed_services_client.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_py3.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties_py3.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties_py3.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/operations.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_assignments_operations.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_definitions_operations.py
  sdk/managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/version.py
  sdk/managedservices/azure-mgmt-managedservices/setup.py
  sdk/managedservices/azure-mgmt-managedservices/tests/recordings/test_mgmt_managedservices.test_managedservices_crud.yaml
  sdk/managedservices/azure-mgmt-managedservices/tests/test_mgmt_managedservices.py
Labels: ServicePR

#6118 [AutoPR apimanagement/resource-manager] apim ciphers custom settings description
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_base_properties_py3.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_resource_py3.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_update_parameters_py3.py
Labels: RestPRMerged

#6142 [AutoPR monitor/resource-manager] BUG fix: Fixing type of MetricValue.Count to be double instead of the incorrect int64 it had before
  sdk/monitor/azure-mgmt-monitor/README.rst
  sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2015_04_01/operations/_activity_logs_operations.py
  sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2018_01_01/models/_models.py
  sdk/monitor/azure-mgmt-monitor/azure/mgmt/monitor/v2018_01_01/models/_models_py3.py
  sdk/monitor/azure-mgmt-monitor/setup.py
Labels: RestPRMerged

#6220 [azure-storage] Added release notes for blob, file and queue
  sdk/storage/azure-storage-blob/HISTORY.md
  sdk/storage/azure-storage-file/HISTORY.md
  sdk/storage/azure-storage-queue/HISTORY.md
Labels: Storage

#6192 [AutoPR mediaservices/resource-manager] Restore default tag to stable version of the API - package-2018-07
  sdk/media/azure-mgmt-media/azure/mgmt/media/azure_media_services.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/__init__.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/azure_media_services_enums.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event_input_track_selection.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event_input_track_selection_py3.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event_output_transcription_track.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event_output_transcription_track_py3.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event_py3.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event_transcription.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/models/live_event_transcription_py3.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/operations/jobs_operations.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/operations/live_events_operations.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/operations/live_outputs_operations.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/operations/streaming_endpoints_operations.py
  sdk/media/azure-mgmt-media/azure/mgmt/media/version.py
Labels: RestPRMerged

#6223 add context management for traces
  sdk/core/azure-core/azure/core/tracing/__init__.py
  sdk/core/azure-core/azure/core/tracing/abstract_span.py
  sdk/core/azure-core/azure/core/tracing/context.py
  sdk/core/azure-core/tests/test_trace_context.py
Labels: Azure.Core, Client

#6273 Update Key Vault readmes with reference doc links
  sdk/keyvault/azure-keyvault-keys/README.md
  sdk/keyvault/azure-keyvault-secrets/README.md
Labels: Client, KeyVault

#6294 Update azure-identity readme
  sdk/identity/azure-identity/README.md
Labels: Azure.Identity, Client, Docs

#6284 [AutoPR datashare/resource-manager] Add RP Data Share to specification folder [Public Preview]
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/__init__.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/_configuration.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/_data_share_management_client.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/__init__.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_data_share_management_client_enums.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_models.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_models_py3.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/models/_paged_models.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/__init__.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_accounts_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_consumer_invitations_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_consumer_source_data_sets_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_data_set_mappings_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_data_sets_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_invitations_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_provider_share_subscriptions_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_share_subscriptions_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_shares_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_synchronization_settings_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/operations/_triggers_operations.py
  sdk/azure-mgmt-DataShare/azure/mgmt/DataShare/version.py
Labels: RestPRMerged

#6300 [AutoPR containerregistry/resource-manager] set a default api version
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/_container_registry_management_client.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/models.py
Labels: RestPRMerged

#6301 [AutoPR] containerregistry/resource-manager
  sdk/containerregistry/azure-mgmt-containerregistry/HISTORY.rst
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/_container_registry_management_client.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/version.py
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_classic_registry.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_managed_registry.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_replication.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_webhook.yaml
Labels: ServicePR

#6096 [AutoPR datamigration/resource-manager] Adding objects necessary for mapping Oracle schemas and tables to PostgreSQL databases and tables
  sdk/datamigration/azure-mgmt-datamigration/README.rst
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/__init__.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
  sdk/datamigration/azure-mgmt-datamigration/setup.py
Labels: RestPRMerged

#6114 [AutoPR portal/resource-manager] [Hub Generated] Review request for Microsoft.Portal to add version preview/2015-08-01-preview
  sdk/azure-mgmt/portal/operations/dashboards_operations.py
  sdk/azure-mgmt/portal/operations/operations.py
  sdk/azure-mgmt/portal/portal_client.py
  sdk/azure-mgmt/portal/version.py
Labels: RestPRMerged

#6307 update CODEOWNERS links to point to sync documentation
  .github/CODEOWNERS
Labels: EngSys

#6264 add opencensus implementation
  sdk/core/azure-core/azure/core/tracing/abstract_span.py
  sdk/core/azure-core/azure/core/tracing/ext/__init__.py
  sdk/core/azure-core/azure/core/tracing/ext/opencensus_span.py
  sdk/core/azure-core/dev_requirements.txt
  sdk/core/azure-core/tests/test_tracing_context.py
  sdk/core/azure-core/tests/test_tracing_implementations.py
Labels: Azure.Core, Client

#6289 [AutoPR security/resource-manager] Improving Security Center pricing API documentation
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_aggregated_alert.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_aggregated_alert_paged.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_aggregated_alert_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_aggregated_recommendation.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_aggregated_recommendation_paged.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_aggregated_recommendation_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_device.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_device_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_devices_list.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_devices_list_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_alert.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_alert_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_alerts_list.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_alerts_list_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendation.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendation_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendations_list.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendations_list_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_analytics_model.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_analytics_model_list.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_analytics_model_list_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_analytics_model_properties_devices_metrics_item.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_analytics_model_properties_devices_metrics_item_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_analytics_model_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_model.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_model_paged.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_solution_model_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tseverity_metrics.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tseverity_metrics_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/pricing.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/pricing_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/recommendation_configuration_properties.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/recommendation_configuration_properties_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/security_center_enums.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/tags_resource.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/tags_resource_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/update_iot_security_solution_data.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/update_iot_security_solution_data_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/user_defined_resources_properties.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/user_defined_resources_properties_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_aggregated_alert_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_aggregated_alerts_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_recommendation_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_recommendations_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_resource_group_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/iot_security_solution_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/pricings_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/security_center.py
Labels: RestPRMerged

#6348 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] chore: jsonfmt cognitiveservices
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/_luis_runtime_client.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/_models_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/api_error.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/api_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_child_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_child_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_entity_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/composite_entity_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_resolution.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_resolution_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_score.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/entity_with_score_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/intent_model.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/intent_model_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/sentiment.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/sentiment_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/_prediction_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/operations/prediction_operations.py
Labels: RestPRMerged

#6266 [AutoPR sql/resource-manager] Add resource group based LTR API
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/long_term_retention_backups_operations.py
Labels: RestPRMerged

#6304 [AutoPR subscription/resource-manager] Enable sub/nitegupt
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/__init__.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/enabled_subscription_id.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/enabled_subscription_id_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/subscriptions_operations.py
Labels: RestPRMerged

#6343 [AutoPR devops/resource-manager] Adding Swagger for Microsoft.DevOps/Pipelines resource
  sdk/azure-mgmt/devops/__init__.py
  sdk/azure-mgmt/devops/_configuration.py
  sdk/azure-mgmt/devops/_dev_ops_client.py
  sdk/azure-mgmt/devops/models/__init__.py
  sdk/azure-mgmt/devops/models/_dev_ops_client_enums.py
  sdk/azure-mgmt/devops/models/_models.py
  sdk/azure-mgmt/devops/models/_models_py3.py
  sdk/azure-mgmt/devops/models/_paged_models.py
  sdk/azure-mgmt/devops/operations/__init__.py
  sdk/azure-mgmt/devops/operations/_operations.py
  sdk/azure-mgmt/devops/operations/_pipeline_template_definitions_operations.py
  sdk/azure-mgmt/devops/operations/_pipelines_operations.py
  sdk/azure-mgmt/devops/version.py
  sdk/devops/azure-mgmt-devops/HISTORY.rst
  sdk/devops/azure-mgmt-devops/MANIFEST.in
  sdk/devops/azure-mgmt-devops/README.rst
  sdk/devops/azure-mgmt-devops/azure/__init__.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/__init__.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/__init__.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/_configuration.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/_dev_ops_client.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/models/__init__.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/models/_dev_ops_client_enums.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/models/_models.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/models/_models_py3.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/models/_paged_models.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/operations/__init__.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/operations/_operations.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/operations/_pipeline_template_definitions_operations.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/operations/_pipelines_operations.py
  sdk/devops/azure-mgmt-devops/azure/mgmt/devops/version.py
  sdk/devops/azure-mgmt-devops/sdk_packaging.toml
  sdk/devops/azure-mgmt-devops/setup.cfg
  sdk/devops/azure-mgmt-devops/setup.py
Labels: RestPRMerged

#6231 [AutoPR cosmos-db/resource-manager] Adding cassandra connector properties for cosmos db C* account -
  sdk/cosmos/azure-mgmt-cosmosdb/README.rst
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/__init__.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/cosmos_db_enums.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/database_account.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/database_account_create_update_parameters.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/database_account_create_update_parameters_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/database_account_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/setup.py
Labels: RestPRMerged

#6355 Avoid surprising aiohttp with unexpected kwargs
  sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py
Labels: Azure.Core, Client

#6244 Add challenge authentication to azure-keyvault-keys
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_internal.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_challenge_auth_policy.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/challenge_auth_policy.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge_cache.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_internal.py
  sdk/keyvault/azure-keyvault-keys/tests/helpers.py
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_list.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_list_deleted_keys.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_list_versions.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_purge.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_recover.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_list.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_list_deleted_keys.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_list_versions.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_purge.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_recover.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_key_list_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_keys_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_keys_recover.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_key_list_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_keys_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_keys_recover.yaml
  sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py
  sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py
Labels: Client, KeyVault

#6299 Add decorator
  sdk/core/azure-core/azure/core/settings.py
  sdk/core/azure-core/azure/core/tracing/__init__.py
  sdk/core/azure-core/azure/core/tracing/abstract_span.py
  sdk/core/azure-core/azure/core/tracing/common.py
  sdk/core/azure-core/azure/core/tracing/context.py
  sdk/core/azure-core/azure/core/tracing/decorator.py
  sdk/core/azure-core/azure/core/tracing/decorator_async.py
  sdk/core/azure-core/azure/core/tracing/ext/opencensus_span.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_tracing_decorator_async.py
  sdk/core/azure-core/tests/test_settings.py
  sdk/core/azure-core/tests/test_tracing_context.py
  sdk/core/azure-core/tests/test_tracing_decorator.py
  sdk/core/azure-core/tests/test_tracing_implementations.py
  sdk/core/azure-core/tests/tracing_common.py
Labels: Azure.Core, Client, Mgmt

#6339 [AutoPR compute/resource-manager] Dev/ccelik/dedicatedhostswagger
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_dedicated_hosts_operations.py
Labels: RestPRMerged

#6233 [AutoPR storage/resource-manager] [Bug fix] Remove read-only constraint for management policy
  sdk/storage/azure-mgmt-storage/README.rst
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/_storage_management_client.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/models.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py
  sdk/storage/azure-mgmt-storage/setup.py
Labels: RestPRMerged

#6358 Add credential wrapping MSAL ConfidentialClientApplication
  sdk/identity/azure-identity/azure/identity/_internal/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py
  sdk/identity/azure-identity/azure/identity/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/credentials.py
  sdk/identity/azure-identity/azure/identity/credentials.py
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/identity/azure-identity/tests/test_identity_async.py
  sdk/identity/azure-identity/tests/test_live.py
Labels: Azure.Identity, Client

#6379 Add policy
  sdk/core/azure-core/azure/core/pipeline/policies/distributed_tracing.py
  sdk/core/azure-core/azure/core/tracing/abstract_span.py
  sdk/core/azure-core/azure/core/tracing/ext/opencensus_span.py
  sdk/core/azure-core/tests/test_tracing_implementations.py
  sdk/core/azure-core/tests/test_tracing_policy.py
  sdk/core/azure-core/tests/tracing_common.py
Labels: Azure.Core, Client

#6389 [AutoPR machinelearningservices/resource-manager] [READY TO MERGE] Add missing usages api optional parameter
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_usages_operations.py
Labels: RestPRMerged

#6399 Fix implementation bug
  sdk/core/azure-core/azure/core/tracing/decorator.py
  sdk/core/azure-core/azure/core/tracing/decorator_async.py
  sdk/core/azure-core/azure/core/tracing/ext/opencensus_span.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_tracing_decorator_async.py
  sdk/core/azure-core/tests/test_tracing_decorator.py
Labels: Azure.Core, Client

#6410 Update create_key snippets
  sdk/keyvault/azure-keyvault-keys/README.md
Labels: Client, Docs, KeyVault

#6366 [AutoPR cognitiveservices/data-plane/ContentModerator] fix: cognitive services create example
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/README.rst
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/_content_moderator_client.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/_models_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/models/_paged_models.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/_image_moderation_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/_list_management_image_lists_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/_list_management_image_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/_list_management_term_lists_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/_list_management_term_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/_reviews_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/azure/cognitiveservices/vision/contentmoderator/operations/_text_moderation_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-contentmoderator/setup.py
Labels: RestPRMerged

#6371 [AutoPR windowsiot/resource-manager] add winiotsvcs stable api
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/__init__.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/_configuration.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/_device_services.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/models/__init__.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/models/_device_services_enums.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/models/_models.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/models/_models_py3.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/models/_paged_models.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/operations/__init__.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/operations/_operations.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/operations/_services_operations.py
  sdk/azure-mgmt-windowsiot/azure/mgmt/windowsiot/version.py
Labels: RestPRMerged

#6372 Some azure-core features
  sdk/core/azure-core/README.md
  sdk/core/azure-core/azure/core/configuration.py
  sdk/core/azure-core/azure/core/exceptions.py
  sdk/core/azure-core/azure/core/pipeline/base.py
  sdk/core/azure-core/azure/core/pipeline/base_async.py
  sdk/core/azure-core/azure/core/pipeline/policies/base.py
  sdk/core/azure-core/azure/core/pipeline/policies/universal.py
  sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_asyncio.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_basic.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_trio.py
  sdk/core/azure-core/azure/core/pipeline_client.py
  sdk/core/azure-core/azure/core/pipeline_client_async.py
  sdk/core/azure-core/examples/test_example_async.py
  sdk/core/azure-core/examples/test_example_config.py
  sdk/core/azure-core/examples/test_example_sync.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_pipeline.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_universal_http.py
  sdk/core/azure-core/tests/test_exceptions.py
  sdk/core/azure-core/tests/test_pipeline.py
  sdk/identity/azure-identity/azure/identity/_authn_client.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py
  sdk/identity/azure-identity/azure/identity/aio/_authn_client.py
  sdk/identity/azure-identity/sdk_packaging.toml
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
  sdk/keyvault/azure-keyvault-keys/sdk_packaging.toml
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
  sdk/keyvault/azure-keyvault-secrets/sdk_packaging.toml
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared/utils.py
  sdk/storage/azure-storage-blob/tests/test_blob_access_conditions.py
  sdk/storage/azure-storage-blob/tests/test_blob_client.py
  sdk/storage/azure-storage-file/azure/storage/file/_shared/utils.py
  sdk/storage/azure-storage-file/tests/test_file_client.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/utils.py
  sdk/storage/azure-storage-queue/tests/test_queue_client.py
Labels: Azure.Core, Client

#6417 Policy bug
  sdk/core/azure-core/azure/core/pipeline/policies/distributed_tracing.py
  sdk/core/azure-core/tests/test_tracing_policy.py
Labels: Azure.Core, Client

#6381 added decorators to keyvault-keys
  sdk/core/azure-core/tests/test_tracing_decorator.py
  sdk/core/azure-core/tests/test_tracing_implementations.py
  sdk/core/azure-core/tests/tracing_common.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
Labels: Client, KeyVault

#6373 [AutoPR portal/resource-manager] [Hub Generated] Review request for Microsoft.Portal to add version preview/2019-01-01-preview
  sdk/azure-mgmt/portal/operations/dashboards_operations.py
  sdk/azure-mgmt/portal/operations/operations.py
  sdk/azure-mgmt/portal/portal_client.py
Labels: RestPRMerged

#6376 Remove default development settings
  .gitignore
  .vscode/settings.json
  scripts/devops_tasks/setup_execute_tests.py
  setup.cfg
Labels: Client

#6390 Use tracing policy
  sdk/core/azure-core/azure/core/pipeline_client.py
  sdk/core/azure-core/azure/core/pipeline_client_async.py
Labels: Azure.Core, Client

#6450 [AutoPR apimanagement/resource-manager] [Hub Generated] Review request for Microsoft.ApiManagement to add version stable/2019-01-01
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_diagnostic_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_attachment_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_comment_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_issue_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_operation_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_operation_policy_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_product_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_release_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/api_revision_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/backend_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/group_user_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/notification_recipient_user_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_api_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_group_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_policy_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/product_subscriptions_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/tag_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_confirmation_password_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_group_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_identities_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_operations.py
  sdk/apimanagement/azure-mgmt-apimanagement/azure/mgmt/apimanagement/operations/user_subscription_operations.py
Labels: RestPRMerged

#6460 [AutoPR compute/resource-manager] removing non-ascii character
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Labels: RestPRMerged

#6456 Trace core lro
  sdk/core/azure-core/azure/core/polling/poller.py
Labels: Azure.Core, Client

#6455 Trace identity
  sdk/identity/azure-identity/azure/identity/_authn_client.py
  sdk/identity/azure-identity/azure/identity/aio/_authn_client.py
Labels: Azure.Identity, Client

#6457 [AutoPR cognitiveservices/data-plane/QnAMaker] Updated QnAMaker Runtime API headers descriptions
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/feedback_record_dto.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/feedback_record_dto_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/feedback_records_dto.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/feedback_records_dto_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/qn_amaker_runtime_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/qn_asearch_result.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/qn_asearch_result_context.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/qn_asearch_result_context_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/qn_asearch_result_list.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/qn_asearch_result_list_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/qn_asearch_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/query_context_dto.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/query_context_dto_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/query_dto.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/query_dto_context.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/query_dto_context_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/query_dto_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/operations/runtime_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/qn_amaker_runtime_client.py
Labels: RestPRMerged

#6463 [AutoPR hanaonazure/resource-manager] Added Keyvault and MSI parameters to create SAP Monitor
  sdk/hanaonazure/azure-mgmt-hanaonazure/README.rst
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/setup.py
Labels: RestPRMerged

#6453 add policy and decorators for keyvault.secrets
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_client.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_client_base.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/client_base.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/_client.py
Labels: Azure.Core, KeyVault

#6412 Smoke test for Python
  .docsettings.yml
  samples/smoketest/Program.py
  samples/smoketest/README.md
  samples/smoketest/cosmos_db.py
  samples/smoketest/event_hubs.py
  samples/smoketest/key_vault_secrets.py
  samples/smoketest/requirements.txt
  samples/smoketest/storage_blob.py
Labels: EngSys

#6471 [AutoPR datafactory/resource-manager] Change type name and add timeout property
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_explorer_command_activity.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_explorer_command_activity_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/execution_activity.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/execution_activity_py3.py
Labels: RestPRMerged

#6454 add decorator and policy to storage_files and propagate context for it
  sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client.py
  sdk/storage/azure-storage-file/azure/storage/file/_shared/base_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/_shared/downloads.py
  sdk/storage/azure-storage-file/azure/storage/file/_shared/uploads.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/directory_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/file_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/file_service_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/share_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/directory_client.py
  sdk/storage/azure-storage-file/azure/storage/file/file_client.py
  sdk/storage/azure-storage-file/azure/storage/file/file_service_client.py
  sdk/storage/azure-storage-file/azure/storage/file/share_client.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py
Labels: Client, Storage

#6449 Trace storage queue
  sdk/storage/azure-storage-file/azure/storage/file/_shared/uploads.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/base_client_async.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/downloads.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py
  sdk/storage/azure-storage-queue/azure/storage/queue/aio/queue_client_async.py
  sdk/storage/azure-storage-queue/azure/storage/queue/aio/queue_service_client_async.py
  sdk/storage/azure-storage-queue/azure/storage/queue/queue_client.py
  sdk/storage/azure-storage-queue/azure/storage/queue/queue_service_client.py
Labels: Client, Storage

#6497 get rid of should only propagate
  sdk/core/azure-core/azure/core/pipeline/policies/distributed_tracing.py
  sdk/core/azure-core/azure/core/settings.py
  sdk/core/azure-core/azure/core/tracing/common.py
  sdk/core/azure-core/azure/core/tracing/decorator.py
  sdk/core/azure-core/azure/core/tracing/decorator_async.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_tracing_decorator_async.py
  sdk/core/azure-core/tests/test_settings.py
  sdk/core/azure-core/tests/test_tracing_decorator.py
  sdk/core/azure-core/tests/test_tracing_policy.py
  sdk/core/azure-core/tests/tracing_common.py
Labels: Azure.Core, Client

#6478 Trace storage blob
  README.md
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared/base_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared/download_chunking.py
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared/upload_chunking.py
  sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/blob_service_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/lease.py
  sdk/storage/azure-storage-blob/azure/storage/blob/polling.py
Labels: Client, Storage

#6122 [AutoPR signalr/resource-manager] Add new property for CORS settings
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcors_settings.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcors_settings_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_py3.py
Labels: RestPRMerged

#6490 [azure-core] Small fixes for aiohttp
  sdk/core/azure-core/azure/core/exceptions.py
  sdk/core/azure-core/azure/core/pipeline/policies/universal.py
  sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_asyncio.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_basic.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_trio.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_pipeline.py
  sdk/core/azure-core/tests/test_universal_pipeline.py
  sdk/identity/azure-identity/tests/helpers.py
  sdk/identity/azure-identity/tests/test_authn_client.py
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/identity/azure-identity/tests/test_identity_async.py
Labels: Azure.Core, Client

#6394 Eventhubs conn
  sdk/eventhub/azure-eventhubs/azure/eventhub/_connection_manager.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/_consumer_producer_mixin.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_connection_manager_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_consumer_producer_mixin_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/error_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/common.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/configuration.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/error.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
  sdk/eventhub/azure-eventhubs/tests/test_negative.py
Labels: Client, Event Hubs

#6515 [AutoPR security/resource-manager] chore: jsonfmt security
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/recommendation_configuration_properties.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/recommendation_configuration_properties_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/security_center_enums.py
Labels: RestPRMerged

#6505 [AutoPR datafactory/resource-manager] support dataset v2 split name
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_dw_table_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_dw_table_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_table_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_sql_table_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/drill_table_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/drill_table_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/google_big_query_object_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/google_big_query_object_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/greenplum_table_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/greenplum_table_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/hive_object_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/hive_object_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/impala_object_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/impala_object_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/oracle_table_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/oracle_table_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/phoenix_object_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/phoenix_object_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/presto_object_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/presto_object_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/spark_object_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/spark_object_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/sql_server_table_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/sql_server_table_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/vertica_table_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/vertica_table_dataset_py3.py
Labels: RestPRMerged

#6324 create_batch feature implementation (#6256)
  sdk/eventhub/azure-eventhubs/azure/eventhub/__init__.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/_consumer_producer_mixin.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_connection_manager_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_consumer_producer_mixin_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/common.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/error.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
  sdk/eventhub/azure-eventhubs/tests/asynctests/test_auth_async.py
  sdk/eventhub/azure-eventhubs/tests/asynctests/test_longrunning_receive_async.py
  sdk/eventhub/azure-eventhubs/tests/asynctests/test_negative_async.py
  sdk/eventhub/azure-eventhubs/tests/test_auth.py
  sdk/eventhub/azure-eventhubs/tests/test_negative.py
Labels: Event Hubs, Mgmt

#6402 [AutoPR hdinsight/resource-manager] [HDInsight] Add Capabilities to Stable API version,Modify ApplicationType,AccessModes to enum
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_hd_insight_management_client_enums.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/_locations_operations.py
Labels: RestPRMerged

#6530 decorator only trace very top level function
  sdk/core/azure-core/azure/core/tracing/decorator.py
  sdk/core/azure-core/azure/core/tracing/decorator_async.py
  sdk/core/azure-core/tests/azure_core_asynctests/test_tracing_decorator_async.py
  sdk/core/azure-core/tests/test_tracing_decorator.py
Labels: Azure.Core, Client

#6496 Only import aiohttp when necessary
  sdk/core/azure-core/azure/core/pipeline_client_async.py
Labels: Azure.Core, Client

#6536 [AutoPR storage/resource-manager] [SRP] Add new API ListBlobServices
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_paged_models.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_blob_services_operations.py
Labels: RestPRMerged

#6541 Document async dependencies
  sdk/identity/azure-identity/README.md
  sdk/keyvault/azure-keyvault-keys/README.md
  sdk/keyvault/azure-keyvault-secrets/README.md
Labels: Azure.Identity, Client, KeyVault

#5697 [AutoPR] alertsmanagement/resource-manager
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/HISTORY.rst
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/MANIFEST.in
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/README.rst
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/__init__.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/_alerts_management_client.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/_configuration.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/__init__.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_alerts_management_client_enums.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_models.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_models_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/_paged_models.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_item.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_item_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_properties.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_properties_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_paged.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_properties.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_properties_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group_item.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group_item_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/essentials.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/essentials_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_display.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_display_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_paged.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/resource.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/resource_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_aggregated_property.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_aggregated_property_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_item.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_item_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_properties.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_properties_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_groups_list.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_groups_list_py3.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/__init__.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_action_rules_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_alerts_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_smart_detector_alert_rules_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_smart_groups_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/version.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/setup.py
Labels: ServicePR

#6542 [AutoPR containerregistry/resource-manager] Revert "set a default api version"
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/_container_registry_management_client.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/models.py
Labels: RestPRMerged

#6416 Implement (synchronous) username/password auth
  sdk/identity/azure-identity/azure/identity/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
  sdk/identity/azure-identity/azure/identity/constants.py
  sdk/identity/azure-identity/azure/identity/credentials.py
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/keyvault/azure-keyvault-keys/tests/keys_helpers.py
  sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth.py
  sdk/keyvault/azure-keyvault-keys/tests/test_challenge_auth_async.py
Labels: Azure.Identity, Client

#6466 Implement synchronous interactive authentication
  sdk/identity/azure-identity/azure/identity/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/auth_code_redirect_handler.py
  sdk/identity/azure-identity/azure/identity/browser_auth.py
  sdk/identity/azure-identity/tests/test_identity.py
Labels: Azure.Identity, Client

#6567 [AutoPR datafactory/resource-manager] Enable Avro Dataset in public swagger
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_dataset_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_sink.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_sink_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_source.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_source_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_write_settings.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/avro_write_settings_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/copy_sink.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/copy_sink_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/copy_source.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/copy_source_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/data_factory_management_client_enums.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/dataset.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/dataset_py3.py
Labels: RestPRMerged

#6535 [AutoPR hanaonazure/resource-manager] Removing monitoring hana instance API
  sdk/hanaonazure/azure-mgmt-hanaonazure/HISTORY.rst
  sdk/hanaonazure/azure-mgmt-hanaonazure/README.rst
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/_hana_instances_operations.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/setup.py
Labels: RestPRMerged

#6545 [AutoPR hdinsight/resource-manager] [HDInsight] Change accessModes and applicationType from enum to string
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_hd_insight_management_client_enums.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py
Labels: RestPRMerged

#6526 [AutoPR security/resource-manager] Set IoTSecuritySolutions & IoTSecuritySolutionAnalytics API as stable
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_devices_list.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_alerted_devices_list_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendations_list.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/io_tsecurity_device_recommendations_list_py3.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/models/security_center_enums.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/__init__.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_aggregated_alert_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_aggregated_alerts_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_recommendation_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_analytics_recommendations_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/io_tsecurity_solutions_resource_group_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/operations/iot_security_solution_operations.py
  sdk/security/azure-mgmt-security/azure/mgmt/security/security_center.py
Labels: RestPRMerged

#6534 [AutoPR healthcareapis/resource-manager] Update the possible Kind values to include FHIR R4
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/_configuration.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/_healthcare_apis_management_client.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_healthcare_apis_management_client_enums.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_paged_models.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/check_name_availability_parameters.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/check_name_availability_parameters_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details_internal.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details_internal_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_display.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_display_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_results_description.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_results_description_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/resource.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/resource_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_access_policy_entry.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_access_policy_entry_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_authentication_configuration_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_authentication_configuration_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cors_configuration_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cors_configuration_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cosmos_db_configuration_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cosmos_db_configuration_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_description.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_description_paged.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_description_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_name_availability_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_name_availability_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_patch_description.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_patch_description_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_properties.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_properties_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operation_results_operations.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operations.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_services_operations.py
Labels: RestPRMerged
