Repository Azure/azure-sdk-for-python, pull requests merged in 2019-01, with the labels that each got.

#3203 [AutoPR] netapp/resource-manager
  azure-mgmt-netapp/HISTORY.rst
  azure-mgmt-netapp/MANIFEST.in
  azure-mgmt-netapp/README.rst
  azure-mgmt-netapp/azure/__init__.py
  azure-mgmt-netapp/azure/mgmt/__init__.py
  azure-mgmt-netapp/azure/mgmt/netapp/__init__.py
  azure-mgmt-netapp/azure/mgmt/netapp/azure_net_app_files_management_client.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/__init__.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/azure_net_app_files_management_client_enums.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_paged.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/dimension.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/dimension_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/error.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/error_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/metric_specification.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/metric_specification_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/mount_target.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/mount_target_paged.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/mount_target_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_paged.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/operation.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/operation_display.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/operation_display_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/operation_paged.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/operation_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/service_specification.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/service_specification_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_paged.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_paged.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/__init__.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/mount_targets_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/pools_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/snapshots_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/volumes_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/version.py
  azure-mgmt-netapp/sdk_packaging.toml
  azure-mgmt-netapp/setup.cfg
  azure-mgmt-netapp/setup.py
Labels: ServicePR

#4122 [AutoPR storagesync/resource-manager] Microsoft.StorageSync : Change from preview to stable for 2018-10-01 ApiVersion
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/__init__.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/cloud_endpoint.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/cloud_endpoint_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/registered_server.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/registered_server_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint_create_parameters.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint_create_parameters_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint_health.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint_health_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint_update_parameters.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/server_endpoint_update_parameters_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/sync_progress_status.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/sync_progress_status_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/sync_session_status.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/models/sync_session_status_py3.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/operations/cloud_endpoints_operations.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/operations/operations.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/operations/registered_servers_operations.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/operations/server_endpoints_operations.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/operations/storage_sync_services_operations.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/operations/sync_groups_operations.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/operations/workflows_operations.py
  azure-mgmt-storagesync/azure/mgmt/storagesync/storage_sync_management_client.py
Labels: RestPRMerged

#4090 [AutoPR datafactory/resource-manager] [Azure Data Factory] Change Ssis activity property type to support expression
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/data_factory_management_client_enums.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/execute_ssis_package_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/execute_ssis_package_activity_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/ssis_package_location.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/ssis_package_location_py3.py
Labels: RestPRMerged

#4119 [AutoPR containerservices/resource-manager] [AKS] add empty resource group validation
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/operations/managed_clusters_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/operations/open_shift_managed_clusters_operations.py
Labels: RestPRMerged

#4028 [AutoPR] cognitiveservices/data-plane/Face
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/face_list_operations.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/large_face_list_operations.py
  azure-cognitiveservices-vision-face/sdk_packaging.toml
Labels: ServicePR

#4035 [AutoPR] cognitiveservices/data-plane/CustomVision/Training
  azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/custom_vision_training_client.py
  azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/project.py
  azure-cognitiveservices-vision-customvision/azure/cognitiveservices/vision/customvision/training/models/project_py3.py
Labels: ServicePR

#2985 [AutoPR cognitiveservices/data-plane/ComputerVision] Remove basePath from Computer Vision 2.0 swagger.
  azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_client.py
Labels: RestPRInProgress

#4133 [AutoPR network/resource-manager] Fix duplicate path in old Network API version
  azure-mgmt-network/azure/mgmt/network/v2015_06_15/operations/virtual_network_gateway_connections_operations.py
Labels: RestPRMerged

#4143 [AutoPR network/resource-manager] Fix errors with ddosCustomPolicy.json
  azure-mgmt-network/azure/mgmt/network/network_management_client.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/__init__.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/ddos_custom_policy.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/ddos_custom_policy_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/network_management_client_enums.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/protocol_custom_settings_format.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/protocol_custom_settings_format_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/network_management_client.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/operations/__init__.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/operations/ddos_custom_policies_operations.py
Labels: RestPRMerged

#4064 [AutoPR] containerservices/resource-manager
  azure-mgmt-containerservice/HISTORY.rst
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/container_service_agent_pool_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/container_service_agent_pool_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/container_service_master_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/container_service_master_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/operations/container_services_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/container_service_master_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/container_service_master_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/credential_results.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/credential_results_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_agent_pool_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_agent_pool_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/operations/managed_clusters_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/container_service_master_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/container_service_master_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/credential_results.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/credential_results_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster_agent_pool_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster_agent_pool_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/operations/managed_clusters_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/models/open_shift_router_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/models/open_shift_router_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_09_30_preview/operations/open_shift_managed_clusters_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/version.py
Labels: ServicePR

#4130 [AutoPR compute/resource-manager] Update ComputerName definition for OsProfile
  azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2015_06_15/models/os_profile_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/models/os_profile_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/models/os_profile_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/models/os_profile_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/models/os_profile_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/models/os_profile_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/os_profile_py3.py
Labels: RestPRMerged

#4140 [AutoPR datafactory/resource-manager] [Datafactory] Add Webhook Activity to Azure Data Factory
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/data_factory_management_client_enums.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/web_hook_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/web_hook_activity_py3.py
Labels: RestPRMerged

#4153 [AutoPR logic/resource-manager] [LogicApps] Fix more acronyms that don't match API
  azure-mgmt-logic/azure/mgmt/logic/models/as2_error_settings.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_error_settings_py3.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_mdn_settings.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_mdn_settings_py3.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_security_settings.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_security_settings_py3.py
Labels: RestPRMerged

#4163 [AutoPR sql/resource-manager] Fix set LTR policy example
  azure-mgmt-sql/azure/mgmt/sql/operations/long_term_retention_backups_operations.py
Labels: RestPRMerged

#4173 [AutoPR datafactory/resource-manager] [Azure Data Factory] Add winauth support in SSIS Activity
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/execute_ssis_package_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/execute_ssis_package_activity_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/ssis_execution_credential.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/ssis_execution_credential_py3.py
Labels: RestPRMerged

#4139 [AutoPR monitor/resource-manager] Add version 2018-11-27-preview to Microsoft.Insights
  azure-mgmt-monitor/azure/mgmt/monitor/models/__init__.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/data_container.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/data_container_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/error.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/error_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/monitor_management_client_enums.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/proxy_resource.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/proxy_resource_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/response_with_error.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/response_with_error_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/vm_insights_onboarding_status.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/vm_insights_onboarding_status_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/workspace_info.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/workspace_info_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/monitor_management_client.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/__init__.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/vm_insights_operations.py
  azure-mgmt-monitor/azure/mgmt/monitor/version.py
Labels: RestPRMerged

#4085 [AutoPR] logic/resource-manager
  azure-mgmt-logic/HISTORY.rst
  azure-mgmt-logic/azure/mgmt/logic/models/as2_error_settings.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_error_settings_py3.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_mdn_settings.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_mdn_settings_py3.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_security_settings.py
  azure-mgmt-logic/azure/mgmt/logic/models/as2_security_settings_py3.py
  azure-mgmt-logic/azure/mgmt/logic/version.py
Labels: ServicePR

#4141 [AutoPR] network/resource-manager
  azure-mgmt-network/HISTORY.rst
  azure-mgmt-network/azure/mgmt/network/network_management_client.py
  azure-mgmt-network/azure/mgmt/network/v2015_06_15/operations/virtual_network_gateway_connections_operations.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/__init__.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/ddos_custom_policy.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/ddos_custom_policy_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/network_management_client_enums.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/protocol_custom_settings_format.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/models/protocol_custom_settings_format_py3.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/network_management_client.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/operations/__init__.py
  azure-mgmt-network/azure/mgmt/network/v2018_11_01/operations/ddos_custom_policies_operations.py
  azure-mgmt-network/azure/mgmt/network/version.py
Labels: ServicePR

#4185 [AutoPR datafactory/resource-manager] For preview api: Change type of Ssis actitvity to support expression
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/validation_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/validation_activity_py3.py
Labels: RestPRMerged

#4164 [AutoPR eventgrid/data-plane] Add MediaJobOutputProgressEventData in Media Services EventGrid swagger
  azure-eventgrid/azure/eventgrid/models/__init__.py
  azure-eventgrid/azure/eventgrid/models/media_job_output_progress_event_data.py
  azure-eventgrid/azure/eventgrid/models/media_job_output_progress_event_data_py3.py
Labels: RestPRMerged

#4171 [AutoPR devspaces/resource-manager] Adding API version 2019-01-01-preview for Microsoft.DevSpaces
  azure-mgmt-devspaces/MANIFEST.in
  azure-mgmt-devspaces/azure/mgmt/devspaces/dev_spaces_management_client.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/__init__.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/container_host_mapping.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/container_host_mapping_py3.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller_connection_details.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller_connection_details_py3.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller_py3.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/dev_spaces_management_client_enums.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/kubernetes_connection_details.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/kubernetes_connection_details_py3.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/orchestrator_specific_connection_details.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/orchestrator_specific_connection_details_py3.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/operations/__init__.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/operations/container_host_mappings_operations.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/operations/controllers_operations.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/operations/operations.py
Labels: RestPRMerged

#4199 [AutoPR blueprint/resource-manager] typo: blueprint/resource-manager/Microsoft.Blueprint
  azure-mgmt-blueprint/azure/mgmt/blueprint/blueprint_management_client.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/__init__.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/managed_service_identity.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/managed_service_identity_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/user_assigned_identity.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/user_assigned_identity_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/__init__.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/artifacts_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/assignments_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/blueprints_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/published_artifacts_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/published_blueprints_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/version.py
Labels: RestPRMerged

#4196 [AutoPR containerregistry/resource-manager] Add target and credentials flag to the requests.
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/__init__.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/container_registry_management_client_enums.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/credentials.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/credentials_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/custom_registry_credentials.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/custom_registry_credentials_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_request.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_request_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step_update_parameters.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/docker_build_step_update_parameters_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/encoded_task_run_request.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/encoded_task_run_request_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/file_task_run_request.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/file_task_run_request_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/run.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/run_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/secret_object.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/secret_object_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_registry_credentials.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_registry_credentials_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task_update_parameters.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/task_update_parameters_py3.py
Labels: RestPRMerged

#4204 [AutoPR datafactory/resource-manager] Remove webhook activity
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/data_factory_management_client_enums.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/web_hook_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/web_hook_activity_py3.py
Labels: RestPRMerged

#4214 [AutoPR iothub/resource-manager] Adding JSON encoding type to storage endpoint
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_storage_container_properties.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_storage_container_properties_py3.py
Labels: RestPRMerged

#4219 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Align with latest released version of Face API with Snapshot features.
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/face_client.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/__init__.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/apply_snapshot_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/apply_snapshot_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/face_client_enums.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/operation_status.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/operation_status_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/snapshot.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/snapshot_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/take_snapshot_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/take_snapshot_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/update_snapshot_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/update_snapshot_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/__init__.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/snapshot_operations.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/version.py
Labels: RestPRMerged

#4216 [AutoPR security/resource-manager] Add description to empty result in Workspace Settings Get
  azure-mgmt-security/azure/mgmt/security/operations/workspace_settings_operations.py
Labels: RestPRMerged

#4218 [AutoPR hdinsight/resource-manager] [HDInsight] - Support MSI for ADLS gen2
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/storage_account.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/storage_account_py3.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/version.py
Labels: RestPRMerged

#4209 [AutoPR recoveryservicesbackup/resource-manager] typo: recoveryservicesbackup/resource-manager/Microsoft.RecoveryServices
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_backup_server_engine.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_backup_server_engine_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_iaa_svm_job_task_details.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_iaa_svm_job_task_details_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_database_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_database_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_database_workload_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_database_workload_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_system_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_system_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_system_workload_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_ase_system_workload_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_database_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_database_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_database_workload_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_database_workload_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_system_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_system_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_system_workload_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sap_hana_system_workload_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_availability_group_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_availability_group_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_database_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_database_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_database_workload_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_database_workload_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_instance_protectable_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_instance_protectable_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_instance_workload_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_vm_workload_sql_instance_workload_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_point_in_time_recovery_point.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_point_in_time_recovery_point_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_recovery_point.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_recovery_point_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sap_hana_point_in_time_recovery_point.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sap_hana_point_in_time_recovery_point_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sap_hana_recovery_point.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sap_hana_recovery_point_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sql_point_in_time_recovery_point.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sql_point_in_time_recovery_point_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sql_recovery_point.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/azure_workload_sql_recovery_point_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/backup_engine_base.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/backup_engine_base_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/backup_engine_extended_info.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/backup_engine_extended_info_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/dpm_backup_engine.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/dpm_backup_engine_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/dpm_protected_item.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/dpm_protected_item_py3.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/key_and_secret_details.py
  azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/models/key_and_secret_details_py3.py
Labels: RestPRMerged

#4176 [AutoPR cognitiveservices/resource-manager] Adding customSubDomainName property.
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_py3.py
Labels: RestPRMerged

#4231 [AutoPR resources/resource-manager] Adding ResourceGroup example
  azure-mgmt-resource/azure/mgmt/resource/features/feature_client.py
  azure-mgmt-resource/azure/mgmt/resource/links/management_link_client.py
  azure-mgmt-resource/azure/mgmt/resource/locks/management_lock_client.py
  azure-mgmt-resource/azure/mgmt/resource/policy/policy_client.py
  azure-mgmt-resource/azure/mgmt/resource/resources/resource_management_client.py
  azure-mgmt-resource/azure/mgmt/resource/subscriptions/subscription_client.py
Labels: RestPRMerged

#4186 [AutoPR] hanaonazure/resource-manager
  azure-mgmt-hanaonazure/HISTORY.rst
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/hana_instances_operations.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: ServicePR

#4170 Add dependency analysis
  .azure-pipelines/client.yml
  azure-common/setup.py
  azure-template/setup.py
  scripts/analyze_deps.py
  shared_requirements.txt
Labels: engineering system

#4240 [AutoPR cognitiveservices/data-plane/Face] [Cogs Face] Refine the documentation for Face API's new Snapshot features.
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/find_similar_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/find_similar_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/face_operations.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/snapshot_operations.py
Labels: RestPRMerged

#4224 [AutoPR] hdinsight/resource-manager
  azure-mgmt-hdinsight/HISTORY.rst
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/storage_account.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/storage_account_py3.py
  azure-mgmt-hdinsight/azure/mgmt/hdinsight/version.py
Labels: ServicePR

#4246 [AutoPR containerservice/resource-manager] [AKS] add apiServerAuthorizedIPRanges property
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_08_01_preview/models/managed_cluster_py3.py
Labels: RestPRMerged

#4254 [AutoPR hanaonazure/resource-manager] Add new field 'proximityPlacementGroup' to properties of HanaInstance
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance_py3.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: RestPRMerged

#4245 [AutoPR cognitiveservices/data-plane/LUIS/Runtime] Add dispatch child to LUIS Runtime response
  azure-cognitiveservices-language-luis/MANIFEST.in
  azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result.py
  azure-cognitiveservices-language-luis/azure/cognitiveservices/language/luis/runtime/models/luis_result_py3.py
  azure-cognitiveservices-language-luis/setup.py
Labels: RestPRMerged

#4267 [AutoPR sql/resource-manager] Update managedInstances.json
  azure-mgmt-sql/README.rst
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update_py3.py
Labels: RestPRMerged

#4229 [AutoPR securityinsights/resource-manager] Creates the "real" API for Scheduled Alert Rules
  azure-mgmt-securityinsight/HISTORY.rst
  azure-mgmt-securityinsight/MANIFEST.in
  azure-mgmt-securityinsight/README.rst
  azure-mgmt-securityinsight/azure/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/alert_rule.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/alert_rule_kind1.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/alert_rule_kind1_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/alert_rule_paged.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/alert_rule_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_display.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_display_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_paged.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/resource.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/resource_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/scheduled_alert_rule.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/scheduled_alert_rule_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/security_insights_enums.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/alert_rules_operations.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/operations.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/security_insights.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/version.py
  azure-mgmt-securityinsight/sdk_packaging.toml
  azure-mgmt-securityinsight/setup.cfg
  azure-mgmt-securityinsight/setup.py
Labels: RestPRMerged

#4258 [AutoPR eventgrid/data-plane] Add Helm Events to ACR Schema for Event Grid
  azure-eventgrid/azure/eventgrid/models/__init__.py
  azure-eventgrid/azure/eventgrid/models/container_registry_artifact_event_data.py
  azure-eventgrid/azure/eventgrid/models/container_registry_artifact_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/container_registry_artifact_event_target.py
  azure-eventgrid/azure/eventgrid/models/container_registry_artifact_event_target_py3.py
  azure-eventgrid/azure/eventgrid/models/container_registry_chart_deleted_event_data.py
  azure-eventgrid/azure/eventgrid/models/container_registry_chart_deleted_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/container_registry_chart_pushed_event_data.py
  azure-eventgrid/azure/eventgrid/models/container_registry_chart_pushed_event_data_py3.py
Labels: RestPRMerged

#4252 [AutoPR eventhub/resource-manager] Eventhub: Added skipEmptyArchives to Eventhub CaptureDescription
  azure-mgmt-eventhub/azure/mgmt/eventhub/models/capture_description.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/models/capture_description_py3.py
Labels: RestPRMerged
