Repository Azure/azure-sdk-for-python, pull requests merged in 2019-05, with the labels that each got.

#5004 [AutoPR portal/resource-manager] Add Swagger and Examples for shared dashboards to Azure
  azure-mgmt/portal/__init__.py
  azure-mgmt/portal/models/__init__.py
  azure-mgmt/portal/models/dashboard.py
  azure-mgmt/portal/models/dashboard_lens.py
  azure-mgmt/portal/models/dashboard_lens_py3.py
  azure-mgmt/portal/models/dashboard_paged.py
  azure-mgmt/portal/models/dashboard_parts.py
  azure-mgmt/portal/models/dashboard_parts_position.py
  azure-mgmt/portal/models/dashboard_parts_position_py3.py
  azure-mgmt/portal/models/dashboard_parts_py3.py
  azure-mgmt/portal/models/dashboard_py3.py
  azure-mgmt/portal/models/error_definition.py
  azure-mgmt/portal/models/error_definition_py3.py
  azure-mgmt/portal/models/error_response.py
  azure-mgmt/portal/models/error_response_py3.py
  azure-mgmt/portal/models/patchable_dashboard.py
  azure-mgmt/portal/models/patchable_dashboard_py3.py
  azure-mgmt/portal/models/resource_provider_operation.py
  azure-mgmt/portal/models/resource_provider_operation_display.py
  azure-mgmt/portal/models/resource_provider_operation_display_py3.py
  azure-mgmt/portal/models/resource_provider_operation_paged.py
  azure-mgmt/portal/models/resource_provider_operation_py3.py
  azure-mgmt/portal/operations/__init__.py
  azure-mgmt/portal/operations/dashboards_operations.py
  azure-mgmt/portal/operations/operations.py
  azure-mgmt/portal/portal_client.py
  azure-mgmt/portal/version.py
Labels: RestPRMerged

#5010 [AutoPR apimanagement/resource-manager] [Hub Generated] Review request for Microsoft.ApiManagement to add version stable/2019-01-01
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_sku_properties.py
  azure-mgmt-apimanagement/azure/mgmt/apimanagement/models/api_management_service_sku_properties_py3.py
Labels: RestPRMerged

#4955 [AutoPR resources/resource-manager] Add list_by_scope
  azure-mgmt-resource/azure/mgmt/resource/locks/v2016_09_01/operations/management_locks_operations.py
Labels: RestPRMerged

#3761 [AutoPR] cognitiveservices/resource-manager
  azure-mgmt-cognitiveservices/HISTORY.rst
  azure-mgmt-cognitiveservices/MANIFEST.in
  azure-mgmt-cognitiveservices/README.rst
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/__init__.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_parameter.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_parameter_py3.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_result.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/check_sku_availability_result_py3.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_create_parameters.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_create_parameters_py3.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_py3.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_update_parameters.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_account_update_parameters_py3.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/cognitive_services_management_client_enums.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/sku.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/models/sku_py3.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/accounts_operations.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/check_sku_availability_operations.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/operations.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/resource_skus_operations.py
  azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/version.py
  azure-mgmt-cognitiveservices/setup.py
Labels: ServicePR

#5050 [AutoPR containerservice/resource-manager] Revert node public ip support from 2019-04-01 model.
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/agent_pool.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/agent_pool_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile_properties.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile_properties_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/managed_cluster_agent_pool_profile_py3.py
Labels: RestPRMerged

#5061 [AutoPR cognitiveservices/data-plane/FormRecognizer] FormRecognizer - Update Title for SDK code generation
  azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/__init__.py
  azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/form_recognizer_client.py
Labels: RestPRMerged

#5067 [AutoPR containerservice/resource-manager] ACS Python update
  azure-mgmt-containerservice/azure/mgmt/containerservice/container_service_client.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/container_service_client.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/__init__.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile_list_result.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile_list_result_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/operations/__init__.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/operations/container_services_operations.py
Labels: RestPRMerged

#5068 [AutoPR containerservice/resource-manager] Location is pure ACS - Python
  azure-mgmt-containerservice/azure/mgmt/containerservice/container_service_client.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/orchestrator_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/orchestrator_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/orchestrator_version_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/models/orchestrator_version_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2017_07_01/operations/container_services_operations.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/container_service_client.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/__init__.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile_list_result.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile_list_result_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/models/orchestrator_version_profile_py3.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/operations/__init__.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2019_04_30/operations/container_services_operations.py
Labels: RestPRMerged

#5020 Updated exception hierarchy
  azure-core/azure/core/__init__.py
  azure-core/azure/core/exceptions.py
  azure-core/azure/core/pipeline/policies/retry.py
  azure-core/azure/core/pipeline/policies/universal.py
  azure-core/azure/core/pipeline/transport/aiohttp.py
  azure-core/azure/core/pipeline/transport/base.py
  azure-core/azure/core/pipeline/transport/requests_asyncio.py
  azure-core/azure/core/pipeline/transport/requests_basic.py
  azure-core/azure/core/pipeline/transport/requests_trio.py
Labels: Azure.Core, Client

#4956 [AutoPR keyvault/data-plane] Update Auto rest specs for KeyVault
  azure-keyvault/azure/keyvault/v2016_10_01/key_vault_client.py
  azure-keyvault/azure/keyvault/v2016_10_01/models/administrator_details.py
  azure-keyvault/azure/keyvault/v2016_10_01/models/administrator_details_py3.py
  azure-keyvault/azure/keyvault/v2016_10_01/models/contact.py
  azure-keyvault/azure/keyvault/v2016_10_01/models/contact_py3.py
  azure-keyvault/azure/keyvault/v2016_10_01/models/key_vault_client_enums.py
  azure-keyvault/azure/keyvault/v2016_10_01/models/x509_certificate_properties.py
  azure-keyvault/azure/keyvault/v2016_10_01/models/x509_certificate_properties_py3.py
  azure-keyvault/azure/keyvault/v7_0/key_vault_client.py
  azure-keyvault/azure/keyvault/v7_0/models/administrator_details.py
  azure-keyvault/azure/keyvault/v7_0/models/administrator_details_py3.py
  azure-keyvault/azure/keyvault/v7_0/models/contact.py
  azure-keyvault/azure/keyvault/v7_0/models/contact_py3.py
  azure-keyvault/azure/keyvault/v7_0/models/x509_certificate_properties.py
  azure-keyvault/azure/keyvault/v7_0/models/x509_certificate_properties_py3.py
Labels: RestPRMerged

#5069 [AutoPR alertsmanagement/resource-manager] typo: alertsmanagement/resource-manager/Microsoft.AlertsManagement
  azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/conditions.py
  azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/conditions_py3.py
Labels: RestPRMerged

#5087 [AutoPR storage/resource-manager] Storage: Added Java ReadMe
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/operations/blob_services_operations.py
Labels: RestPRMerged

#5095 [AutoPR storage/resource-manager] Support nextLink for list container request.
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/operations/blob_services_operations.py
  azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/list_container_items.py
  azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/list_container_items_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/blob_containers_operations.py
Labels: RestPRMerged

#5094 [AutoPR graphrbac/data-plane] graph: fix invalid types of accountEnabled
  azure-graphrbac/azure/graphrbac/models/service_principal.py
  azure-graphrbac/azure/graphrbac/models/service_principal_base.py
  azure-graphrbac/azure/graphrbac/models/service_principal_base_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters.py
  azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters.py
  azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters_py3.py
  azure-graphrbac/setup.py
Labels: RestPRMerged

#5137 [AutoPR cognitiveservices/data-plane/FormRecognizer] Fix version in form recognizer
  azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/form_recognizer_client.py
  azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/version.py
Labels: RestPRMerged

#4850 [AutoPR azure-kusto/resource-manager] Added data connection check name availability operation
  azure-mgmt-kusto/azure/mgmt/kusto/models/__init__.py
  azure-mgmt-kusto/azure/mgmt/kusto/models/check_name_result.py
  azure-mgmt-kusto/azure/mgmt/kusto/models/check_name_result_py3.py
  azure-mgmt-kusto/azure/mgmt/kusto/models/data_connection_check_name_request.py
  azure-mgmt-kusto/azure/mgmt/kusto/models/data_connection_check_name_request_py3.py
  azure-mgmt-kusto/azure/mgmt/kusto/models/kusto_management_client_enums.py
  azure-mgmt-kusto/azure/mgmt/kusto/operations/data_connections_operations.py
  azure-mgmt-kusto/setup.py
Labels: RestPRMerged

#5138 [AutoPR automation/resource-manager] chore: jsonfmt automation
  azure-mgmt-automation/azure/mgmt/automation/operations/dsc_configuration_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/job_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/runbook_draft_operations.py
  azure-mgmt-automation/azure/mgmt/automation/operations/runbook_operations.py
Labels: RestPRMerged

#5092 [AutoPR blueprint/resource-manager] Blueprints: timeCreated and lastModified should be date-time format
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_status.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_status_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_resource_status_base.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_resource_status_base_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_status.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_status_py3.py
  azure-mgmt-blueprint/setup.py
Labels: RestPRMerged

#4948 [AutoPR] netapp/resource-manager
  azure-mgmt-netapp/HISTORY.rst
  azure-mgmt-netapp/azure/mgmt/netapp/azure_net_app_files_management_client.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/__init__.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/active_directory.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/active_directory_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/azure_net_app_files_management_client_enums.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/error.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/error_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/resource_name_availability.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/resource_name_availability_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/resource_name_availability_request.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/resource_name_availability_request_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/snapshot_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_properties_export_policy.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_properties_export_policy_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_properties_export_policy.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_properties_export_policy_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/mount_targets_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/pools_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/snapshots_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/volumes_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/version.py
  azure-mgmt-netapp/setup.py
  azure-mgmt-netapp/tests/recordings/test_account.test_create_delete_account.yaml
  azure-mgmt-netapp/tests/recordings/test_account.test_get_account_by_name.yaml
  azure-mgmt-netapp/tests/recordings/test_account.test_list_accounts.yaml
  azure-mgmt-netapp/tests/recordings/test_account.test_patch_account.yaml
  azure-mgmt-netapp/tests/recordings/test_mounttarget.test_list_mount_target.yaml
  azure-mgmt-netapp/tests/recordings/test_pool.test_create_delete_pool.yaml
  azure-mgmt-netapp/tests/recordings/test_pool.test_get_pool_by_name.yaml
  azure-mgmt-netapp/tests/recordings/test_pool.test_list_pools.yaml
  azure-mgmt-netapp/tests/recordings/test_pool.test_patch_pool.yaml
  azure-mgmt-netapp/tests/recordings/test_pool.test_update_pool.yaml
  azure-mgmt-netapp/tests/recordings/test_snapshot.test_create_delete_snapshot.yaml
  azure-mgmt-netapp/tests/recordings/test_snapshot.test_get_snapshot_by_name.yaml
  azure-mgmt-netapp/tests/recordings/test_snapshot.test_list_snapshots.yaml
  azure-mgmt-netapp/tests/recordings/test_volume.test_create_delete_list_volume.yaml
  azure-mgmt-netapp/tests/recordings/test_volume.test_get_volume_by_name.yaml
  azure-mgmt-netapp/tests/recordings/test_volume.test_list_volumes.yaml
  azure-mgmt-netapp/tests/recordings/test_volume.test_patch_volume.yaml
  azure-mgmt-netapp/tests/recordings/test_volume.test_update_volume.yaml
  azure-mgmt-netapp/tests/setup.py
Labels: ServicePR

#5151 [AutoPR cdn/resource-manager] make "name" optional in DeliveryRule
  azure-mgmt-cdn/azure/mgmt/cdn/models/delivery_rule.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/delivery_rule_py3.py
Labels: RestPRMerged

#5160 [AutoPR cdn/resource-manager] add premium_chinaCdn to CDN sku
  azure-mgmt-cdn/azure/mgmt/cdn/models/cdn_management_client_enums.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/sku.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/sku_py3.py
Labels: RestPRMerged

#5089 [AutoPR applicationinsights/resource-manager] Update Application Insights Schema to support WorkItemConfig operations
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/work_item_create_configuration.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/models/work_item_create_configuration_py3.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/work_item_configurations_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/version.py
Labels: RestPRMerged

#5178 [AutoPR cognitiveservices/data-plane/FormRecognizer] Path fix for FormRecognizer
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/version.py
Labels: RestPRMerged

#5177 Service folder
  .docsettings.yml
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/HISTORY.rst
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/MANIFEST.in
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/README.rst
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/form_recognizer_client.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/analyze_result.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/analyze_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/error_information.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/error_information_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/error_response.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/error_response_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_key_value_pair.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_key_value_pair_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_page.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_page_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_table.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_table_column.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_table_column_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_table_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_token.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/extracted_token_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/form_document_report.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/form_document_report_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/form_operation_error.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/form_operation_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/inner_error.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/inner_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/keys_result.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/keys_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/model_result.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/model_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/models_result.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/models_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/train_request.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/train_request_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/train_result.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/models/train_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/version.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/sdk_packaging.toml
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/setup.cfg
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/setup.py
Labels: ServicePR

#5169 [AutoPR web/resource-manager] Add location based deleted Web Apps
  azure-mgmt-web/azure/mgmt/web/operations/deleted_web_apps_operations.py
Labels: RestPRMerged

#5201 [AutoPR automation/resource-manager] New path for automation
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/automation_client.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/dsc_configuration_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/job_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/node_count_information_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/runbook_draft_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/operations/runbook_operations.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/version.py
Labels: RestPRMerged

#5186 [AutoPR containerregistry/resource-manager] [ACR] Add Default Trigger Status for API Version 2018-09-01
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger_update_parameters.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/base_image_trigger_update_parameters_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger_update_parameters.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/source_trigger_update_parameters_py3.py
Labels: RestPRMerged

#5190 [AutoPR web/resource-manager] Add Source Web App Location
  azure-mgmt-web/azure/mgmt/web/models/cloning_info.py
  azure-mgmt-web/azure/mgmt/web/models/cloning_info_py3.py
Labels: RestPRMerged

#5143 Key Vault track 2 package stubs
  .github/CODEOWNERS
  azure-security-keyvault/HISTORY.md
  azure-security-keyvault/MANIFEST.in
  azure-security-keyvault/README.md
  azure-security-keyvault/azure/__init__.py
  azure-security-keyvault/azure/security/__init__.py
  azure-security-keyvault/azure/security/keyvault/__init__.py
  azure-security-keyvault/azure/security/keyvault/certificates/__init__.py
  azure-security-keyvault/azure/security/keyvault/keys/__init__.py
  azure-security-keyvault/azure/security/keyvault/secrets/__init__.py
  azure-security-keyvault/azure/security/keyvault/version.py
  azure-security-keyvault/setup.py
  azure-security-nspkg/README.md
  azure-security-nspkg/azure/__init__.py
  azure-security-nspkg/azure/security/__init__.py
  azure-security-nspkg/setup.py
  shared_requirements.txt
Labels: Client, KeyVault

#5212 [AutoPR web/resource-manager] Add Api-version 2018-11-01 for WebApps Collection
  azure-mgmt-web/azure/mgmt/web/operations/web_apps_operations.py
Labels: RestPRMerged

#4676 [AutoPR] managedservices/resource-manager
  azure-mgmt-managedservices/HISTORY.rst
  azure-mgmt-managedservices/MANIFEST.in
  azure-mgmt-managedservices/README.rst
  azure-mgmt-managedservices/azure/__init__.py
  azure-mgmt-managedservices/azure/mgmt/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/managed_services_client.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/authorization.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/authorization_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_error.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_error_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/managed_services_client_enums.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_display.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_display_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_list.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_list_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/plan.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/plan_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_paged.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_paged.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/operations.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_assignments_operations.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_definitions_operations.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/version.py
  azure-mgmt-managedservices/sdk_packaging.toml
  azure-mgmt-managedservices/setup.cfg
  azure-mgmt-managedservices/setup.py
  azure-mgmt-managedservices/tests/recordings/test_mgmt_managedservices.test_managedservices_crud.yaml
  azure-mgmt-managedservices/tests/test_mgmt_managedservices.py
Labels: ServicePR

#5191 [AutoPR security/resource-manager] Add compliance results
  azure-mgmt-security/azure/mgmt/security/models/__init__.py
  azure-mgmt-security/azure/mgmt/security/models/compliance_result.py
  azure-mgmt-security/azure/mgmt/security/models/compliance_result_paged.py
  azure-mgmt-security/azure/mgmt/security/models/compliance_result_py3.py
  azure-mgmt-security/azure/mgmt/security/models/security_center_enums.py
  azure-mgmt-security/azure/mgmt/security/operations/__init__.py
  azure-mgmt-security/azure/mgmt/security/operations/compliance_results_operations.py
  azure-mgmt-security/azure/mgmt/security/security_center.py
Labels: RestPRMerged

#5229 [AutoPR cognitiveservices/data-plane/FormRecognizer] FormRecognizer - Minor update to help text.
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/form_recognizer_client.py
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/version.py
Labels: RestPRMerged

#5249 [AutoPR iothub/resource-manager] IotHub new Py path
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/operations/iot_hub_operations.py
  sdk/iothub/azure-mgmt-iothub/azure/mgmt/iothub/version.py
Labels: RestPRMerged

#5256 [AutoPR applicationinsights/resource-manager] AppInsights new folder
  sdk/applicationinsights/azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/version.py
Labels: RestPRMerged

#5271 [AutoPR consumption/resource-manager] Consumption Python new folder
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/version.py
Labels: RestPRMerged

#5273 [AutoPR msi/resource-manager] New folder and version for MSI and Python
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/version.py
Labels: RestPRMerged

#5274 [AutoPR managementpartner/resource-manager] managementpartner new conf
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/version.py
Labels: RestPRMerged

#5165 [AutoPR hanaonazure/resource-manager] Added new SKUs
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile_py3.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: RestPRMerged

#5194 [AutoPR cognitiveservices/data-plane/ComputerVision] [Cogs OCR] Remove mode parameter from CognitiveService OCR GA API.
  azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_client.py
Labels: RestPRMerged

#5272 [AutoPR devspaces/resource-manager] Update DevSpaces 2019-04-01 swagger specs
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/__init__.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller_update_parameters.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/controller_update_parameters_py3.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/dev_spaces_error_response.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/models/dev_spaces_error_response_py3.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/operations/container_host_mappings_operations.py
  azure-mgmt-devspaces/azure/mgmt/devspaces/operations/controllers_operations.py
Labels: RestPRMerged

#3887 [AutoPR] msi/resource-manager
  azure-mgmt-hdinsight/test/test_mgmt_hdinsight.py
  azure-mgmt-msi/MANIFEST.in
  sdk/resources/azure-mgmt-msi/HISTORY.rst
  sdk/resources/azure-mgmt-msi/MANIFEST.in
  sdk/resources/azure-mgmt-msi/README.rst
  sdk/resources/azure-mgmt-msi/azure/__init__.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/__init__.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/__init__.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/managed_service_identity_client.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/__init__.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/identity.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/identity_paged.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/identity_py3.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/managed_service_identity_client_enums.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/operation.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/operation_display.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/operation_display_py3.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/operation_paged.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/models/operation_py3.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/operations/__init__.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/operations/operations.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/operations/user_assigned_identities_operations.py
  sdk/resources/azure-mgmt-msi/azure/mgmt/msi/version.py
  sdk/resources/azure-mgmt-msi/sdk_packaging.toml
  sdk/resources/azure-mgmt-msi/setup.cfg
  sdk/resources/azure-mgmt-msi/setup.py
Labels: ServicePR

#5168 [AutoPR azureactivedirectory/resource-manager] [Hub Generated] Review request for Microsoft.Aadiam to add version stable/2017-04-01
  azure-mgmt/azureactivedirectory/__init__.py
  azure-mgmt/azureactivedirectory/azureactivedirectory_client.py
  azure-mgmt/azureactivedirectory/models/__init__.py
  azure-mgmt/azureactivedirectory/models/azureactivedirectory_client_enums.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_category_resource.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_category_resource_collection.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_category_resource_collection_py3.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_category_resource_py3.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_resource.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_resource_collection.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_resource_collection_py3.py
  azure-mgmt/azureactivedirectory/models/diagnostic_settings_resource_py3.py
  azure-mgmt/azureactivedirectory/models/display.py
  azure-mgmt/azureactivedirectory/models/display_py3.py
  azure-mgmt/azureactivedirectory/models/error_definition.py
  azure-mgmt/azureactivedirectory/models/error_definition_py3.py
  azure-mgmt/azureactivedirectory/models/error_response.py
  azure-mgmt/azureactivedirectory/models/error_response_py3.py
  azure-mgmt/azureactivedirectory/models/log_settings.py
  azure-mgmt/azureactivedirectory/models/log_settings_py3.py
  azure-mgmt/azureactivedirectory/models/operations_discovery.py
  azure-mgmt/azureactivedirectory/models/operations_discovery_collection.py
  azure-mgmt/azureactivedirectory/models/operations_discovery_collection_py3.py
  azure-mgmt/azureactivedirectory/models/operations_discovery_py3.py
  azure-mgmt/azureactivedirectory/models/proxy_only_resource.py
  azure-mgmt/azureactivedirectory/models/proxy_only_resource_py3.py
  azure-mgmt/azureactivedirectory/models/retention_policy.py
  azure-mgmt/azureactivedirectory/models/retention_policy_py3.py
  azure-mgmt/azureactivedirectory/operations/__init__.py
  azure-mgmt/azureactivedirectory/operations/diagnostic_settings_category_operations.py
  azure-mgmt/azureactivedirectory/operations/diagnostic_settings_operations.py
  azure-mgmt/azureactivedirectory/operations/operations.py
  azure-mgmt/azureactivedirectory/version.py
Labels: RestPRMerged

#5288 [AutoPR customproviders/resource-manager] chore: jsonfmt customproviders
  sdk/azure-mgmt/customproviders/__init__.py
  sdk/azure-mgmt/customproviders/customproviders_client.py
  sdk/azure-mgmt/customproviders/models/__init__.py
  sdk/azure-mgmt/customproviders/models/custom_rp_action_route_definition.py
  sdk/azure-mgmt/customproviders/models/custom_rp_action_route_definition_py3.py
  sdk/azure-mgmt/customproviders/models/custom_rp_manifest.py
  sdk/azure-mgmt/customproviders/models/custom_rp_manifest_paged.py
  sdk/azure-mgmt/customproviders/models/custom_rp_manifest_py3.py
  sdk/azure-mgmt/customproviders/models/custom_rp_resource_type_route_definition.py
  sdk/azure-mgmt/customproviders/models/custom_rp_resource_type_route_definition_py3.py
  sdk/azure-mgmt/customproviders/models/custom_rp_route_definition.py
  sdk/azure-mgmt/customproviders/models/custom_rp_route_definition_py3.py
  sdk/azure-mgmt/customproviders/models/custom_rp_validations.py
  sdk/azure-mgmt/customproviders/models/custom_rp_validations_py3.py
  sdk/azure-mgmt/customproviders/models/customproviders_client_enums.py
  sdk/azure-mgmt/customproviders/models/error_definition.py
  sdk/azure-mgmt/customproviders/models/error_definition_py3.py
  sdk/azure-mgmt/customproviders/models/error_response.py
  sdk/azure-mgmt/customproviders/models/error_response_py3.py
  sdk/azure-mgmt/customproviders/models/resource.py
  sdk/azure-mgmt/customproviders/models/resource_provider_operation.py
  sdk/azure-mgmt/customproviders/models/resource_provider_operation_display.py
  sdk/azure-mgmt/customproviders/models/resource_provider_operation_display_py3.py
  sdk/azure-mgmt/customproviders/models/resource_provider_operation_paged.py
  sdk/azure-mgmt/customproviders/models/resource_provider_operation_py3.py
  sdk/azure-mgmt/customproviders/models/resource_providers_update.py
  sdk/azure-mgmt/customproviders/models/resource_providers_update_py3.py
  sdk/azure-mgmt/customproviders/models/resource_py3.py
  sdk/azure-mgmt/customproviders/operations/__init__.py
  sdk/azure-mgmt/customproviders/operations/custom_resource_provider_operations.py
  sdk/azure-mgmt/customproviders/operations/operations.py
  sdk/azure-mgmt/customproviders/version.py
Labels: RestPRMerged

#5283 [AutoPR consumption/resource-manager] chore: jsonfmt consumption
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/version.py
Labels: RestPRMerged

#2183 [AutoPR] managementpartner/resource-manager
  azure-mgmt-managementpartner/HISTORY.rst
  azure-mgmt-managementpartner/MANIFEST.in
  azure-mgmt-managementpartner/dev_requirements.txt
  sdk/managementpartner/azure-mgmt-managementpartner/HISTORY.rst
  sdk/managementpartner/azure-mgmt-managementpartner/MANIFEST.in
  sdk/managementpartner/azure-mgmt-managementpartner/README.rst
  sdk/managementpartner/azure-mgmt-managementpartner/azure/__init__.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/__init__.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/__init__.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/ace_provisioning_management_partner_api.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/__init__.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/error.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/error_py3.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/extended_error_info.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/extended_error_info_py3.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/operation_display.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/operation_display_py3.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/operation_response.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/operation_response_paged.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/operation_response_py3.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/partner_response.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/models/partner_response_py3.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/operations/__init__.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/operations/operation_operations.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/operations/partner_operations.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/operations/partners_operations.py
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/version.py
  sdk/managementpartner/azure-mgmt-managementpartner/dev_requirements.txt
  sdk/managementpartner/azure-mgmt-managementpartner/sdk_packaging.toml
  sdk/managementpartner/azure-mgmt-managementpartner/setup.cfg
  sdk/managementpartner/azure-mgmt-managementpartner/setup.py
  sdk/managementpartner/azure-mgmt-managementpartner/tests/recordings/test_mgmt_managementpartner.test_managementpartner_create.yaml
  sdk/managementpartner/azure-mgmt-managementpartner/tests/recordings/test_mgmt_managementpartner.test_managementpartner_delete.yaml
  sdk/managementpartner/azure-mgmt-managementpartner/tests/recordings/test_mgmt_managementpartner.test_managementpartner_get.yaml
  sdk/managementpartner/azure-mgmt-managementpartner/tests/recordings/test_mgmt_managementpartner.test_managementpartner_update.yaml
  sdk/managementpartner/azure-mgmt-managementpartner/tests/test_mgmt_managementpartner.py
Labels: ServicePR

#5322 [AutoPR databricks/resource-manager] chore: jsonfmt databricks
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/__init__.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/databricks_client.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/__init__.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/databricks_client_enums.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/error_detail.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/error_detail_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/error_info.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/error_info_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/error_response.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/error_response_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/operation.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/operation_display.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/operation_display_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/operation_paged.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/operation_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/resource.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/resource_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/sku.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/sku_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/tracked_resource.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/tracked_resource_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/workspace.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/workspace_paged.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/workspace_provider_authorization.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/workspace_provider_authorization_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/workspace_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/workspace_update.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/models/workspace_update_py3.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/operations/__init__.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/operations/operations.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/operations/workspaces_operations.py
  sdk/azure-mgmt-databricks/azure/mgmt/databricks/version.py
Labels: RestPRMerged

#5333 [AutoPR cosmos-db/resource-manager] added service name field in CosmosDb and created a Java readme
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/version.py
Labels: RestPRMerged

#5343 [AutoPR hanaonazure/resource-manager] Hanaonazure on SDK folder
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: RestPRMerged

#5275 [AutoPR] hanaonazure/resource-manager
  azure-mgmt-hanaonazure/dev_requirements.txt
  sdk/hanaonazure/azure-mgmt-hanaonazure/HISTORY.rst
  sdk/hanaonazure/azure-mgmt-hanaonazure/MANIFEST.in
  sdk/hanaonazure/azure-mgmt-hanaonazure/README.rst
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/__init__.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/__init__.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/__init__.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/hana_management_client.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/disk.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/disk_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/display.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/display_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/error_response.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/error_response_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance_paged.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hardware_profile_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/ip_address.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/ip_address_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/monitoring_details.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/monitoring_details_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/network_profile.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/network_profile_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/operation.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/operation_paged.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/operation_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/resource.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/resource_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/storage_profile.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/storage_profile_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/tags.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/tags_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/__init__.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/hana_instances_operations.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/operations.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/dev_requirements.txt
  sdk/hanaonazure/azure-mgmt-hanaonazure/sdk_packaging.toml
  sdk/hanaonazure/azure-mgmt-hanaonazure/setup.cfg
  sdk/hanaonazure/azure-mgmt-hanaonazure/setup.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/tests/recordings/test_azure_mgmt_hanaonazure.test_hanainstance_get.yaml
  sdk/hanaonazure/azure-mgmt-hanaonazure/tests/recordings/test_azure_mgmt_hanaonazure.test_hanainstance_list.yaml
  sdk/hanaonazure/azure-mgmt-hanaonazure/tests/recordings/test_azure_mgmt_hanaonazure.test_hanainstance_list_by_resource_group.yaml
  sdk/hanaonazure/azure-mgmt-hanaonazure/tests/test_azure_mgmt_hanaonazure.py
Labels: ServicePR

#5354 [AutoPR eventgrid/data-plane] EventGrid dataplane SDK folder
  sdk/eventgrid/azure-eventgrid/azure/eventgrid/event_grid_client.py
Labels: RestPRMerged

#5363 [AutoPR eventgrid/data-plane] Add new Event Grid event type for SignalR Service
  sdk/eventgrid/azure-eventgrid/azure/eventgrid/models/__init__.py
  sdk/eventgrid/azure-eventgrid/azure/eventgrid/models/signal_rservice_client_connection_connected_event_data.py
  sdk/eventgrid/azure-eventgrid/azure/eventgrid/models/signal_rservice_client_connection_connected_event_data_py3.py
  sdk/eventgrid/azure-eventgrid/azure/eventgrid/models/signal_rservice_client_connection_disconnected_event_data.py
  sdk/eventgrid/azure-eventgrid/azure/eventgrid/models/signal_rservice_client_connection_disconnected_event_data_py3.py
Labels: RestPRMerged

#5374 [AutoPR recoveryservicesbackup/resource-manager] recoveryservicesbackup new Python path
  sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/azure/mgmt/recoveryservicesbackup/version.py
Labels: RestPRMerged

#5376 [AutoPR alertsmanagement/resource-manager] [Hub Generated] Review request for Microsoft.AlertsManagement to add version stable/2019-03-01
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/__init__.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/alerts_management_client.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/__init__.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_item.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_item_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_properties.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_properties_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_modification_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_paged.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_properties.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_properties_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alert_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_management_client_enums.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group_item.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group_item_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_group_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/alerts_summary_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/essentials.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/essentials_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_display.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_display_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_paged.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/operation_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/proxy_resource.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/proxy_resource_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_aggregated_property.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_aggregated_property_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_item.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_item_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_properties.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_properties_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_modification_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_group_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_groups_list.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/models/smart_groups_list_py3.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/__init__.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/alerts_operations.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/operations.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/smart_groups_operations.py
  sdk/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/version.py
Labels: RestPRMerged

#5378 [AutoPR botservice/resource-manager] BotService SDK folder
  sdk/botservice/azure-mgmt-botservice/azure/mgmt/botservice/version.py
Labels: RestPRMerged

#5379 [AutoPR signalr/resource-manager] Change SDK folder
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/version.py
Labels: RestPRMerged

#5380 [AutoPR recoveryservices/resource-manager] recoveryservices new Py path
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/version.py
Labels: RestPRMerged

#3706 [AutoPR] signalr/resource-manager
  azure-mgmt-signalr/MANIFEST.in
  sdk/signalr/azure-mgmt-signalr/HISTORY.rst
  sdk/signalr/azure-mgmt-signalr/MANIFEST.in
  sdk/signalr/azure-mgmt-signalr/README.rst
  sdk/signalr/azure-mgmt-signalr/azure/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/dimension.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/dimension_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/metric_specification.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/metric_specification_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability_parameters.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability_parameters_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/name_availability_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/operation.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/operation_display.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/operation_display_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/operation_paged.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/operation_properties.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/operation_properties_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/operation_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/regenerate_key_parameters.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/regenerate_key_parameters_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/service_specification.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/service_specification_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_parameters.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_parameters_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rkeys.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rkeys_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rmanagement_client_enums.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_paged.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rupdate_parameters.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rupdate_parameters_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rusage.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rusage_name.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rusage_name_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rusage_paged.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rusage_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/tracked_resource.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/tracked_resource_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/operations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/signal_roperations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/usages_operations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/signal_rmanagement_client.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/version.py
  sdk/signalr/azure-mgmt-signalr/sdk_packaging.toml
  sdk/signalr/azure-mgmt-signalr/setup.cfg
  sdk/signalr/azure-mgmt-signalr/setup.py
Labels: ReadyforRelease, ServicePR

#3976 [AutoPR] dns/resource-manager
  azure-mgmt-dns/MANIFEST.in
  azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/record_sets_operations.py
  azure-mgmt-dns/azure/mgmt/dns/v2016_04_01/operations/zones_operations.py
  azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/record_sets_operations.py
  azure-mgmt-dns/azure/mgmt/dns/v2018_03_01_preview/operations/zones_operations.py
  azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/operations/record_sets_operations.py
  azure-mgmt-dns/azure/mgmt/dns/v2018_05_01/operations/zones_operations.py
Labels: ServicePR

#5384 [AutoPR billing/resource-manager] Billing new Py path
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/billing_management_client.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/__init__.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/payment_methods_operations.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/version.py
Labels: RestPRMerged

#5392 [AutoPR billing/resource-manager] ARM spec review for validateAddress for BillingRP
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/billing_management_client.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/__init__.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_management_client_enums.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/validate_address_response.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/validate_address_response_py3.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/__init__.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/billing_accounts_validate_address_operations.py
Labels: RestPRMerged

#5416 [AutoPR datamigration/resource-manager] chore: jsonfmt datamigrtion
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/version.py
Labels: RestPRMerged

#5419 [AutoPR eventgrid/resource-manager] Move EventGrid to new Py folder
  sdk/eventgrid/azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/domains_operations.py
  sdk/eventgrid/azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/topics_operations.py
  sdk/eventgrid/azure-mgmt-eventgrid/azure/mgmt/eventgrid/version.py
Labels: RestPRMerged

#5420 [AutoPR eventgrid/resource-manager] Change EG flatten parameter for PY
  sdk/eventgrid/azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/domains_operations.py
  sdk/eventgrid/azure-mgmt-eventgrid/azure/mgmt/eventgrid/operations/topics_operations.py
Labels: RestPRMerged

#5421 [AutoPR containerinstance/resource-manager] ACI new Py path
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/version.py
Labels: RestPRMerged

#5403 [AutoPR servicefabric/resource-manager] typo: servicefabric/resource-manager/Microsoft.ServiceFabric
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_upgrade_policy.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/cluster_upgrade_policy_py3.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/node_type_description.py
  azure-mgmt-servicefabric/azure/mgmt/servicefabric/models/node_type_description_py3.py
Labels: RestPRMerged

#5448 [AutoPR devspaces/resource-manager] DevSpaces new path
  sdk/aks/azure-mgmt-devspaces/azure/mgmt/devspaces/version.py
Labels: RestPRMerged

#5454 [AutoPR resources/resource-manager] Fix api version for subscription
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/subscription_client.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2018_06_01/operations/operations.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2018_06_01/operations/subscriptions_operations.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2018_06_01/operations/tenants_operations.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2018_06_01/subscription_client.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/subscriptions/v2018_06_01/version.py
Labels: RestPRMerged

#5436 Get Pylint Pass on Azure Core
  pylintrc
  sdk/core/azure-core/azure/__init__.py
  sdk/core/azure-core/azure/core/__init__.py
  sdk/core/azure-core/azure/core/async_paging.py
  sdk/core/azure-core/azure/core/configuration.py
  sdk/core/azure-core/azure/core/exceptions.py
  sdk/core/azure-core/azure/core/paging.py
  sdk/core/azure-core/azure/core/pipeline/__init__.py
  sdk/core/azure-core/azure/core/pipeline/base.py
  sdk/core/azure-core/azure/core/pipeline/base_async.py
  sdk/core/azure-core/azure/core/pipeline/policies/__init__.py
  sdk/core/azure-core/azure/core/pipeline/policies/base.py
  sdk/core/azure-core/azure/core/pipeline/policies/base_async.py
  sdk/core/azure-core/azure/core/pipeline/policies/custom_hook.py
  sdk/core/azure-core/azure/core/pipeline/policies/redirect.py
  sdk/core/azure-core/azure/core/pipeline/policies/redirect_async.py
  sdk/core/azure-core/azure/core/pipeline/policies/retry.py
  sdk/core/azure-core/azure/core/pipeline/policies/retry_async.py
  sdk/core/azure-core/azure/core/pipeline/policies/universal.py
  sdk/core/azure-core/azure/core/pipeline/transport/__init__.py
  sdk/core/azure-core/azure/core/pipeline/transport/aiohttp.py
  sdk/core/azure-core/azure/core/pipeline/transport/base.py
  sdk/core/azure-core/azure/core/pipeline/transport/base_async.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_asyncio.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_basic.py
  sdk/core/azure-core/azure/core/pipeline/transport/requests_trio.py
  sdk/core/azure-core/azure/core/pipeline_client.py
  sdk/core/azure-core/azure/core/pipeline_client_async.py
  sdk/core/azure-core/azure/core/polling/__init__.py
  sdk/core/azure-core/azure/core/polling/async_poller.py
  sdk/core/azure-core/azure/core/polling/poller.py
  sdk/core/azure-core/azure/core/version.py
Labels: Azure.Core

#5359 [AutoPR hanaonazure/resource-manager] Add Create HanaInstance API
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/hana_instances_operations.py
Labels: RestPRMerged

#5244 [AutoPR] cognitiveservices/data-plane/FormRecognizer
  sdk/cognitiveservices/azure-cognitiveservices-formrecognizer/azure/cognitiveservices/formrecognizer/form_recognizer_client.py
Labels: ServicePR

#5467 [AutoPR subscription/resource-manager] Make subscription a method parameter
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/subscriptions_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/subscription_client.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/version.py
Labels: RestPRMerged

#5468 [AutoPR] subscription/resource-manager
  sdk/subscription/azure-mgmt-subscription/HISTORY.rst
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/subscriptions_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/subscription_client.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/version.py
Labels: ServicePR

#4503 [AutoPR] search/resource-manager
  azure-mgmt-search/build.json
  azure-mgmt-search/dev_requirements.txt
  sdk/search/azure-mgmt-search/HISTORY.rst
  sdk/search/azure-mgmt-search/MANIFEST.in
  sdk/search/azure-mgmt-search/README.rst
  sdk/search/azure-mgmt-search/azure/__init__.py
  sdk/search/azure-mgmt-search/azure/mgmt/__init__.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/__init__.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/__init__.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/admin_key_result.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/admin_key_result_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/check_name_availability_input.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/check_name_availability_input_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/check_name_availability_output.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/check_name_availability_output_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/identity.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/identity_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/operation.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/operation_display.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/operation_display_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/operation_paged.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/operation_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/query_key.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/query_key_paged.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/query_key_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/resource.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/resource_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/search_management_client_enums.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/search_management_request_options.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/search_management_request_options_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/search_service.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/search_service_paged.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/search_service_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/sku.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/models/sku_py3.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/operations/__init__.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/operations/admin_keys_operations.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/operations/operations.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/operations/query_keys_operations.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/operations/services_operations.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/search_management_client.py
  sdk/search/azure-mgmt-search/azure/mgmt/search/version.py
  sdk/search/azure-mgmt-search/dev_requirements.txt
  sdk/search/azure-mgmt-search/sdk_packaging.toml
  sdk/search/azure-mgmt-search/setup.cfg
  sdk/search/azure-mgmt-search/setup.py
  sdk/search/azure-mgmt-search/tests/recordings/test_mgmt_search.test_search_admin_keys.yaml
  sdk/search/azure-mgmt-search/tests/recordings/test_mgmt_search.test_search_query_keys.yaml
  sdk/search/azure-mgmt-search/tests/recordings/test_mgmt_search.test_search_services.yaml
  sdk/search/azure-mgmt-search/tests/test_mgmt_search.py
Labels: ServicePR

#5415 [AutoPR advisor/resource-manager] [Microsoft.Advisor] Add isAlertable property to metadata entity properties. (API is not live yet)
  azure-mgmt-advisor/azure/mgmt/advisor/models/__init__.py
  azure-mgmt-advisor/azure/mgmt/advisor/models/advisor_management_client_enums.py
  azure-mgmt-advisor/azure/mgmt/advisor/models/metadata_entity.py
  azure-mgmt-advisor/azure/mgmt/advisor/models/metadata_entity_py3.py
Labels: RestPRMerged

#5472 [AutoPR web/resource-manager] Web new path
  sdk/appservice/azure-mgmt-web/azure/mgmt/web/version.py
Labels: RestPRMerged

#5461 [AutoPR cosmos-db/resource-manager] Fix limit and currentValue properties
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage_py3.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage_py3.py
Labels: RestPRMerged

#5344 Add module for local client settings
  sdk/core/azure-core/azure/core/settings.py
  sdk/core/azure-core/tests/test_settings.py
Labels: Azure.Core, Client

#5479 [AutoPR security/resource-manager] Remove redundent resourceGroup scope from all paths
  azure-mgmt-security/azure/mgmt/security/operations/regulatory_compliance_assessments_operations.py
  azure-mgmt-security/azure/mgmt/security/operations/regulatory_compliance_controls_operations.py
  azure-mgmt-security/azure/mgmt/security/operations/regulatory_compliance_standards_operations.py
Labels: RestPRMerged

#5496 [AutoPR cognitiveservices/data-plane/Personalizer] Personlizer Python
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/HISTORY.rst
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/MANIFEST.in
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/README.rst
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/error_response.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/error_response_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/internal_error.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/internal_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/personalizer_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/personalizer_error.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/personalizer_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_request.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_request_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_response.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_response_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rankable_action.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rankable_action_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/ranked_action.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/ranked_action_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/reward_request.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/reward_request_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/operations/events_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/personalizer_client.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/version.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/sdk_packaging.toml
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/setup.cfg
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/setup.py
Labels: RestPRMerged

#5506 [AutoPR graphrbac/data-plane] Graphrbac new path
  sdk/graphrbac/azure-graphrbac/azure/graphrbac/version.py
Labels: RestPRMerged

#5508 [AutoPR cognitiveservices/data-plane/ComputerVision] [Cogs OCR] Fix bugs in OCR swagger file
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/computer_vision_client.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/computer_vision_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/line.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/line_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/read_operation_result.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/read_operation_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/text_operation_result.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/text_operation_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/text_recognition_result.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/text_recognition_result_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/word.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/word_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/version.py
Labels: RestPRMerged

#5246 azure-identity prototype
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/azure/__init__.py
  sdk/identity/azure-identity/azure/identity/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/authn_client.py
  sdk/identity/azure-identity/azure/identity/aio/credentials.py
  sdk/identity/azure-identity/azure/identity/authn_client.py
  sdk/identity/azure-identity/azure/identity/credentials.py
  sdk/identity/azure-identity/azure/identity/exceptions.py
  sdk/identity/azure-identity/azure/identity/version.py
  sdk/identity/azure-identity/dev_requirements.txt
  sdk/identity/azure-identity/setup.py
  sdk/identity/azure-identity/tests/conftest.py
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/identity/azure-identity/tests/test_identity_async.py
  shared_requirements.txt
Labels: Azure.Identity, Client

#5521 [AutoPR cosmos-db/resource-manager] CosmosDB add Availability Zone option for locations
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location.py
  azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location_py3.py
Labels: RestPRMerged

#5523 [AutoPR automation/resource-manager] Adding support for minute schedule
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/automation_client_enums.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_create_or_update_parameters.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_create_or_update_parameters_py3.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_properties.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_properties_py3.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/schedule_py3.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_collection_item.py
  sdk/automation/azure-mgmt-automation/azure/mgmt/automation/models/software_update_configuration_collection_item_py3.py
Labels: RestPRMerged

#5531 [AutoPR signalr/resource-manager] Add a new field to SignalR Resource property
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rfeature.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rfeature_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/operations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/signal_roperations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/usages_operations.py
Labels: RestPRMerged

#5533 [AutoPR imds/data-plane] chore: jsonfmt imds
  sdk/azure-imds/azure/imds/__init__.py
  sdk/azure-imds/azure/imds/instance_metadata_client.py
  sdk/azure-imds/azure/imds/models/__init__.py
  sdk/azure-imds/azure/imds/models/attested_data.py
  sdk/azure-imds/azure/imds/models/attested_data_py3.py
  sdk/azure-imds/azure/imds/models/compute.py
  sdk/azure-imds/azure/imds/models/compute_py3.py
  sdk/azure-imds/azure/imds/models/error_response.py
  sdk/azure-imds/azure/imds/models/error_response_py3.py
  sdk/azure-imds/azure/imds/models/identity_error_response.py
  sdk/azure-imds/azure/imds/models/identity_error_response_py3.py
  sdk/azure-imds/azure/imds/models/identity_info_response.py
  sdk/azure-imds/azure/imds/models/identity_info_response_py3.py
  sdk/azure-imds/azure/imds/models/identity_token_response.py
  sdk/azure-imds/azure/imds/models/identity_token_response_py3.py
  sdk/azure-imds/azure/imds/models/instance.py
  sdk/azure-imds/azure/imds/models/instance_metadata_client_enums.py
  sdk/azure-imds/azure/imds/models/instance_py3.py
  sdk/azure-imds/azure/imds/models/ipv4_properties.py
  sdk/azure-imds/azure/imds/models/ipv4_properties_py3.py
  sdk/azure-imds/azure/imds/models/ipv6_properties.py
  sdk/azure-imds/azure/imds/models/ipv6_properties_py3.py
  sdk/azure-imds/azure/imds/models/network.py
  sdk/azure-imds/azure/imds/models/network_interface.py
  sdk/azure-imds/azure/imds/models/network_interface_ipv4.py
  sdk/azure-imds/azure/imds/models/network_interface_ipv4_py3.py
  sdk/azure-imds/azure/imds/models/network_interface_ipv6.py
  sdk/azure-imds/azure/imds/models/network_interface_ipv6_py3.py
  sdk/azure-imds/azure/imds/models/network_interface_py3.py
  sdk/azure-imds/azure/imds/models/network_py3.py
  sdk/azure-imds/azure/imds/models/plan_properties.py
  sdk/azure-imds/azure/imds/models/plan_properties_py3.py
  sdk/azure-imds/azure/imds/models/public_keys_properties.py
  sdk/azure-imds/azure/imds/models/public_keys_properties_py3.py
  sdk/azure-imds/azure/imds/models/subnet_properties.py
  sdk/azure-imds/azure/imds/models/subnet_properties_py3.py
  sdk/azure-imds/azure/imds/operations/__init__.py
  sdk/azure-imds/azure/imds/operations/attested_operations.py
  sdk/azure-imds/azure/imds/operations/identity_operations.py
  sdk/azure-imds/azure/imds/operations/instances_operations.py
  sdk/azure-imds/azure/imds/version.py
Labels: RestPRMerged

#5437 Sync key client implementation
  sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/__init__.py
  sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/_client.py
  sdk/keyvault/azure-security-keyvault/azure/security/keyvault/keys/_models.py
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_keys.test_example_key_crud_operations.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_keys.test_example_key_list_operations.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_keys.test_example_keys_backup_restore.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_keys.test_example_keys_recover_purge.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_examples_keys.test_key_wrap_and_unwrap.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_key_client.test_backup_restore.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_key_client.test_key_crud_operations.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_key_client.test_key_list.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_key_client.test_key_wrap_and_unwrap.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_key_client.test_list_versions.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_key_client.test_new_client.yaml
  sdk/keyvault/azure-security-keyvault/tests/recordings/test_key_client.test_recover_purge.yaml
  sdk/keyvault/azure-security-keyvault/tests/test_examples_keys.py
  sdk/keyvault/azure-security-keyvault/tests/test_key_client.py
Labels: KeyVault

#5542 [AutoPR managedservices/resource-manager] chore: jsonfmt managedservices
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/__init__.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/managed_services_client.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/__init__.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/authorization.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/authorization_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_error.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_error_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/managed_services_client_enums.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_display.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_display_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_list.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_list_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/plan.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/plan_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_paged.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_paged.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_py3.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/__init__.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/operations.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_assignments_operations.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_definitions_operations.py
  managedservices/azure-mgmt-managedservices/azure/mgmt/managedservices/version.py
Labels: RestPRMerged

#5502 [AutoPR] cognitiveservices/data-plane/Personalizer
  .docsettings.yml
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/HISTORY.rst
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/MANIFEST.in
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/README.rst
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/error_response.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/error_response_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/internal_error.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/internal_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/personalizer_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/personalizer_error.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/personalizer_error_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_request.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_request_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_response.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rank_response_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rankable_action.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/rankable_action_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/ranked_action.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/ranked_action_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/reward_request.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/models/reward_request_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/operations/events_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/personalizer_client.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/azure/cognitiveservices/personalizer/version.py
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/sdk_packaging.toml
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/setup.cfg
  sdk/cognitiveservices/azure-cognitiveservices-personalizer/setup.py
Labels: ServicePR

#5459 [AutoPR] hanaonazure/resource-manager
  sdk/hanaonazure/azure-mgmt-hanaonazure/HISTORY.rst
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_instance_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/os_profile_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/hana_instances_operations.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: ServicePR

#5539 [AutoPR hdinsight/resource-manager] [HDInsight] Fix specs not support subdomainsuffix parameter
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_https_endpoint.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/application_get_https_endpoint_py3.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/version.py
Labels: RestPRMerged

#5577 [AutoPR managementpartner/resource-manager] chore: jsonfmt managementpartner
  sdk/managementpartner/azure-mgmt-managementpartner/azure/mgmt/managementpartner/version.py
Labels: RestPRMerged

#5580 [AutoPR healthcareapis/resource-manager] chore: jsonfmt healthcareapis
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/healthcare_apis_management_client.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/check_name_availability_parameters.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/check_name_availability_parameters_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details_internal.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details_internal_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/error_details_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/healthcare_apis_management_client_enums.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/move_resources_parameters.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/move_resources_parameters_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_display.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_display_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_paged.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_results_description.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/operation_results_description_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/resource.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/resource_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_access_policy_entry.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_access_policy_entry_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cosmos_db_configuration_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/service_cosmos_db_configuration_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_description.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_description_paged.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_description_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_name_availability_info.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_name_availability_info_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_patch_description.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_patch_description_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_properties.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/services_properties_py3.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/__init__.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/move_resources_status_operations.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/operation_results_operations.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/operations.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/services_operations.py
  sdk/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/version.py
Labels: RestPRMerged

#5582 [AutoPR deviceprovisioningservices/resource-manager] chore: jsonfmt deviceprovisioningservices
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/iot_dps_client.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/iot_dps_properties_description.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/iot_dps_properties_description_py3.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/iot_dps_sku_definition.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/iot_dps_sku_definition_py3.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/iot_dps_sku_info.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/iot_dps_sku_info_py3.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/name_availability_info.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/name_availability_info_py3.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/models/provisioning_service_description_py3.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/operations/dps_certificate_operations.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/operations/iot_dps_resource_operations.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/operations/operations.py
  sdk/iothub/azure-mgmt-iothubprovisioningservices/azure/mgmt/iothubprovisioningservices/version.py
Labels: RestPRMerged

#5574 [AutoPR maps/resource-manager] chore: jsonfmt maps
  sdk/maps/azure-mgmt-maps/MANIFEST.in
  sdk/maps/azure-mgmt-maps/README.rst
  sdk/maps/azure-mgmt-maps/azure/mgmt/maps/models/__init__.py
  sdk/maps/azure-mgmt-maps/azure/mgmt/maps/models/maps_account.py
  sdk/maps/azure-mgmt-maps/azure/mgmt/maps/models/maps_account_properties.py
  sdk/maps/azure-mgmt-maps/azure/mgmt/maps/models/maps_account_properties_py3.py
  sdk/maps/azure-mgmt-maps/azure/mgmt/maps/models/maps_account_py3.py
  sdk/maps/azure-mgmt-maps/azure/mgmt/maps/operations/accounts_operations.py
  sdk/maps/azure-mgmt-maps/setup.py
Labels: RestPRMerged

#5590 [AutoPR billing/resource-manager] [Hub Generated] Review request for Microsoft.Billing to add version preview/2018-11-01-preview
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/__init__.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_account_update_properties.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/billing_account_update_properties_py3.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/billing_accounts_operations.py
Labels: RestPRMerged

#5595 [AutoPR billing/resource-manager] [Hub Generated] Review request for Microsoft.Billing to add version preview/2018-11-01-preview
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/billing_management_client.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/__init__.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/operations/addresses_operations.py
Labels: RestPRMerged

#5599 [AutoPR cosmos-db/resource-manager] Cosmos Python
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/version.py
Labels: RestPRMerged

#5602 [AutoPR] cosmos-db/resource-manager
  sdk/cosmos/azure-mgmt-cosmosdb/HISTORY.rst
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/location_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/partition_usage_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/models/usage_py3.py
  sdk/cosmos/azure-mgmt-cosmosdb/azure/mgmt/cosmosdb/version.py
Labels: ServicePR
