Repository Azure/azure-sdk-for-python, pull requests merged in 2019-03, with the labels that each got.

#4463 [AutoPR netapp/resource-manager] add netapp to Go SDK
  azure-mgmt-netapp/MANIFEST.in
  azure-mgmt-netapp/README.rst
  azure-mgmt-netapp/azure/mgmt/netapp/version.py
Labels: RestPRMerged

#4465 [AutoPR eventgrid/data-plane] Added Azure App Configuration event data schema.
  azure-eventgrid/MANIFEST.in
  azure-eventgrid/azure/eventgrid/models/__init__.py
  azure-eventgrid/azure/eventgrid/models/app_configuration_key_value_deleted_event_data.py
  azure-eventgrid/azure/eventgrid/models/app_configuration_key_value_deleted_event_data_py3.py
  azure-eventgrid/azure/eventgrid/models/app_configuration_key_value_modified_event_data.py
  azure-eventgrid/azure/eventgrid/models/app_configuration_key_value_modified_event_data_py3.py
  azure-eventgrid/azure/eventgrid/version.py
Labels: RestPRMerged

#4467 Fix azure-cognitiveservices-nspkg (and sub nspkg)
  azure-cognitiveservices-knowledge-nspkg/README.rst
  azure-cognitiveservices-language-nspkg/MANIFEST.in
  azure-cognitiveservices-language-nspkg/README.rst
  azure-cognitiveservices-language-nspkg/setup.cfg
  azure-cognitiveservices-language-nspkg/setup.py
  azure-cognitiveservices-nspkg/MANIFEST.in
  azure-cognitiveservices-nspkg/README.rst
  azure-cognitiveservices-nspkg/setup.cfg
  azure-cognitiveservices-nspkg/setup.py
  azure-cognitiveservices-search-nspkg/MANIFEST.in
  azure-cognitiveservices-search-nspkg/README.rst
  azure-cognitiveservices-search-nspkg/setup.cfg
  azure-cognitiveservices-search-nspkg/setup.py
  azure-cognitiveservices-vision-nspkg/MANIFEST.in
  azure-cognitiveservices-vision-nspkg/README.rst
  azure-cognitiveservices-vision-nspkg/setup.cfg
  azure-cognitiveservices-vision-nspkg/setup.py
Labels: Client, Cognitive Services, Packaging

#3674 [AutoPR applicationinsights/data-plane] Add example with nested segmentation, fix number types, remove extraneous `produces`
  azure-loganalytics/MANIFEST.in
  azure-loganalytics/azure/loganalytics/log_analytics_data_client.py
  azure-loganalytics/azure/loganalytics/operations/__init__.py
  azure-loganalytics/azure/loganalytics/operations/query_operations.py
Labels: RestPRInProgress

#4142 [AutoPR securityinsight/resource-manager] Creating first and basic swagger for new RP of ASI (Azure Security In…
  azure-mgmt-securityinsight/HISTORY.rst
  azure-mgmt-securityinsight/MANIFEST.in
  azure-mgmt-securityinsight/README.rst
  azure-mgmt-securityinsight/azure/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/alert_rule.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/alert_rule_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_display.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_display_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_paged.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/operation_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/resource.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/models/resource_py3.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/__init__.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/alert_rules_operations.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/operations/operations.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/security_insights.py
  azure-mgmt-securityinsight/azure/mgmt/securityinsight/version.py
  azure-mgmt-securityinsight/sdk_packaging.toml
  azure-mgmt-securityinsight/setup.cfg
  azure-mgmt-securityinsight/setup.py
Labels: RestPRInProgress

#4188 [AutoPR adhybridhealthservice/resource-manager] Dev adhybridhealthservice microsoft.ad hybrid health service 2014 01 01 binilkk
  azure-mgmt-adhybridhealthservice/README.rst
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/__init__.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/risky_ip_blob_uri.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/risky_ip_blob_uri_paged.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/risky_ip_blob_uri_py3.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/operations/services_operations.py
Labels: RestPRMerged

#4448 [AutoPR web/resource-manager] Update UserAssignedIdentities spec in Web
  azure-mgmt-web/azure/mgmt/web/models/__init__.py
  azure-mgmt-web/azure/mgmt/web/models/managed_service_identity.py
  azure-mgmt-web/azure/mgmt/web/models/managed_service_identity_py3.py
  azure-mgmt-web/azure/mgmt/web/models/managed_service_identity_user_assigned_identities_value.py
  azure-mgmt-web/azure/mgmt/web/models/managed_service_identity_user_assigned_identities_value_py3.py
Labels: RestPRMerged

#4459 [AutoPR security/resource-manager] Reverted security python readme to pre multi api
  azure-mgmt-security/azure/mgmt/security/models/pricing_paged.py
Labels: RestPRMerged

#4464 [AutoPR] netapp/resource-manager
  azure-mgmt-netapp/HISTORY.rst
  azure-mgmt-netapp/MANIFEST.in
  azure-mgmt-netapp/README.rst
  azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/mount_targets_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/pools_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/snapshots_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/volumes_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/version.py
Labels: ReadyforRelease, ServicePR

#4485 [AutoPR marketplaceordering/resource-manager] Add missing MarketplaceOrdering operations to swagger
  azure-mgmt-marketplaceordering/MANIFEST.in
  azure-mgmt-marketplaceordering/README.rst
  azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/operations/marketplace_agreements_operations.py
Labels: RestPRMerged

#4481 [AutoPR web/resource-manager] Fix Hosting Environment Network Dependencies pagination
  azure-mgmt-web/azure/mgmt/web/models/__init__.py
  azure-mgmt-web/azure/mgmt/web/models/inbound_environment_endpoint_paged.py
  azure-mgmt-web/azure/mgmt/web/models/outbound_environment_endpoint_paged.py
  azure-mgmt-web/azure/mgmt/web/operations/app_service_environments_operations.py
Labels: RestPRMerged

#4486 [AutoPR containerservice/resource-manager] Add regex validation for ManagedClusterAgentPoolProfile.name
  azure-mgmt-containerservice/MANIFEST.in
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_agent_pool_profile.py
  azure-mgmt-containerservice/azure/mgmt/containerservice/v2018_03_31/models/managed_cluster_agent_pool_profile_py3.py
Labels: RestPRMerged

#3184 [AutoPR] cdn/resource-manager
  azure-mgmt-cdn/HISTORY.rst
  azure-mgmt-cdn/MANIFEST.in
  azure-mgmt-cdn/README.rst
  azure-mgmt-cdn/azure/mgmt/cdn/cdn_management_client.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/__init__.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cache_expiration_action_parameters.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cache_expiration_action_parameters_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cdn_certificate_source_parameters.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cdn_certificate_source_parameters_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cdn_managed_https_parameters.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cdn_managed_https_parameters_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cdn_management_client_enums.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cidr_ip_address.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/cidr_ip_address_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/custom_domain.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/custom_domain_https_parameters.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/custom_domain_https_parameters_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/custom_domain_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/endpoint.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/endpoint_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/endpoint_update_parameters.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/endpoint_update_parameters_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/error_response.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/error_response_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/key_vault_certificate_source_parameters.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/key_vault_certificate_source_parameters_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/sku.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/sku_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/user_managed_https_parameters.py
  azure-mgmt-cdn/azure/mgmt/cdn/models/user_managed_https_parameters_py3.py
  azure-mgmt-cdn/azure/mgmt/cdn/operations/custom_domains_operations.py
  azure-mgmt-cdn/azure/mgmt/cdn/operations/edge_nodes_operations.py
  azure-mgmt-cdn/azure/mgmt/cdn/operations/endpoints_operations.py
  azure-mgmt-cdn/azure/mgmt/cdn/operations/operations.py
  azure-mgmt-cdn/azure/mgmt/cdn/operations/origins_operations.py
  azure-mgmt-cdn/azure/mgmt/cdn/operations/profiles_operations.py
  azure-mgmt-cdn/azure/mgmt/cdn/operations/resource_usage_operations.py
  azure-mgmt-cdn/azure/mgmt/cdn/version.py
  azure-mgmt-cdn/build.json
Labels: ServicePR

#4420 [AutoPR network/resource-manager] [Hub Generated] Review request for Microsoft.Network to add version 2018-12-01
  azure-mgmt-network/azure/mgmt/network/v2018_12_01/models/application_gateway.py
  azure-mgmt-network/azure/mgmt/network/v2018_12_01/models/application_gateway_py3.py
Labels: RestPRMerged

#4482 [AutoPR sql/resource-manager] typo: Winodws -> Windows
  azure-mgmt-sql/MANIFEST.in
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_py3.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update.py
  azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_update_py3.py
Labels: RestPRMerged

#2901 [AutoPR] search/resource-manager
  azure-mgmt-search/HISTORY.rst
  azure-mgmt-search/README.rst
  azure-mgmt-search/azure/mgmt/search/models/__init__.py
  azure-mgmt-search/azure/mgmt/search/models/identity.py
  azure-mgmt-search/azure/mgmt/search/models/identity_py3.py
  azure-mgmt-search/azure/mgmt/search/models/resource.py
  azure-mgmt-search/azure/mgmt/search/models/resource_py3.py
  azure-mgmt-search/azure/mgmt/search/models/search_service.py
  azure-mgmt-search/azure/mgmt/search/models/search_service_py3.py
  azure-mgmt-search/azure/mgmt/search/operations/admin_keys_operations.py
  azure-mgmt-search/azure/mgmt/search/operations/operations.py
  azure-mgmt-search/azure/mgmt/search/operations/query_keys_operations.py
  azure-mgmt-search/azure/mgmt/search/operations/services_operations.py
  azure-mgmt-search/azure/mgmt/search/version.py
  azure-mgmt-search/sdk_packaging.toml
Labels: ReadyforRelease, ServicePR

#2934 [AutoPR] managementgroups/resource-manager
  azure-mgmt-managementgroups/HISTORY.rst
  azure-mgmt-managementgroups/MANIFEST.in
  azure-mgmt-managementgroups/README.rst
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/management_groups_api.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/entity_info.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/models/entity_info_py3.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/entities_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_group_subscriptions_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/management_groups_operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/operations/operations.py
  azure-mgmt-managementgroups/azure/mgmt/managementgroups/version.py
Labels: ReadyforRelease, ServicePR

#4480 [AutoPR search/resource-manager] Azure Search: Resource Manager: Support 'None' Identity type
  azure-mgmt-search/MANIFEST.in
  azure-mgmt-search/azure/mgmt/search/models/__init__.py
  azure-mgmt-search/azure/mgmt/search/models/identity.py
  azure-mgmt-search/azure/mgmt/search/models/identity_py3.py
  azure-mgmt-search/azure/mgmt/search/models/search_management_client_enums.py
  azure-mgmt-search/azure/mgmt/search/version.py
Labels: RestPRMerged

#4490 [AutoPR datalake-analytics/data-plane] [ADLA] - Catalog - Add stream path to USqlTableFragment
  azure-mgmt-datalake-analytics/MANIFEST.in
  azure-mgmt-datalake-analytics/README.rst
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_index.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_index_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_column.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_column_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_fragment.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/models/usql_table_fragment_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/catalog/operations/catalog_operations.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_job_parameters.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_job_parameters_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_scope_job_parameters.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/create_scope_job_parameters_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/data_lake_analytics_job_management_client_enums.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/diagnostics.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/diagnostics_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_error_details.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_error_details_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_basic_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_information_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_statistics_vertex_stage.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/job_statistics_vertex_stage_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/update_job_parameters.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/models/update_job_parameters_py3.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/operations/job_operations.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/operations/pipeline_operations.py
  azure-mgmt-datalake-analytics/azure/mgmt/datalake/analytics/job/operations/recurrence_operations.py
Labels: RestPRMerged

#4471 [AutoPR consumption/resource-manager] [Hub Generated] Review request for Microsoft.Consumption to add version 2019-01-01
  azure-mgmt-consumption/MANIFEST.in
  azure-mgmt-consumption/azure/mgmt/consumption/operations/budgets_operations.py
Labels: RestPRMerged

#4220 [AutoPR] cognitiveservices/data-plane/Face
  azure-cognitiveservices-vision-face/HISTORY.rst
  azure-cognitiveservices-vision-face/MANIFEST.in
  azure-cognitiveservices-vision-face/README.rst
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/face_client.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/__init__.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/apply_snapshot_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/apply_snapshot_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/face_attributes.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/face_attributes_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/face_client_enums.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/find_similar_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/find_similar_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/operation_status.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/operation_status_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/snapshot.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/snapshot_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/take_snapshot_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/take_snapshot_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/update_snapshot_request.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/models/update_snapshot_request_py3.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/__init__.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/face_operations.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/snapshot_operations.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/version.py
  azure-cognitiveservices-vision-face/tests/recordings/test_snapshot.yaml
  azure-cognitiveservices-vision-face/tests/test_face.py
Labels: ServicePR

#4499 [AutoPR compute/resource-manager] update description.
  azure-mgmt-compute/MANIFEST.in
  azure-mgmt-compute/README.rst
  azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/os_profile.py
  azure-mgmt-compute/azure/mgmt/compute/v2016_04_30_preview/models/os_profile_py3.py
Labels: RestPRMerged

#4521 [AutoPR eventhub/resource-manager] EventHub: added VNet API to 2017 stable version
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/__init__.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/event_hub_management_client_enums.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/network_rule_set.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/network_rule_set_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_ip_rules.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_ip_rules_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_virtual_network_rules.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_virtual_network_rules_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/subnet.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/subnet_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/operations/namespaces_operations.py
Labels: RestPRMerged

#4533 [AutoPR eventhub/resource-manager] EventHub : corrected typo
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/operations/namespaces_operations.py
Labels: RestPRMerged

#4539 [AutoPR eventhub/resource-manager] EventHub: Revert the NetworkRuleSet
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/__init__.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/event_hub_management_client_enums.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/network_rule_set.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/network_rule_set_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_ip_rules.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_ip_rules_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_virtual_network_rules.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_virtual_network_rules_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/subnet.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/subnet_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/operations/namespaces_operations.py
Labels: RestPRMerged

#4288 [AutoPR] policyinsights/resource-manager
  azure-mgmt-policyinsights/HISTORY.rst
  azure-mgmt-policyinsights/MANIFEST.in
  azure-mgmt-policyinsights/README.rst
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/__init__.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/expression_evaluation_details.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/expression_evaluation_details_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/if_not_exists_evaluation_details.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/if_not_exists_evaluation_details_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_evaluation_details.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_evaluation_details_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_state.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/policy_state_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_options.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/models/query_options_py3.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/operations.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/policy_states_operations.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/version.py
Labels: ReadyforRelease, ServicePR

#4545 [AutoPR edgegateway/resource-manager] Microsoft.DataBoxEdge RP: Corrected comments of trigger and extendedinfo APIs, corrected examples
  azure-mgmt-edgegateway/MANIFEST.in
  azure-mgmt-edgegateway/README.rst
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/data_box_edge_device_extended_info.py
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/data_box_edge_device_extended_info_py3.py
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/periodic_timer_source_info.py
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/periodic_timer_source_info_py3.py
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/operations/devices_operations.py
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/operations/orders_operations.py
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/operations/triggers_operations.py
Labels: RestPRMerged

#4562 [AutoPR monitor/resource-manager] fix package tag for new API version
  azure-mgmt-monitor/azure/mgmt/monitor/models/arm_role_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/arm_role_receiver_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/automation_runbook_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/automation_runbook_receiver_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/azure_function_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/azure_function_receiver_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/email_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/email_receiver_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/logic_app_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/logic_app_receiver_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/webhook_receiver.py
  azure-mgmt-monitor/azure/mgmt/monitor/models/webhook_receiver_py3.py
  azure-mgmt-monitor/azure/mgmt/monitor/operations/action_groups_operations.py
Labels: RestPRMerged

#4561 [AutoPR edgegateway/resource-manager] typo: upto -> up to
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/periodic_timer_source_info.py
  azure-mgmt-edgegateway/azure/mgmt/edgegateway/models/periodic_timer_source_info_py3.py
Labels: RestPRMerged

#4573 [AutoPR graphrbac/data-plane] typo: graphrbac/data-plane/Microsoft.GraphRbac/stable/1.6
  azure-graphrbac/azure/graphrbac/models/application.py
  azure-graphrbac/azure/graphrbac/models/application_base.py
  azure-graphrbac/azure/graphrbac/models/application_base_py3.py
  azure-graphrbac/azure/graphrbac/models/application_create_parameters.py
  azure-graphrbac/azure/graphrbac/models/application_create_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/application_py3.py
  azure-graphrbac/azure/graphrbac/models/application_update_parameters.py
  azure-graphrbac/azure/graphrbac/models/application_update_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/optional_claim.py
  azure-graphrbac/azure/graphrbac/models/optional_claim_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal.py
  azure-graphrbac/azure/graphrbac/models/service_principal_base.py
  azure-graphrbac/azure/graphrbac/models/service_principal_base_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters.py
  azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters.py
  azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters_py3.py
  azure-graphrbac/azure/graphrbac/version.py
Labels: RestPRMerged

#4576 [AutoPR policyinsights/resource-manager] Fix PolicyInsights code generation issue
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/operations.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/operations/policy_states_operations.py
  azure-mgmt-policyinsights/azure/mgmt/policyinsights/version.py
Labels: RestPRMerged

#4524 [AutoPR security/resource-manager] Correlation Key property added
  azure-mgmt-security/README.rst
  azure-mgmt-security/azure/mgmt/security/models/alert.py
  azure-mgmt-security/azure/mgmt/security/models/alert_py3.py
  azure-mgmt-security/azure/mgmt/security/version.py
Labels: RestPRMerged

#4568 Updating DocSettings with Content Verification
  .azure-pipelines/client.yml
  .docsettings.yml
  azure-template/README.md
Labels: EngSys

#4575 [AutoPR search/resource-manager] Add L-Series SKU values to management plane
  azure-mgmt-search/azure/mgmt/search/models/search_management_client_enums.py
  azure-mgmt-search/azure/mgmt/search/models/sku.py
  azure-mgmt-search/azure/mgmt/search/models/sku_py3.py
Labels: RestPRMerged

#4592 [AutoPR iothub/resource-manager] [Hub Generated] Review request for Microsoft.Devices to add version 2018-12-01-preview
  azure-mgmt-iothub/MANIFEST.in
  azure-mgmt-iothub/README.rst
  azure-mgmt-iothub/azure/mgmt/iothub/models/__init__.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/iot_hub_client_enums.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/iot_hub_properties.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/iot_hub_properties_py3.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/operations_monitoring_properties.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/operations_monitoring_properties_py3.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_event_hub_properties.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_event_hub_properties_py3.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_service_bus_queue_endpoint_properties.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_service_bus_queue_endpoint_properties_py3.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_service_bus_topic_endpoint_properties.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_service_bus_topic_endpoint_properties_py3.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_storage_container_properties.py
  azure-mgmt-iothub/azure/mgmt/iothub/models/routing_storage_container_properties_py3.py
Labels: RestPRMerged

#4602 [AutoPR marketplaceordering/resource-manager] [Hub Generated] Review request for Microsoft.MarketplaceOrdering to add version 2015-06-01
  azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/operations/marketplace_agreements_operations.py
  azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/version.py
Labels: RestPRMerged

#4613 [AutoPR graphrbac/data-plane] graph: identifierUris should not be required
  azure-graphrbac/azure/graphrbac/models/application_create_parameters.py
  azure-graphrbac/azure/graphrbac/models/application_create_parameters_py3.py
Labels: RestPRMerged

#4556 [AutoPR netapp/resource-manager] Update to Release 3.5 standard (pre GA)
  azure-mgmt-netapp/azure/mgmt/netapp/models/__init__.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/active_directories.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/active_directories_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/azure_net_app_files_management_client_enums.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/capacity_pool_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/export_policy_rule.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/export_policy_rule_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/mount_target.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/mount_target_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/pools_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/snapshots_operations.py
  azure-mgmt-netapp/azure/mgmt/netapp/version.py
Labels: RestPRMerged

#4540 [AutoPR eventhub/resource-manager] EventHub: Added NetwrokruleSet API
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/__init__.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/event_hub_management_client_enums.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/network_rule_set.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/network_rule_set_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_ip_rules.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_ip_rules_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_virtual_network_rules.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/nw_rule_set_virtual_network_rules_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/subnet.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/models/subnet_py3.py
  azure-mgmt-eventhub/azure/mgmt/eventhub/v2017_04_01/operations/namespaces_operations.py
Labels: RestPRMerged

#4574 [AutoPR] graphrbac/data-plane
  azure-graphrbac/HISTORY.rst
  azure-graphrbac/azure/graphrbac/models/__init__.py
  azure-graphrbac/azure/graphrbac/models/application.py
  azure-graphrbac/azure/graphrbac/models/application_base.py
  azure-graphrbac/azure/graphrbac/models/application_base_py3.py
  azure-graphrbac/azure/graphrbac/models/application_create_parameters.py
  azure-graphrbac/azure/graphrbac/models/application_create_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/application_py3.py
  azure-graphrbac/azure/graphrbac/models/application_update_parameters.py
  azure-graphrbac/azure/graphrbac/models/application_update_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/optional_claim.py
  azure-graphrbac/azure/graphrbac/models/optional_claim_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal.py
  azure-graphrbac/azure/graphrbac/models/service_principal_base.py
  azure-graphrbac/azure/graphrbac/models/service_principal_base_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters.py
  azure-graphrbac/azure/graphrbac/models/service_principal_create_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_object_result.py
  azure-graphrbac/azure/graphrbac/models/service_principal_object_result_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_py3.py
  azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters.py
  azure-graphrbac/azure/graphrbac/models/service_principal_update_parameters_py3.py
  azure-graphrbac/azure/graphrbac/operations/applications_operations.py
  azure-graphrbac/azure/graphrbac/version.py
  azure-graphrbac/tests/recordings/test_graphrbac.test_apps_and_sp.yaml
  azure-graphrbac/tests/test_graphrbac.py
Labels: ServicePR

#4577 [AutoPR containerregistry/resource-manager] [ACR] Update Webhook Event Target Schema to Add Name and Version
  azure-mgmt-containerregistry/MANIFEST.in
  azure-mgmt-containerregistry/README.rst
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/target.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2017_10_01/models/target_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/target.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_02_01_preview/models/target_py3.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/target.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/target_py3.py
Labels: RestPRMerged

#4570 [AutoPR datafactory/resource-manager] Update the public swagger by reference to private swagger
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_lake_store_cosmos_structured_stream_dataset.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_lake_store_cosmos_structured_stream_dataset_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_lake_store_dataset.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/azure_data_lake_store_dataset_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/custom_dataset.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/custom_dataset_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/dataset.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/dataset_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/oracle_table_dataset.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/oracle_table_dataset_py3.py
Labels: RestPRMerged

#4534 [AutoPR servicebus/resource-manager] Servicebus : NetworkruleSet
  azure-mgmt-servicebus/MANIFEST.in
  azure-mgmt-servicebus/README.rst
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/__init__.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/network_rule_set.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/network_rule_set_py3.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/nw_rule_set_ip_rules.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/nw_rule_set_ip_rules_py3.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/nw_rule_set_virtual_network_rules.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/nw_rule_set_virtual_network_rules_py3.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/service_bus_management_client_enums.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/subnet.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/models/subnet_py3.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/operations/namespaces_operations.py
  azure-mgmt-servicebus/azure/mgmt/servicebus/version.py
Labels: RestPRMerged

#4547 [AutoPR azure-kusto/resource-manager] Kusto: Suppress R2016 warning
  azure-mgmt-kusto/MANIFEST.in
  azure-mgmt-kusto/azure/mgmt/kusto/version.py
Labels: RestPRMerged

#4620 [AutoPR storage/resource-manager] [Storage] Add a new return code to Create Container
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/operations/blob_containers_operations.py
Labels: RestPRMerged

#4624 [AutoPR frontdoor/resource-manager] Update FrontDoor WAF API with new preview features (2019-03-01)
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/front_door_management_client.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/__init__.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_override_rule_group.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_override_rule_group_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_rule_set.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/azure_managed_rule_set_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_rule.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_rule_list.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_rule_list_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_rule_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/front_door_management_client_enums.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/frontend_endpoint_link.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/frontend_endpoint_link_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_definition.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_definition_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_group_definition.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_group_definition_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_group_override.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_group_override_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_override.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_override_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set_definition.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set_definition_paged.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set_definition_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set_list.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set_list_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/managed_rule_set_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/match_condition.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/match_condition_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/policy_settings.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/policy_settings_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/web_application_firewall_policy.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/web_application_firewall_policy_paged.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/web_application_firewall_policy_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/__init__.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/managed_rule_sets_operations.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/policies_operations.py
Labels: RestPRMerged

#4640 [AutoPR containerregistry/resource-manager] [ACR] Add Readonly RunErrorMessage to RunProperties
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/run.py
  azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2018_09_01/models/run_py3.py
Labels: RestPRMerged

#4648 [AutoPR storage/resource-manager] Added feature revoke user delegation key
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/operations/storage_accounts_operations.py
Labels: RestPRMerged

#4638 [AutoPR netapp/resource-manager] Small correction to list handling
  azure-mgmt-netapp/azure/mgmt/netapp/models/__init__.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/active_directory.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/active_directory_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/net_app_account_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_properties_export_policy.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_properties_export_policy_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_patch_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_properties_export_policy.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_properties_export_policy_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/models/volume_py3.py
  azure-mgmt-netapp/azure/mgmt/netapp/operations/accounts_operations.py
Labels: RestPRMerged

#4654 [AutoPR adhybridhealthservice/resource-manager] New operations for adhealth
  azure-mgmt-adhybridhealthservice/README.rst
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/__init__.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/connector_metadata.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/connector_metadata_details.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/connector_metadata_details_py3.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/connector_metadata_py3.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/operations/service_members_operations.py
Labels: RestPRMerged

#4652 [AutoPR graphrbac/data-plane] typo: informations -> information about
  azure-graphrbac/azure/graphrbac/models/application.py
  azure-graphrbac/azure/graphrbac/models/application_base.py
  azure-graphrbac/azure/graphrbac/models/application_base_py3.py
  azure-graphrbac/azure/graphrbac/models/application_create_parameters.py
  azure-graphrbac/azure/graphrbac/models/application_create_parameters_py3.py
  azure-graphrbac/azure/graphrbac/models/application_py3.py
  azure-graphrbac/azure/graphrbac/models/application_update_parameters.py
  azure-graphrbac/azure/graphrbac/models/application_update_parameters_py3.py
  azure-graphrbac/azure/graphrbac/version.py
Labels: RestPRMerged

#4615 [AutoPR] marketplaceordering/resource-manager
  azure-mgmt-marketplaceordering/HISTORY.rst
  azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/operations/marketplace_agreements_operations.py
  azure-mgmt-marketplaceordering/azure/mgmt/marketplaceordering/version.py
Labels: ReadyforRelease, ServicePR

#4667 [AutoPR compute/resource-manager] Add Disk 2018-09 to Python
  azure-mgmt-compute/azure/mgmt/compute/compute_management_client.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/__init__.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/compute_management_client.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/__init__.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/access_uri.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/access_uri_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/compute_management_client_enums.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/creation_data.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/creation_data_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/disk.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/disk_paged.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/disk_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/disk_sku.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/disk_sku_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/disk_update.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/disk_update_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/encryption_settings_collection.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/encryption_settings_collection_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/encryption_settings_element.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/encryption_settings_element_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/grant_access_data.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/grant_access_data_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/image_disk_reference.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/image_disk_reference_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/key_vault_and_key_reference.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/key_vault_and_key_reference_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/key_vault_and_secret_reference.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/key_vault_and_secret_reference_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/resource.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/resource_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/snapshot.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/snapshot_paged.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/snapshot_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/snapshot_sku.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/snapshot_sku_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/snapshot_update.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/snapshot_update_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/source_vault.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/source_vault_py3.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/operations/__init__.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/operations/disks_operations.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/operations/snapshots_operations.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/version.py
Labels: RestPRMerged

#4641 [AutoPR managedservices/resource-manager] add python readme
  azure-mgmt-managedservices/HISTORY.rst
  azure-mgmt-managedservices/MANIFEST.in
  azure-mgmt-managedservices/README.rst
  azure-mgmt-managedservices/azure/__init__.py
  azure-mgmt-managedservices/azure/mgmt/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/managed_services_client.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/authorization.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/authorization_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_error.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_error_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/error_response_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/managed_services_client_enums.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_display.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_display_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_list.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_list_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/operation_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/plan.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/plan_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_paged.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_properties_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_properties_registration_definition_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_assignment_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_paged.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_properties_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/models/registration_definition_py3.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/__init__.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/operations.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_assignments_operations.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/operations/registration_definitions_operations.py
  azure-mgmt-managedservices/azure/mgmt/managedservices/version.py
  azure-mgmt-managedservices/sdk_packaging.toml
  azure-mgmt-managedservices/setup.cfg
  azure-mgmt-managedservices/setup.py
Labels: RestPRMerged

#4655 [AutoPR consumption/resource-manager] typo: consumption/resource-manager/Microsoft.Consumption
  azure-mgmt-consumption/azure/mgmt/consumption/models/enrollment.py
  azure-mgmt-consumption/azure/mgmt/consumption/models/enrollment_py3.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/charges_by_billing_account_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/charges_by_billing_profile_operations.py
  azure-mgmt-consumption/azure/mgmt/consumption/operations/charges_by_invoice_section_operations.py
Labels: RestPRMerged

#4572 [AutoPR alertsmanagement/resource-manager] Swagger Changes For Alerts and Alerts Summary as extension resources
  azure-mgmt-alertsmanagement/MANIFEST.in
  azure-mgmt-alertsmanagement/README.rst
  azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/version.py
Labels: RestPRMerged

#4682 [AutoPR frontdoor/resource-manager] Stable release of Front door API
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/front_door_management_client.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/__init__.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/backend.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/backend_pools_settings.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/backend_pools_settings_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/backend_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/forwarding_configuration.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/forwarding_configuration_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/front_door.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/front_door_management_client_enums.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/front_door_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/front_door_update_parameters.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/front_door_update_parameters_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/redirect_configuration.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/redirect_configuration_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/route_configuration.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/route_configuration_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/routing_rule.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/routing_rule_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/routing_rule_update_parameters.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/routing_rule_update_parameters_py3.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/backend_pools_operations.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/endpoints_operations.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/front_doors_operations.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/frontend_endpoints_operations.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/health_probe_settings_operations.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/load_balancing_settings_operations.py
  azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/routing_rules_operations.py
Labels: RestPRMerged

#4690 [AutoPR cognitiveservices/data-plane/TranslatorText] typo: cognitiveservices/data-plane/TranslatorText
  azure-cognitiveservices-translatortext/MANIFEST.in
  azure-cognitiveservices-translatortext/README.rst
  azure-cognitiveservices-translatortext/azure/cognitiveservices/translatortext/operations/translator_operations.py
Labels: RestPRMerged

#4619 [AutoPR resourcegraph/resource-manager] [Hub Generated] Review request for Microsoft.ResourceGraph to add version 2019-04-01
  azure-mgmt-resourcegraph/MANIFEST.in
  azure-mgmt-resourcegraph/README.rst
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/operations/operations.py
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/resource_graph_client.py
Labels: RestPRMerged

#4675 [AutoPR datafactory/resource-manager] Webhook activity
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/control_activity_py3.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/data_factory_management_client_enums.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/web_hook_activity.py
  azure-mgmt-datafactory/azure/mgmt/datafactory/models/web_hook_activity_py3.py
Labels: RestPRMerged

#4687 [AutoPR billing/resource-manager] fix: billing/resource-manager/Microsoft.Billing
  azure-mgmt-billing/azure/mgmt/billing/models/product_details.py
  azure-mgmt-billing/azure/mgmt/billing/models/product_details_py3.py
  azure-mgmt-billing/azure/mgmt/billing/models/transfer_details.py
  azure-mgmt-billing/azure/mgmt/billing/models/transfer_details_py3.py
Labels: RestPRMerged

#4677 [AutoPR blueprint/resource-manager] Blueprints API update for excludePrincipals and whoIsBlueprint
  azure-mgmt-blueprint/MANIFEST.in
  azure-mgmt-blueprint/README.rst
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/__init__.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_lock_settings.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/assignment_lock_settings_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_management_client_enums.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/blueprint_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/published_blueprint.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/published_blueprint_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/who_is_blueprint_contract.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/models/who_is_blueprint_contract_py3.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/artifacts_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/assignment_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/assignments_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/blueprints_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/published_artifacts_operations.py
  azure-mgmt-blueprint/azure/mgmt/blueprint/operations/published_blueprints_operations.py
Labels: RestPRMerged

#4688 [AutoPR cognitiveservices/data-plane/Face] typo: cognitiveservices/data-plane/Face/stable/v1
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/large_face_list_operations.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/large_person_group_operations.py
  azure-cognitiveservices-vision-face/azure/cognitiveservices/vision/face/operations/person_group_operations.py
Labels: RestPRMerged

#4700 [AutoPR adhybridhealthservice/resource-manager] typo: adhybridhealthservice/resource-manager/Microsoft.ADHybridHealthService
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/risky_ip_blob_uri.py
  azure-mgmt-adhybridhealthservice/azure/mgmt/adhybridhealthservice/models/risky_ip_blob_uri_py3.py
Labels: RestPRMerged

#4719 [AutoPR resourcegraph/resource-manager] add resourcegraph to Go SDK
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/version.py
Labels: RestPRMerged

#3744 [AutoPR] resourcegraph/resource-manager
  azure-mgmt-resourcegraph/HISTORY.rst
  azure-mgmt-resourcegraph/MANIFEST.in
  azure-mgmt-resourcegraph/README.rst
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/facet_request_options.py
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/models/facet_request_options_py3.py
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/operations/operations.py
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/resource_graph_client.py
  azure-mgmt-resourcegraph/azure/mgmt/resourcegraph/version.py
  azure-mgmt-resourcegraph/tests/recordings/test_mgmt_resourcegraph.test_resources_basic_query.yaml
  azure-mgmt-resourcegraph/tests/recordings/test_mgmt_resourcegraph.test_resources_facet_query.yaml
  azure-mgmt-resourcegraph/tests/recordings/test_mgmt_resourcegraph.test_resources_malformed_query.yaml
  azure-mgmt-resourcegraph/tests/recordings/test_mgmt_resourcegraph.test_resources_query_options.yaml
Labels: ServicePR

#4723 [AutoPR compute/resource-manager] Adding doNotRunExtensionsOnOverprovisionedVMs property to swagger
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/__init__.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_09_30/models/compute_management_client_enums.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set.py
  azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/models/virtual_machine_scale_set_py3.py
Labels: RestPRMerged

#4673 [AutoPR hanaonazure/resource-manager] [Hub Generated] Review request for Microsoft.HanaOnAzure to add version 2017-11-03-preview
  azure-mgmt-hanaonazure/MANIFEST.in
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/hana_management_client.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/__init__.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/hana_management_client_enums.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/monitoring_details.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/monitoring_details_py3.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/__init__.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/operations/monitoring_operations.py
  azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: RestPRMerged

#4715 [AutoPR netapp/resource-manager] Updating NetApp readme to include Java
  azure-mgmt-netapp/azure/mgmt/netapp/version.py
Labels: RestPRMerged

#4729 [AutoPR storagesync/resource-manager] added java readme to storage sync readme
  azure-mgmt-storagesync/azure/mgmt/storagesync/version.py
Labels: RestPRMerged

#4720 [AutoPR applicationinsights/resource-manager] [App Insights control plane] fix: validate subId, apiVersion, rgName
  azure-mgmt-applicationinsights/MANIFEST.in
  azure-mgmt-applicationinsights/README.rst
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/application_insights_management_client.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/analytics_items_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/annotations_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/api_keys_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_available_features_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_current_billing_features_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_feature_capabilities_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/component_quota_status_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/components_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/export_configurations_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/favorites_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/proactive_detection_configurations_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_test_locations_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/web_tests_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/work_item_configurations_operations.py
  azure-mgmt-applicationinsights/azure/mgmt/applicationinsights/operations/workbooks_operations.py
Labels: RestPRMerged

#4693 [AutoPR storage/resource-manager] [DO NOT REVIEW/MERGE] Swagger for Lease Container API from Oct17 to latest
  azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/__init__.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/lease_container_request.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/lease_container_request_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/lease_container_response.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/models/lease_container_response_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_02_01/operations/blob_containers_operations.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/__init__.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/lease_container_request.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/lease_container_request_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/lease_container_response.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/models/lease_container_response_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_03_01_preview/operations/blob_containers_operations.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/__init__.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/lease_container_request.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/lease_container_request_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/lease_container_response.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/models/lease_container_response_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_07_01/operations/blob_containers_operations.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/models/__init__.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/models/lease_container_request.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/models/lease_container_request_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/models/lease_container_response.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/models/lease_container_response_py3.py
  azure-mgmt-storage/azure/mgmt/storage/v2018_11_01/operations/blob_containers_operations.py
Labels: RestPRMerged
