Repository Azure/azure-sdk-for-python, pull requests merged in 2019-08, with the labels that each got.

#6502 [AutoPR reservations/resource-manager] [Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models_py3.py
Labels: RestPRMerged

#6464 Implement synchronous device code credential
  sdk/identity/azure-identity/azure/identity/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/__init__.py
  sdk/identity/azure-identity/azure/identity/_internal/exception_wrapper.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
  sdk/identity/azure-identity/azure/identity/browser_auth.py
  sdk/identity/azure-identity/azure/identity/credentials.py
  sdk/identity/azure-identity/setup.py
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/identity/azure-identity/tests/test_identity_async.py
Labels: Azure.Identity, Client

#6569 [AutoPR sql/resource-manager] fix: Microsoft.Sql/stable/2014-04-01 model validation
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/database_blob_auditing_policy_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_database_blob_auditing_policy_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/extended_server_blob_auditing_policy_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/server_blob_auditing_policy_py3.py
Labels: RestPRMerged

#6574 [AutoPR alertsmanagement/resource-manager] fixing subscription id issue
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/HISTORY.rst
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/_alerts_management_client.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/_configuration.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_action_rules_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_alerts_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_smart_detector_alert_rules_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/operations/_smart_groups_operations.py
  sdk/alertsmanagement/azure-mgmt-alertsmanagement/azure/mgmt/alertsmanagement/version.py
Labels: RestPRMerged

#6603 Remove Configuration from public API
  sdk/identity/azure-identity/azure/identity/_authn_client.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py
  sdk/identity/azure-identity/azure/identity/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/_authn_client.py
  sdk/identity/azure-identity/azure/identity/aio/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/credentials.py
  sdk/identity/azure-identity/azure/identity/credentials.py
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/identity/azure-identity/tests/test_identity_async.py
Labels: Azure.Identity, Client

#6590 Mypy fixes
  sdk/core/azure-core/azure/core/tracing/abstract_span.py
  sdk/core/azure-core/azure/core/tracing/common.py
  sdk/core/azure-core/azure/core/tracing/context.py
  sdk/core/azure-core/azure/core/tracing/decorator.py
  sdk/core/azure-core/azure/core/tracing/decorator_async.py
  sdk/core/azure-core/azure/core/tracing/ext/opencensus_span.py
  sdk/core/azure-core/tests/test_tracing_context.py
  sdk/core/azure-core/tests/test_tracing_decorator.py
Labels: Azure.Core, Client

#6512 [AutoPR compute/resource-manager] Add missing Gallery Application API in 2019-07-01 version
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machine_scale_set_vms_operations.py
Labels: RestPRMerged

#6640 Update Key Vault user agent
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/__init__.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/aio/client.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/client.py
Labels: Client, KeyVault

#6641 mypy fixes
  sdk/core/azure-core/azure/core/pipeline/policies/distributed_tracing.py
  sdk/core/azure-core/azure/core/tracing/context.py
Labels: Azure.Core, Client

#6645 seed tests.yml file
  sdk/storage/tests.yml
Labels: EngSys

#6532 [AutoPR cognitiveservices/data-plane/InkRecognizer] [Hub Generated] Review request for InkRecognizer to add version preview/v1.0
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/HISTORY.rst
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/MANIFEST.in
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/README.rst
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/_ink_recognizer_client.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/models/_ink_recognizer_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/models/_models_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/operations/_ink_recognizer_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/azure/cognitiveservices/inkrecognizer/version.py
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/sdk_packaging.toml
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/setup.cfg
  sdk/cognitiveservices/azure-cognitiveservices-inkrecognizer/setup.py
Labels: RestPRMerged

#6652 [AutoPR healthcareapis/resource-manager] Fixed healthcareapi readme.md
  sdk/healthcareapis/azure-mgmt-healthcareapis/HISTORY.rst
  sdk/healthcareapis/azure-mgmt-healthcareapis/MANIFEST.in
  sdk/healthcareapis/azure-mgmt-healthcareapis/README.rst
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/__init__.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/__init__.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/__init__.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/_configuration.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/_healthcare_apis_management_client.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/__init__.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_healthcare_apis_management_client_enums.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models_py3.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_paged_models.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/__init__.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operation_results_operations.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operations.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_services_operations.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/version.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/sdk_packaging.toml
  sdk/healthcareapis/azure-mgmt-healthcareapis/setup.cfg
  sdk/healthcareapis/azure-mgmt-healthcareapis/setup.py
Labels: RestPRInProgress

#6659 [AutoPR subscription/resource-manager] chore: jsonfmt subscription
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/error_response.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/error_response_py3.py
Labels: RestPRMerged

#6664 Final azure-identity preview 2 changes
  sdk/identity/azure-identity/HISTORY.md
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/azure/identity/__init__.py
  sdk/identity/azure-identity/azure/identity/_authn_client.py
  sdk/identity/azure-identity/azure/identity/_base.py
  sdk/identity/azure-identity/azure/identity/_browser_auth.py
  sdk/identity/azure-identity/azure/identity/_constants.py
  sdk/identity/azure-identity/azure/identity/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/_version.py
  sdk/identity/azure-identity/azure/identity/aio/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/_managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/credentials.py
  sdk/identity/azure-identity/azure/identity/credentials.py
  sdk/identity/azure-identity/conftest.py
  sdk/identity/azure-identity/setup.py
  sdk/identity/azure-identity/tests/test_identity.py
  sdk/identity/azure-identity/tests/test_identity_async.py
  sdk/identity/azure-identity/tests/test_live_async.py
  sdk/identity/azure-identity/tests/test_managed_identity.py
  sdk/identity/azure-identity/tests/test_managed_identity_async.py
  sdk/keyvault/azure-keyvault-keys/setup.py
  sdk/keyvault/azure-keyvault-secrets/setup.py
  sdk/storage/azure-storage-blob/setup.py
  sdk/storage/azure-storage-file/setup.py
  sdk/storage/azure-storage-queue/setup.py
  shared_requirements.txt
Labels: Azure.Identity, Client

#6658 [storage] Preview2 updates
  sdk/storage/azure-storage-blob/HISTORY.md
  sdk/storage/azure-storage-blob/azure/storage/blob/version.py
  sdk/storage/azure-storage-blob/tests/test_blob_client.py
  sdk/storage/azure-storage-blob/tests/test_blob_client_async.py
  sdk/storage/azure-storage-file/HISTORY.md
  sdk/storage/azure-storage-file/azure/storage/file/_polling.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/_polling_async.py
  sdk/storage/azure-storage-file/azure/storage/file/version.py
  sdk/storage/azure-storage-file/tests/test_file_async.py
  sdk/storage/azure-storage-file/tests/test_file_client.py
  sdk/storage/azure-storage-file/tests/test_file_client_async.py
  sdk/storage/azure-storage-queue/HISTORY.md
  sdk/storage/azure-storage-queue/azure/storage/queue/version.py
  sdk/storage/azure-storage-queue/tests/test_queue_client.py
  sdk/storage/azure-storage-queue/tests/test_queue_client_async.py
Labels: Storage

#6672 [AutoPR datamigration/resource-manager] Fix incorrect discriminator for Oracle to PostgreSQL scenario
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/__init__.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_data_migration_service_client_enums.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Labels: RestPRMerged

#6543 [AutoPR] containerregistry/resource-manager
  sdk/containerregistry/azure-mgmt-containerregistry/HISTORY.rst
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/_container_registry_management_client.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/version.py
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_classic_registry.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_managed_registry.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_replication.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry.test_webhook.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry_2017_03_01.test_basic_registry.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry_2018_02_01_preview.test_build.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry_2018_02_01_preview.test_build_step.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry_2018_02_01_preview.test_build_task.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry_2018_02_01_preview.test_managed_registry.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry_2018_02_01_preview.test_replication.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/recordings/test_mgmt_containerregistry_2018_02_01_preview.test_webhook.yaml
  sdk/containerregistry/azure-mgmt-containerregistry/tests/test_mgmt_containerregistry.py
  sdk/containerregistry/azure-mgmt-containerregistry/tests/test_mgmt_containerregistry_2017_03_01.py
  sdk/containerregistry/azure-mgmt-containerregistry/tests/test_mgmt_containerregistry_2018_02_01_preview.py
Labels: ServicePR

#5532 [AutoPR] signalr/resource-manager
  sdk/signalr/azure-mgmt-signalr/HISTORY.rst
  sdk/signalr/azure-mgmt-signalr/README.rst
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/__init__.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/resource_sku_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcors_settings.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcors_settings_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rcreate_or_update_properties_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rfeature.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rfeature_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/models/signal_rresource_py3.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/operations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/signal_roperations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/operations/usages_operations.py
  sdk/signalr/azure-mgmt-signalr/azure/mgmt/signalr/version.py
  sdk/signalr/azure-mgmt-signalr/setup.py
Labels: ServicePR

#6668 Key Vault 4.0.0b2 updates
  sdk/identity/azure-identity/HISTORY.md
  sdk/keyvault/azure-keyvault-keys/HISTORY.md
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_list.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_list_deleted_keys.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_list_versions.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_purge.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_recover.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_list.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_key_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_list_deleted_keys.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_list_versions.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_purge.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_keys_async.test_recover.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_key_list_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_keys_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys.test_example_keys_recover.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_key_crud_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_key_list_operations.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_keys_backup_restore.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_samples_keys_async.test_example_keys_recover.yaml
  sdk/keyvault/azure-keyvault-secrets/HISTORY.md
  sdk/keyvault/azure-keyvault-secrets/README.md
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_version.py
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets.test_example_secret_crud_operations.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets.test_example_secret_list_operations.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets.test_example_secrets_backup_restore.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets.test_example_secrets_recover.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets_async.test_example_secret_crud_operations.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets_async.test_example_secret_list_operations.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets_async.test_example_secrets_backup_restore.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_samples_secrets_async.test_example_secrets_recover.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_async.test_backup_restore.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_async.test_list_deleted_secrets.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_async.test_list_versions.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_async.test_purge.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_async.test_recover.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_async.test_secret_crud_operations.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_async.test_secret_list.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_backup_restore.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_list_deleted_secrets.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_list_versions.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_purge.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_recover.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_secret_crud_operations.yaml
  sdk/keyvault/azure-keyvault-secrets/tests/recordings/test_secrets_client.test_secret_list.yaml
Labels: Client, KeyVault

#6082 [AutoPR] hdinsight/resource-manager
  sdk/hdinsight/azure-mgmt-hdinsight/HISTORY.rst
  sdk/hdinsight/azure-mgmt-hdinsight/README.rst
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/__init__.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_hd_insight_management_client_enums.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/models/_models_py3.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/operations/_locations_operations.py
  sdk/hdinsight/azure-mgmt-hdinsight/azure/mgmt/hdinsight/version.py
  sdk/hdinsight/azure-mgmt-hdinsight/setup.py
Labels: ServicePR

#6702 Update documented modules
  doc/sphinx/ref/azure.identity.rst
  doc/sphinx/ref/azure.keyvault.secrets.aio.rst
  doc/sphinx/ref/azure.keyvault.secrets.rst
Labels: Azure.Identity, Client, Docs, KeyVault

#6537 CryptographyClient implemented with service calls
  doc/sphinx/ref/azure.keyvault.key_vault_id.rst
  doc/sphinx/ref/azure.keyvault.keys.aio.rst
  doc/sphinx/ref/azure.keyvault.keys.crypto.aio.rst
  doc/sphinx/ref/azure.keyvault.keys.crypto.rst
  doc/sphinx/ref/azure.keyvault.keys.rst
  sdk/keyvault/azure-keyvault-keys/HISTORY.md
  sdk/keyvault/azure-keyvault-keys/README.md
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/__init__.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/__init__.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/enums.py
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_encrypt_and_decrypt.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_sign_and_verify.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client.test_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_encrypt_and_decrypt.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_sign_and_verify.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_crypto_client_async.test_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto.test_encrypt_decrypt.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto.test_sign_verify.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto.test_wrap_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto_async.test_encrypt_decrypt_async.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto_async.test_sign_verify_async.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_examples_crypto_async.test_wrap_unwrap_async.yaml
  sdk/keyvault/azure-keyvault-keys/tests/recordings/test_key_client.test_key_wrap_and_unwrap.yaml
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
  sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto.py
  sdk/keyvault/azure-keyvault-keys/tests/test_examples_crypto_async.py
  sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
Labels: Client, KeyVault

#6706 EventHub Preview2 sphinx update
  doc/sphinx/ref/azure.eventhub.eventprocessor.rst
  doc/sphinx/ref/azure.eventhub.rst
  doc/sphinx/ref/azure.eventprocessorhost.rst
  doc/sphinx/ref/azure.eventprocessorhost.vendor.rst
  doc/sphinx/ref/azure.eventprocessorhost.vendor.storage.blob.rst
  doc/sphinx/ref/azure.eventprocessorhost.vendor.storage.common.rst
  doc/sphinx/ref/azure.eventprocessorhost.vendor.storage.rst
Labels: Client, Event Hubs

#6707 [AutoPR datamigration/resource-manager] Added "caseManipulation" to MigrateOracleAzureDbPostgreSqlSyncDatabaseInput object
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models.py
  sdk/datamigration/azure-mgmt-datamigration/azure/mgmt/datamigration/models/_models_py3.py
Labels: RestPRMerged

#6683 [AutoPR consumption/resource-manager] chore: jsonfmt consumption
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/_consumption_management_client.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/__init__.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_consumption_management_client_enums.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/models/_models_py3.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_aggregated_cost_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_balances_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_budgets_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_charges_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_forecasts_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_marketplaces_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_price_sheet_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservation_recommendations_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_details_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_reservations_summaries_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_tags_operations.py
  sdk/consumption/azure-mgmt-consumption/azure/mgmt/consumption/operations/_usage_details_operations.py
Labels: RestPRMerged

#6721 [AutoPR frontdoor/resource-manager] Update readme.md files missed from previous commit - switching API version to 2019-05-01
  sdk/network/azure-mgmt-frontdoor/README.rst
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/front_door_management_client.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/__init__.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/backend_pools_settings.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/backend_pools_settings_py3.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_https_configuration.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/custom_https_configuration_py3.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/front_door_management_client_enums.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/health_probe_settings_model.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/health_probe_settings_model_py3.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/health_probe_settings_update_parameters.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/models/health_probe_settings_update_parameters_py3.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/backend_pools_operations.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/endpoints_operations.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/front_doors_operations.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/frontend_endpoints_operations.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/health_probe_settings_operations.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/load_balancing_settings_operations.py
  sdk/network/azure-mgmt-frontdoor/azure/mgmt/frontdoor/operations/routing_rules_operations.py
  sdk/network/azure-mgmt-frontdoor/setup.py
Labels: RestPRMerged

#6735 [AutoPR storage/resource-manager] [SRP] Add Support for File Service and File Shares
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/_storage_management_client.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/_storage_management_client.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/__init__.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/models/_models_py3.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/__init__.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_file_services_operations.py
  sdk/storage/azure-mgmt-storage/azure/mgmt/storage/v2019_04_01/operations/_file_shares_operations.py
Labels: RestPRMerged

#6728 Async blob code samples
  sdk/storage/azure-storage-blob/README.md
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_service_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/lease_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/blob_service_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/lease.py
  sdk/storage/azure-storage-blob/tests/recordings/test_blob_samples_common.test_start_copy_blob_from_url_and_abort_copy.yaml
  sdk/storage/azure-storage-blob/tests/test_blob_samples_authentication_async.py
  sdk/storage/azure-storage-blob/tests/test_blob_samples_common.py
  sdk/storage/azure-storage-blob/tests/test_blob_samples_common_async.py
  sdk/storage/azure-storage-blob/tests/test_blob_samples_containers_async.py
  sdk/storage/azure-storage-blob/tests/test_blob_samples_hello_world_async.py
  sdk/storage/azure-storage-blob/tests/test_blob_samples_service_async.py
Labels: Storage

#6750 Adding storage docs
  doc/sphinx/ref/azure.storage.blob.aio.rst
  doc/sphinx/ref/azure.storage.blob.rst
  doc/sphinx/ref/azure.storage.file.aio.rst
  doc/sphinx/ref/azure.storage.file.rst
  doc/sphinx/ref/azure.storage.queue.aio.rst
  doc/sphinx/ref/azure.storage.queue.rst
Labels: Storage

#5633 [AutoPR azure-kusto/resource-manager] Updating the skus names and clarified capacity description
  sdk/kusto/azure-mgmt-kusto/MANIFEST.in
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/__init__.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_capacity.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_capacity_py3.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_resource_sku.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_resource_sku_py3.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_sku.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/azure_sku_py3.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/check_name_result.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/check_name_result_py3.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/data_connection_check_name_request.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/data_connection_check_name_request_py3.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/models/kusto_management_client_enums.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/operations/data_connections_operations.py
  sdk/kusto/azure-mgmt-kusto/azure/mgmt/kusto/version.py
  sdk/kusto/azure-mgmt-kusto/setup.py
Labels: RestPRMerged

#6768 Eventhubs fix typing
  sdk/eventhub/azure-eventhubs/README.md
Labels: Client, Event Hubs

#6769 Python Smoke Test Pipeline
  eng/pipelines/smoke-test.yml
Labels: EngSys

#6780 Add sphinx extension for kwargs
  doc/sphinx/conf.py
Labels: Docs, EngSys

#6726 [AutoPR subscription/resource-manager] [DO NOT MERGE] Enable API swagger
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/__init__.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/enabled_subscription_id.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/enabled_subscription_id_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/subscriptions_operations.py
Labels: RestPRMerged

#6722 [AutoPR cognitiveservices/data-plane/QnAMaker] fix schema property naming
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/_qn_amaker_runtime_client.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/_models_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/_qn_amaker_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/models/_qn_amaker_runtime_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/operations/_runtime_operations.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/runtime/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/runtime/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/runtime/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/runtime/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/runtime/models/_models_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/runtime/operations/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-knowledge-qnamaker/azure/cognitiveservices/knowledge/qnamaker/runtime/version.py
Labels: RestPRMerged

#6771 [AutoPR resources/resource-manager] Revert the changes for 2019-07-01/Microsoft.Resources.
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_07_01/models/_models.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_07_01/models/_models_py3.py
  sdk/resources/azure-mgmt-resource/azure/mgmt/resource/resources/v2019_07_01/operations/_deployments_operations.py
Labels: RestPRMerged

#6795 [AutoPR datafactory/resource-manager] [DataFactory] Event Trigger Subscription APIs
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/operations/_triggers_operations.py
Labels: RestPRMerged

#6636 [AutoPR hanaonazure/resource-manager] Adding managed resource group and log Analytics Workspace to the GET API
  sdk/hanaonazure/azure-mgmt-hanaonazure/HISTORY.rst
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models_py3.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/version.py
Labels: RestPRMerged

#6800 [AutoPR datafactory/resource-manager] chore: jsonfmt datafactory
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_data_factory_management_client_enums.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Labels: RestPRMerged

#6630 [AutoPR sql/resource-manager] Add managedInstaceAdministrators.json to readme file, which reprepres…
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/__init__.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_administrator.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_administrator_paged.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/models/managed_instance_administrator_py3.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/__init__.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/operations/managed_instance_administrators_operations.py
  sdk/sql/azure-mgmt-sql/azure/mgmt/sql/sql_management_client.py
Labels: RestPRMerged

#6815 [AutoPR datafactory/resource-manager] [Data Factory] Refactor table option
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Labels: RestPRMerged

#6832 [AutoPR datafactory/resource-manager] [Data Factory]Add property blockSizeInMB for AzureBlobStorageWriteSettings and AzureBlobFSWriteSettings
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Labels: RestPRMerged

#6772 [storage] Fix for Files upload return type
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads.py
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared/uploads_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_service_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/lease_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
  sdk/storage/azure-storage-blob/tests/test_container.py
  sdk/storage/azure-storage-file/azure/storage/file/_shared/uploads.py
  sdk/storage/azure-storage-file/azure/storage/file/_shared/uploads_async.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/file_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/file_client.py
  sdk/storage/azure-storage-file/tests/test_file.py
  sdk/storage/azure-storage-file/tests/test_file_async.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/uploads_async.py
Labels: Storage

#6876 [AutoPR hanaonazure/resource-manager] Added Key Vault ID for GET and LIST SapMonitor
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models.py
  sdk/hanaonazure/azure-mgmt-hanaonazure/azure/mgmt/hanaonazure/models/_models_py3.py
Labels: RestPRMerged

#6874 More Cosmos Pylint work
  sdk/cosmos/azure-cosmos/azure/cosmos/_base.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_default_retry_policy.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_endpoint_discovery_retry_policy.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/base_execution_context.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/document_producer.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/endpoint_component.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_global_endpoint_manager.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_location_cache.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_retry_options.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_retry_utility.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_routing/collection_routing_map.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_routing/routing_map_provider.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_session.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_session_retry_policy.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_synchronized_request.py
  sdk/cosmos/azure-cosmos/azure/cosmos/auth.py
  sdk/cosmos/azure-cosmos/azure/cosmos/container.py
  sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
  sdk/cosmos/azure-cosmos/azure/cosmos/database.py
  sdk/cosmos/azure-cosmos/azure/cosmos/documents.py
  sdk/cosmos/azure-cosmos/azure/cosmos/http_constants.py
  sdk/cosmos/azure-cosmos/azure/cosmos/partition_key.py
  sdk/cosmos/azure-cosmos/azure/cosmos/permission.py
  sdk/cosmos/azure-cosmos/azure/cosmos/scripts.py
  sdk/cosmos/azure-cosmos/azure/cosmos/user.py
Labels: Cosmos

#5748 [AutoPR] subscription/resource-manager
  sdk/subscription/azure-mgmt-subscription/HISTORY.rst
  sdk/subscription/azure-mgmt-subscription/README.rst
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/__init__.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/_configuration.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/_subscription_client.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/__init__.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/_models.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/_models_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/_paged_models.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/_subscription_client_enums.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/canceled_subscription_id.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/canceled_subscription_id_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/error_response.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/error_response_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/location.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/location_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/operation.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/operation_display.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/operation_display_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/operation_list_result.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/operation_list_result_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/operation_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/renamed_subscription_id.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/renamed_subscription_id_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/subscription.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_client_enums.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_name.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_name_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_policies.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_policies_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/subscription_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/tenant_id_description.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/tenant_id_description_paged.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/models/tenant_id_description_py3.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/__init__.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_subscription_factory_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_subscription_operation_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_subscription_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_subscriptions_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/operations/_tenants_operations.py
  sdk/subscription/azure-mgmt-subscription/azure/mgmt/subscription/version.py
  sdk/subscription/azure-mgmt-subscription/setup.py
Labels: ServicePR

#6905 [AutoPR cognitiveservices/data-plane/ComputerVision] Add CV API v2.1 for gore support
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/_computer_vision_client.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/_configuration.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/__init__.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_computer_vision_client_enums.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_models.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/models/_models_py3.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/azure/cognitiveservices/vision/computervision/operations/_computer_vision_client_operations.py
Labels: RestPRMerged

#6891 [AutoPR machinelearningservices/resource-manager] [Do Not Merge] SSH and Quota changes
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/_azure_machine_learning_workspaces.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/__init__.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_azure_machine_learning_workspaces_enums.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_models.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/models/_models_py3.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_machine_learning_compute_operations.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_operations.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_usages_operations.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_virtual_machine_sizes_operations.py
  sdk/machinelearning/azure-mgmt-machinelearningservices/azure/mgmt/machinelearningservices/operations/_workspaces_operations.py
Labels: RestPRMerged

#6873 [AutoPR containerregistry/resource-manager] [ACR] Update retention policy schema
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01/models/_models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_05_01/models/_models_py3.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models.py
  sdk/containerregistry/azure-mgmt-containerregistry/azure/mgmt/containerregistry/v2019_06_01_preview/models/_models_py3.py
Labels: RestPRMerged

#6908 [AutoPR compute/resource-manager] Updating an incorrect description for uploadsizebytes
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
Labels: RestPRMerged

#6425 Undefined name: import unittest for access to unittest.main()
  sdk/storage/azure-storage-blob/tests/test_container.py
Labels: Client, Service Attention, Storage, customer-reported

#6893 Final cosmos pylint
  sdk/cosmos/azure-cosmos/azure/cosmos/_base.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_default_retry_policy.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/base_execution_context.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/document_producer.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/execution_dispatcher.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/multi_execution_aggregator.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_global_endpoint_manager.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_location_cache.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_query_iterable.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_resource_throttle_retry_policy.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_retry_utility.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_routing/routing_map_provider.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_session.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_vector_session_token.py
  sdk/cosmos/azure-cosmos/azure/cosmos/container.py
  sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
  sdk/cosmos/azure-cosmos/azure/cosmos/database.py
  sdk/cosmos/azure-cosmos/azure/cosmos/documents.py
  sdk/cosmos/azure-cosmos/azure/cosmos/offer.py
  sdk/cosmos/azure-cosmos/azure/cosmos/partition_key.py
  sdk/cosmos/azure-cosmos/azure/cosmos/scripts.py
Labels: Cosmos

#6929 [storage] make storage pylint-clean
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared_access_signature.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/blob_service_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/container_client_async.py
  sdk/storage/azure-storage-blob/azure/storage/blob/blob_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/blob_service_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/container_client.py
  sdk/storage/azure-storage-blob/azure/storage/blob/lease.py
  sdk/storage/azure-storage-file/azure/storage/file/_shared_access_signature.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/directory_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/file_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/file_service_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/aio/share_client_async.py
  sdk/storage/azure-storage-file/azure/storage/file/directory_client.py
  sdk/storage/azure-storage-file/azure/storage/file/file_client.py
  sdk/storage/azure-storage-file/azure/storage/file/file_service_client.py
  sdk/storage/azure-storage-file/azure/storage/file/share_client.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared_access_signature.py
  sdk/storage/azure-storage-queue/azure/storage/queue/aio/queue_client_async.py
  sdk/storage/azure-storage-queue/azure/storage/queue/aio/queue_service_client_async.py
  sdk/storage/azure-storage-queue/azure/storage/queue/queue_client.py
  sdk/storage/azure-storage-queue/azure/storage/queue/queue_service_client.py
Labels: Client, Storage

#6860 [AutoPR reservations/resource-manager] [Hub Generated] Review request for Microsoft.Capacity to add version preview/2019-04-01
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/_azure_reservation_api.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/__init__.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_models_py3.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/models/_paged_models.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/__init__.py
  sdk/reservations/azure-mgmt-reservations/azure/mgmt/reservations/operations/_reservation_operations.py
Labels: RestPRMerged

#6899 [AutoPR azuredata/resource-manager] chore: jsonfmt azuredata
  sdk/azure-mgmt/azuredata/__init__.py
  sdk/azure-mgmt/azuredata/_azure_data_management_client.py
  sdk/azure-mgmt/azuredata/_configuration.py
  sdk/azure-mgmt/azuredata/models/__init__.py
  sdk/azure-mgmt/azuredata/models/_azure_data_management_client_enums.py
  sdk/azure-mgmt/azuredata/models/_models.py
  sdk/azure-mgmt/azuredata/models/_models_py3.py
  sdk/azure-mgmt/azuredata/models/_paged_models.py
  sdk/azure-mgmt/azuredata/operations/__init__.py
  sdk/azure-mgmt/azuredata/operations/_operations.py
  sdk/azure-mgmt/azuredata/operations/_sql_server_registrations_operations.py
  sdk/azure-mgmt/azuredata/operations/_sql_servers_operations.py
  sdk/azure-mgmt/azuredata/version.py
Labels: RestPRMerged

#6916 [AutoPR billing/resource-manager] [Microsoft.Billing] Add missing reseller property.
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/product.py
  sdk/billing/azure-mgmt-billing/azure/mgmt/billing/models/product_py3.py
Labels: RestPRMerged

#6979 [azure-core] trio deprecated run_sync_in_worker_thread()
  sdk/core/azure-core/azure/core/pipeline/transport/requests_trio.py
Labels: Azure.Core

#6990 Include ProxyPolicy in credential pipelines
  sdk/identity/azure-identity/azure/identity/_authn_client.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_transport_adapter.py
  sdk/identity/azure-identity/azure/identity/aio/_authn_client.py
Labels: Azure.Identity, Client

#6897 [AutoPR] compute/resource-manager
  sdk/compute/azure-mgmt-compute/HISTORY.rst
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/__init__.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_compute_management_client_enums.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/models/_models_py3.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_virtual_machine_scale_set_vms_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/version.py
Labels: ServicePR

#6869 [AutoPR healthcareapis/resource-manager] Move to stable version
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/_healthcare_apis_management_client.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/models/_models_py3.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operation_results_operations.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_operations.py
  sdk/healthcareapis/azure-mgmt-healthcareapis/azure/mgmt/healthcareapis/operations/_services_operations.py
Labels: RestPRMerged

#7005 [AutoPR datafactory/resource-manager] Chainingtrigger
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/__init__.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models.py
  sdk/datafactory/azure-mgmt-datafactory/azure/mgmt/datafactory/models/_models_py3.py
Labels: RestPRMerged

#6940 [AutoPR storagecache/resource-manager] Dev storagecache microsoft.storagecache 2019 06 01 preview
  sdk/storage/azure-mgmt-storagecache/HISTORY.rst
  sdk/storage/azure-mgmt-storagecache/MANIFEST.in
  sdk/storage/azure-mgmt-storagecache/README.rst
  sdk/storage/azure-mgmt-storagecache/azure/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/_configuration.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/_storage_cache_mgmt_client.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_models.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_models_py3.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_paged_models.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/models/_storage_cache_mgmt_client_enums.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/__init__.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_caches_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_skus_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_storage_targets_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/operations/_usage_models_operations.py
  sdk/storage/azure-mgmt-storagecache/azure/mgmt/storagecache/version.py
  sdk/storage/azure-mgmt-storagecache/sdk_packaging.toml
  sdk/storage/azure-mgmt-storagecache/setup.cfg
  sdk/storage/azure-mgmt-storagecache/setup.py
Labels: RestPRMerged

#7010 [AutoPR compute/resource-manager] [Compute] Add missing $expand parameter to AvSet list by subscription API
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2016_03_30/operations/_availability_sets_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2017_03_30/operations/_availability_sets_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2017_12_01/operations/_availability_sets_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_04_01/operations/_availability_sets_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_06_01/operations/_availability_sets_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2018_10_01/operations/_availability_sets_operations.py
  sdk/compute/azure-mgmt-compute/azure/mgmt/compute/v2019_03_01/operations/_availability_sets_operations.py
Labels: RestPRMerged

#6937 [AutoPR cognitiveservices/resource-manager] Fix check domain path
  sdk/cognitiveservices/azure-mgmt-cognitiveservices/README.rst
  sdk/cognitiveservices/azure-mgmt-cognitiveservices/azure/mgmt/cognitiveservices/operations/_cognitive_services_management_client_operations.py
  sdk/cognitiveservices/azure-mgmt-cognitiveservices/setup.py
Labels: RestPRMerged

#6821 [AutoPR maintenance/resource-manager] Adding Maintenance RP
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/__init__.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/_configuration.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/_maintenance_management_client.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/models/__init__.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/models/_maintenance_management_client_enums.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/models/_models.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/models/_models_py3.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/models/_paged_models.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/operations/__init__.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/operations/_apply_updates_operations.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/operations/_configuration_assignments_operations.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/operations/_maintenance_configurations_operations.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/operations/_operations.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/operations/_updates_operations.py
  sdk/azure-mgmt-Maintenance/azure/mgmt/Maintenance/version.py
Labels: RestPRMerged

#7007 Eventhubs pylint errors
  pylintrc
  sdk/eventhub/azure-eventhubs/azure/__init__.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/__init__.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/_connection_manager.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/_consumer_producer_mixin.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_connection_manager_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/_consumer_producer_mixin_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/client_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/consumer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/error_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/aio/producer_async.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/client_abstract.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/common.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/configuration.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/consumer.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/error.py
  sdk/eventhub/azure-eventhubs/azure/eventhub/producer.py
  sdk/eventhub/azure-eventhubs/tests/test_negative.py
  sdk/eventhub/azure-eventhubs/tests/test_send.py
Labels: Client, Event Hubs
