Repository Azure/azure-sdk-for-python, pull requests merged in 2022-12, with the labels that each got.

#27742 [Component] Fix precision issue when load component from yaml
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/component/component.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_component.pyTestComponenttest_component_create[tests/test_configs/internal/hdi-component/component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_component.pyTestComponenttest_component_load[tests/test_configs/internal/hdi-component/component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[4-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[4-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_with_setting_node_output_mode.json
  sdk/ml/azure-ai-ml/tests/test_configs/internal/component_with_input_outputs/component_spec_with_attrs.yaml
Labels: ML-Pipelines, ML-Assets

#27728 [TA] update tests
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_autodetect_lang_document.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_sentiment_analysis_task_with_opinion_mining.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_autodetect_lang_document.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_sentiment_analysis_task_with_opinion_mining.json
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Labels: Cognitive - Text Analytics

#27772 Add docs for out-of-repo recording management
  doc/dev/recording_migration_guide.md
  doc/dev/tests.md
Labels: Docs, EngSys

#27768 add doc link for scopes
  sdk/identity/azure-identity/azure/identity/_credentials/application.py
  sdk/identity/azure-identity/azure/identity/_credentials/authorization_code.py
  sdk/identity/azure-identity/azure/identity/_credentials/azure_cli.py
  sdk/identity/azure-identity/azure/identity/_credentials/azure_powershell.py
  sdk/identity/azure-identity/azure/identity/_credentials/chained.py
  sdk/identity/azure-identity/azure/identity/_credentials/default.py
  sdk/identity/azure-identity/azure/identity/_credentials/environment.py
  sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
  sdk/identity/azure-identity/azure/identity/_credentials/shared_cache.py
  sdk/identity/azure-identity/azure/identity/_credentials/vscode.py
  sdk/identity/azure-identity/azure/identity/_internal/get_token_mixin.py
  sdk/identity/azure-identity/azure/identity/_internal/interactive.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/application.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/authorization_code.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_cli.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/chained.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/environment.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/shared_cache.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/vscode.py
  sdk/identity/azure-identity/azure/identity/aio/_internal/get_token_mixin.py
Labels: Azure.Identity

#27166 [EventHub] Support py311 and Bump uamqp Version
  eng/tox/install_depend_packages.py
  sdk/eventhub/azure-eventhub-checkpointstoreblob-aio/setup.py
  sdk/eventhub/azure-eventhub-checkpointstoreblob/setup.py
  sdk/eventhub/azure-eventhub-checkpointstoretable/setup.py
  sdk/eventhub/azure-eventhub/CHANGELOG.md
  sdk/eventhub/azure-eventhub/dev_requirements.txt
  sdk/eventhub/azure-eventhub/setup.py
  sdk/eventhub/azure-mgmt-eventhub/tests/_aio_testcase.py
  shared_requirements.txt
Labels: Event Hubs

#27660 feat: validate component for node
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/environment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/resource.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/component_job.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/base_node.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/pipeline.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_parallel_component_entity.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_with_specific_nodes.py
  sdk/ml/azure-ai-ml/tests/internal/_utils.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_parallel_run_function.json
  sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
Labels: ML-Pipelines

#27774 [Pipeline] Enable pipeline input as runsetting value
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_artifact_cache.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py
Labels: ML-Pipelines

#27776 refactor: adopt optimized variable name tracing mechanism
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_func_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/setup.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_pipeline_builder.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_persistent_locals.py
Labels: ML-Pipelines

#27800 [Service Bus] Remove Six
  sdk/servicebus/azure-servicebus/azure/servicebus/_common/message.py
  sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_receiver.py
  sdk/servicebus/azure-servicebus/azure/servicebus/_servicebus_session.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_session_async.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_shared_key_policy_async.py
  sdk/servicebus/azure-servicebus/azure/servicebus/management/_shared_key_policy.py
  sdk/servicebus/azure-servicebus/azure/servicebus/management/_utils.py
  sdk/servicebus/azure-servicebus/setup.py
Labels: Service Bus

#27785 Sync eng/common directory with azure-sdk-tools for PR 4856
  eng/common/pipelines/templates/steps/publish-artifact.yml
Labels: EngSys, Central-EngSys

#27806 Resolve Failing Storage Build
  sdk/storage/azure-mgmt-storagesync/dev_requirements.txt
Labels: Storage

#27771 [Storage] Use `tempfile` for file-share package
  sdk/storage/azure-storage-file-share/tests/test_file.py
  sdk/storage/azure-storage-file-share/tests/test_file_async.py
  sdk/storage/azure-storage-file-share/tests/test_get_file.py
  sdk/storage/azure-storage-file-share/tests/test_get_file_async.py
Labels: Storage

#27778 [ML][Pipelines]Support parallel_for output mapping
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel_for.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/base.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_with_specific_nodes.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_port_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_primitive_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_command_function.json
Labels: ML-Pipelines

#27821 Increment version for ml releases
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
Labels: Machine Learning, auto-merge

#25944 add wam support
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/azure/identity/_credentials/browser.py
  sdk/identity/azure-identity/azure/identity/_credentials/certificate.py
  sdk/identity/azure-identity/azure/identity/_credentials/client_secret.py
  sdk/identity/azure-identity/azure/identity/_credentials/on_behalf_of.py
  sdk/identity/azure-identity/azure/identity/_credentials/user_password.py
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
Labels: Azure.Identity

#25714 add instance_discovery support
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
  sdk/identity/azure-identity/tests/test_instance_discovery.py
Labels: Azure.Identity

#27824 Sync eng/common directory with azure-sdk-tools for PR 4878
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#27811 [ML][Pipelines] Not use tmp path in flaky test
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/test_configs/components/component_for_reuse_test/component.yml
Labels: ML-Pipelines

#27829 Update changelog
  sdk/ml/azure-ai-ml/CHANGELOG.md
Labels: ML-Pipelines

#27838 Refactor model download to generate the path prefix for new registry model URI types
  sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_constants.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_storage_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_storage_utils.py
Labels: Machine Learning, ML-Assets

#27851 Remove opencensus dependency
  sdk/ml/azure-ai-ml/setup.py
Labels: Machine Learning

#27855 Enable more job inputs - outputs for batch invoke
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/_azure_machine_learning_workspaces.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/_configuration.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/_metadata.json
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/aio/_azure_machine_learning_workspaces.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/aio/_configuration.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/aio/operations/_batch_job_deployment_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/aio/operations/_batch_job_endpoint_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/models/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/models/_azure_machine_learning_workspaces_enums.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/models/_models.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/models/_models_py3.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/operations/_batch_job_deployment_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2020_09_01_dataplanepreview/operations/_batch_job_endpoint_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_job.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_endpoint.py
  sdk/ml/azure-ai-ml/swagger/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2020-09-01-dataplanepreview/mfe.json
Labels: Machine Learning

#27777 Support PPE live tests for Identity SDK
  sdk/communication/azure-communication-identity/tests.yml
Labels: Communication, Communication - Identity

#27815 [ML] [Pipelines] fix: try to enable internal components in pipeline_node_factory
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_util.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/resource.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component_factory.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_load_component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py
  sdk/ml/azure-ai-ml/tests/internal/_utils.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py
Labels: ML-Pipelines

#27837 Add support for batch invoke endpoint job
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_endpoint.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_deployment_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
  sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_endpoint.py
  sdk/ml/azure-ai-ml/tests/recordings/batch_services/e2etests/test_batch_endpoint.pyTestBatchEndpointtest_batch_component.json
  sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/batch_deployment_component.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/hello-component/hello.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/deployments/batch/hello-component/src/hello.py
  sdk/ml/azure-ai-ml/tests/test_configs/endpoints/batch/batch_endpoint_deployment_component.yaml
Labels: Machine Learning, ML-Inference

#27850 Prevent auto_decompress exception when using EnvironmentCredential
  .vscode/cspell.json
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py
Labels: customer-reported, Azure.Core, needs-author-feedback

#27675 [ACR] Change audience to be optional
  sdk/containerregistry/azure-containerregistry/CHANGELOG.md
  sdk/containerregistry/azure-containerregistry/azure/containerregistry/_container_registry_client.py
  sdk/containerregistry/azure-containerregistry/azure/containerregistry/_helpers.py
  sdk/containerregistry/azure-containerregistry/azure/containerregistry/aio/_async_container_registry_client.py
  sdk/containerregistry/azure-containerregistry/dev_requirements.txt
  sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.pyTestContainerRegistryClienttest_construct_container_registry_client.json
  sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client.pyTestContainerRegistryClienttest_set_audience.json
  sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client_async.pyTestContainerRegistryClientAsynctest_construct_container_registry_client.json
  sdk/containerregistry/azure-containerregistry/tests/recordings/test_container_registry_client_async.pyTestContainerRegistryClientAsynctest_set_audience.json
  sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py
  sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py
  sdk/containerregistry/azure-containerregistry/tests/testcase.py
Labels: Container Registry, Client

#27759 change random_sample_percentage to sampling_rate
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/sampling_strategy_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/sampling_strategy.py
Labels: ML-Inference, ML-Assets

#27858 Unifying approach to selecting static versus dynamic livetest resourc…
  sdk/communication/azure-communication-chat/tests/_shared/testcase.py
  sdk/communication/azure-communication-email/tests/_shared/testcase.py
  sdk/communication/azure-communication-identity/tests/_shared/testcase.py
  sdk/communication/azure-communication-jobrouter/tests/_shared/testcase.py
  sdk/communication/azure-communication-networktraversal/tests/_shared/testcase.py
  sdk/communication/azure-communication-phonenumbers/test/_shared/testcase.py
  sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client.py
  sdk/communication/azure-communication-phonenumbers/test/test_phone_number_administration_client_async.py
  sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e.py
  sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e_async.py
  sdk/communication/azure-communication-rooms/tests/_shared/testcase.py
  sdk/communication/azure-communication-sms/tests/_shared/testcase.py
Labels: Communication

#27865 [Batch component deployment]Assign default_compute value
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_deployment.py
Labels: Machine Learning, ML-Inference

#27854 Update the reference documentation for onlinedeployment and segregate…
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
  sdk/ml/azure-ai-ml/samples/README.md
  sdk/ml/azure-ai-ml/samples/ml_samples_authentication_sovereign_cloud.py
Labels: Machine Learning, ML-Assets

#27891 Update job input types handling based on its type
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/batch/batch_job.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_endpoint.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
Labels: Machine Learning, ML-Inference

#27888 query value max bug fix
  sdk/cosmos/azure-cosmos/CHANGELOG.md
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/aio/endpoint_component.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_execution_context/endpoint_component.py
  sdk/cosmos/azure-cosmos/test/test_query.py
Labels: Cosmos

#27820 Adds Correlated Activity Id
  sdk/cosmos/azure-cosmos/CHANGELOG.md
  sdk/cosmos/azure-cosmos/azure/cosmos/_base.py
  sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
  sdk/cosmos/azure-cosmos/azure/cosmos/container.py
  sdk/cosmos/azure-cosmos/azure/cosmos/http_constants.py
  sdk/cosmos/azure-cosmos/test/test_correlated_activity_id.py
Labels: Cosmos

#27841 Add schema class tour
  sdk/ml/azure-ai-ml/.tours/schema_classes.tour
Labels: Machine Learning

#27913 Update exporter to OpenTelemetry api/sdk v1.15.0
  sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
  sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/export/logs/_exporter.py
  sdk/monitor/azure-monitor-opentelemetry-exporter/setup.py
  sdk/monitor/azure-monitor-opentelemetry-exporter/tests/logs/test_logs.py
  shared_requirements.txt
Labels: customer-reported

#27932 [Search] Move recordings to assets repo
  sdk/search/azure-search-documents/assets.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_basic_live_async.pyTestSearchClientAsynctest_get_document.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_basic_live_async.pyTestSearchClientAsynctest_get_document_count.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_basic_live_async.pyTestSearchClientAsynctest_get_document_missing.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_buffered_sender_live_async.pyTestSearchIndexingBufferedSenderAsynctest_search_client_index_buffered_sender.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_index_document_live_async.pyTestSearchClientDocumentsAsynctest_search_client_index_document.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_search_live_async.pyTestClientTestAsynctest_search_client.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_client_search_live_async.pyTestClientTestAsynctest_search_client_large.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_index_client_alias_live_async.pyTestSearchClientAliastest_alias.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_index_client_data_source_live_async.pyTestSearchClientDataSourcesAsynctest_data_source.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_index_client_live_async.pyTestSearchIndexClientAsynctest_search_index_client.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_index_client_skillset_live_async.pyTestSearchClientSkillsetstest_skillset_crud.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_index_client_synonym_map_live_async.pyTestSearchClientSynonymMapstest_synonym_map.json
  sdk/search/azure-search-documents/tests/recordings/async_tests/test_search_indexer_client_live_async.pyTestSearchIndexerClientTestAsynctest_search_indexers.json
  sdk/search/azure-search-documents/tests/recordings/test_search_client_basic_live.pyTestSearchClienttest_get_document.json
  sdk/search/azure-search-documents/tests/recordings/test_search_client_basic_live.pyTestSearchClienttest_get_document_count.json
  sdk/search/azure-search-documents/tests/recordings/test_search_client_basic_live.pyTestSearchClienttest_get_document_missing.json
  sdk/search/azure-search-documents/tests/recordings/test_search_client_buffered_sender_live.pyTestSearchIndexingBufferedSendertest_search_client_index_buffered_sender.json
  sdk/search/azure-search-documents/tests/recordings/test_search_client_index_document_live.pyTestSearchClientIndexDocumenttest_search_client_index_document.json
  sdk/search/azure-search-documents/tests/recordings/test_search_client_search_live.pyTestSearchClienttest_search_client.json
  sdk/search/azure-search-documents/tests/recordings/test_search_index_client_alias_live.pyTestSearchClientAliastest_alias.json
  sdk/search/azure-search-documents/tests/recordings/test_search_index_client_data_source_live.pyTestSearchClientDataSourcestest_data_source.json
  sdk/search/azure-search-documents/tests/recordings/test_search_index_client_live.pyTestSearchIndexClienttest_search_index_client.json
  sdk/search/azure-search-documents/tests/recordings/test_search_index_client_skillset_live.pyTestSearchSkillsettest_skillset_crud.json
  sdk/search/azure-search-documents/tests/recordings/test_search_index_client_synonym_map_live.pyTestSearchClientSynonymMapstest_synonym_map.json
  sdk/search/azure-search-documents/tests/recordings/test_search_indexer_client_live.pyTestSearchIndexerClientTesttest_search_indexers.json
Labels: Search, Client, MQ, test-enhancement

#27934 [Schema Registry] Move recordings to assets repo
  sdk/schemaregistry/azure-schemaregistry/assets.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_get_schema_errors.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_get_schema_properties_errors.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_register_schema_errors.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_schema_basic_async.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_schema_negative_no_schema_async.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_schema_negative_no_schema_version_async.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_schema_negative_wrong_credential_async.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_schema_negative_wrong_endpoint_async.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_schema_same_twice_async.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/async_tests/test_schema_registry_async.pyTestSchemaRegistryAsynctest_schema_update_async.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_get_schema_errors.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_get_schema_properties_errors.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_register_schema_errors.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_basic.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_negative_no_schema.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_negative_no_schema_version.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_negative_wrong_credential.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_negative_wrong_endpoint.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_same_twice.json
  sdk/schemaregistry/azure-schemaregistry/tests/recordings/test_schema_registry.pyTestSchemaRegistrytest_schema_update.json
Labels: Client, MQ, Schema Registry, test-enhancement

#27935 [Schema Registry Avro] Move recordings to assets repo
  sdk/schemaregistry/azure-schemaregistry-avroencoder/assets.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_basic_sr_avro_encoder_decode_readers_schema.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_basic_sr_avro_encoder_with_auto_register_schemas.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_basic_sr_avro_encoder_with_request_options.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_basic_sr_avro_encoder_without_auto_register_schemas.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_encode_primitive.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_encode_record.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_error_schema_as_record.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_fixed_types.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_invalid_json_string.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_invalid_type.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_primitive_types.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_record_fields.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder.pyTestAvroEncodertest_parse_record_name.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_basic_sr_avro_encoder_decode_readers_schema.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_basic_sr_avro_encoder_with_auto_register_schemas.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_basic_sr_avro_encoder_with_request_options.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_basic_sr_avro_encoder_without_auto_register_schemas.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_encode_primitive.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_encode_record.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_error_schema_as_record.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_fixed_types.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_invalid_json_string.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_invalid_type.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_primitive_types.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_record_fields.json
  sdk/schemaregistry/azure-schemaregistry-avroencoder/tests/recordings/test_avro_encoder_async.pyTestAvroEncoderAsynctest_parse_record_name.json
Labels: Client, MQ, Schema Registry, test-enhancement

#27938 [Conversations] Move recordings to assets repo
  sdk/cognitivelanguage/azure-ai-language-conversations/assets.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_authoring.pyTestConversationAuthoringtest_authoring_aad.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_authoring_async.pyTestConversationAuthoringAsynctest_authoring_aad.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_pii_transcript_input.pyTestConversationalPiitest_conversational_pii.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_pii_transcript_input_async.pyTestConversationalPiiAsynctest_conversational_pii.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_sentiment.pyTestConversationalSentimentTasktest_conversational_sentiment_task.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_sentiment_async.pyTestConversationalSentimentTaskAsynctest_conversational_sentiment_task.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization.pyTestConversationalSummarizationtest_conv_summ_chapter_narrative.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization.pyTestConversationalSummarizationtest_conversational_summarization.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization_async.pyTestConversationalSummarizationAsynctest_conv_summ_chapter_narrative.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization_async.pyTestConversationalSummarizationAsynctest_conversational_summarization.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conversation_app.pyTestConversationApptest_conversation_app.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conversation_app.pyTestConversationApptest_conversation_app_aad_auth.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conversation_app_async.pyTestConversationAppAsynctest_conversation_app.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conversation_app_async.pyTestConversationAppAsynctest_conversation_app_aad_auth.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_orchestration_app_conv_response.pyTestOrchestrationAppConvResponsetest_orchestration_app_conv_response.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_orchestration_app_conv_response_async.pyTestOrchestrationAppConvResponseAsynctest_orchestration_app_conv_response.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_orchestration_app_qna_response.pyTestOrchestrationAppQnaResponsetest_orchestration_app_qna_response.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_orchestration_app_qna_response_async.pyTestOrchestrationAppQnaResponseAsynctest_orchestration_app_qna_response.json
Labels: Client, MQ, Cognitive - Language, test-enhancement

#27939 [Question Answering] Move recordings to assets repo
  sdk/cognitivelanguage/azure-ai-language-questionanswering/assets.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_create_and_deploy_project.pyTestCreateAndDeploytest_create_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_create_and_deploy_project.pyTestCreateAndDeploytest_create_project_aad.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_create_and_deploy_project.pyTestCreateAndDeploytest_deploy_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_create_and_deploy_project_async.pyTestCreateAndDeployAsynctest_create_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_create_and_deploy_project_async.pyTestCreateAndDeployAsynctest_create_project_aad.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_create_and_deploy_project_async.pyTestCreateAndDeployAsynctest_deploy_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_export_import_project.pyTestExportAndImporttest_export_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_export_import_project.pyTestExportAndImporttest_import_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_export_import_project_async.pyTestExportAndImportAsynctest_export_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_export_import_project_async.pyTestExportAndImportAsynctest_import_project.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_aad.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_filter.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_filter_dict_params.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_llc.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_llc_with_answerspan.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_only_id.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_overload.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_python_dict.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_with_answerspan.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_with_dictparams.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase.pyTestQnAKnowledgeBasetest_query_knowledgebase_with_followup.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_aad.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_filter.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_filter_dict_params.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_llc.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_llc_with_answerspan.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_only_id.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_overload.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_python_dict.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_with_answerspan.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_with_dictparams.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_knowledgebase_async.pyTestQnAKnowledgeBaseAsynctest_query_knowledgebase_with_followup.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text.pyTestQueryTexttest_query_text.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text.pyTestQueryTexttest_query_text_default_lang.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text.pyTestQueryTexttest_query_text_llc.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text.pyTestQueryTexttest_query_text_overload.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text.pyTestQueryTexttest_query_text_with_dictparams.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text.pyTestQueryTexttest_query_text_with_str_records.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text_async.pyTestQueryTextAsynctest_query_text.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text_async.pyTestQueryTextAsynctest_query_text_llc.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text_async.pyTestQueryTextAsynctest_query_text_overload.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text_async.pyTestQueryTextAsynctest_query_text_with_dictparams.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_query_text_async.pyTestQueryTextAsynctest_query_text_with_str_records.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_update_knowledge_sources.pyTestSourcesQnasSynonymstest_add_qna.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_update_knowledge_sources.pyTestSourcesQnasSynonymstest_add_source.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_update_knowledge_sources.pyTestSourcesQnasSynonymstest_add_synonym.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_update_knowledge_sources_async.pyTestSourcesQnasSynonymsAsynctest_add_qna.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_update_knowledge_sources_async.pyTestSourcesQnasSynonymsAsynctest_add_source.json
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/recordings/test_update_knowledge_sources_async.pyTestSourcesQnasSynonymsAsynctest_add_synonym.json
Labels: Client, MQ, Cognitive - Language, test-enhancement

#26208 refactor:eventhub/_eventprocessor:type hint added
  sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/_eventprocessor_mixin.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/checkpoint_store.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/event_processor.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/in_memory_checkpoint_store.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/ownership_manager.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/partition_context.py
Labels: Event Hubs, customer-reported

#27919 Fixed bug in sip routing. SDK shouldnt send empty patch.
  sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/siprouting/_sip_routing_client.py
  sdk/communication/azure-communication-phonenumbers/azure/communication/phonenumbers/siprouting/aio/_sip_routing_client_async.py
  sdk/communication/azure-communication-phonenumbers/test/recordings/test_sip_routing_client_e2e.pyTestSipRoutingClientE2Etest_set_trunks_empty_list.json
  sdk/communication/azure-communication-phonenumbers/test/recordings/test_sip_routing_client_e2e_async.pyTestSipRoutingClientE2EAsynctest_set_trunks_empty_list.json
  sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e.py
  sdk/communication/azure-communication-phonenumbers/test/test_sip_routing_client_e2e_async.py
Labels: Communication

#27949 add experimental tag to job definition class
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/job_definition.py
Labels: Machine Learning, ML-Assets

#27952 Sync eng/common directory with azure-sdk-tools for PR 4944
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#27948 [Eventhubs] Remove Six
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_encode.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/utils.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
  sdk/eventhub/azure-eventhub/azure/eventhub/exceptions.py
Labels: Event Hubs

#27957 Fix path validation when specifying data asset using "latest" tag
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_batch_endpoint_operations.py
Labels: Machine Learning, ML-Inference

#27920 [ml] support for registry environment next version auto increment
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py
  sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py
  sdk/ml/azure-ai-ml/tests/environment/unittests/test_environment_operations.py
  sdk/ml/azure-ai-ml/tests/recordings/environment/e2etests/test_environment.pyTestEnvironmenttest_create_autoincrement.json
  sdk/ml/azure-ai-ml/tests/recordings/environment/e2etests/test_environment.pyTestEnvironmenttest_environment_create_conda.json
  sdk/ml/azure-ai-ml/tests/recordings/environment/e2etests/test_environment.pyTestEnvironmenttest_environment_create_conda_inline.json
  sdk/ml/azure-ai-ml/tests/recordings/environment/e2etests/test_environment.pyTestEnvironmenttest_environment_create_or_update_docker.json
  sdk/ml/azure-ai-ml/tests/recordings/environment/e2etests/test_environment.pyTestEnvironmenttest_environment_create_or_update_docker_context_and_image.json
Labels: Machine Learning, ML-Assets

#27942 [ML][Pipelines] Add component validate test for early available output
  sdk/ml/azure-ai-ml/tests/component/unittests/test_component_validate.py
  sdk/ml/azure-ai-ml/tests/test_configs/components/invalid/helloworld_component_early_available_output_not_set_is_control.yml
Labels: Machine Learning, ML-Pipelines

#27804 Change schedule and WS conn print behavior
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_resource.py
Labels: ML-Workspace, ML-WorkspaceConnections

#27954 [EventHubs] add asyncio marker to pyamqp test
  sdk/eventhub/azure-eventhub/tests/pyamqp_tests/asynctests/test_send_receive_pyamqp_async.py
  sdk/eventhub/azure-eventhub/tests/pyamqp_tests/asynctests/test_websocket_async.py
  sdk/eventhub/azure-eventhub/tests/pyamqp_tests/unittest/asynctests/test_websocket_exception_async.py
Labels: Event Hubs

#27951 Sync eng/common directory with azure-sdk-tools for PR 4514
  eng/common/scripts/Verify-AgentOS.ps1
Labels: EngSys, Central-EngSys

#27970 fixing default compute pascal casing issue
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/batch_deployment.py
Labels: Machine Learning, ML-Assets

#27971 Sync eng/common directory with azure-sdk-tools for PR 4962
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
Labels: EngSys, Central-EngSys

#27671 [CLU] enable pyright,verifytypes,samples for type checking
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_client.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_operations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_serialization.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_client.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_operations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_client.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_operations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_serialization.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_version.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_client.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_operations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/pyrightconfig.json
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/authoring/sample_manage_projects_async.py
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/authoring/sample_manage_projects.py
  sdk/cognitivelanguage/azure-ai-language-conversations/swagger/README.md
  tools/azure-sdk-tools/ci_tools/environment_exclusions.py
Labels: Cognitive - Language

#27696 allow setting dict in command.identity , sweep.search_space in pipleine
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/command.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/sweep.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
Labels: ML-Pipelines

#27969 Sync eng/common directory with azure-sdk-tools for PR 4940
  eng/common/scripts/Test-SampleMetadata.ps1
Labels: EngSys, Central-EngSys

#27668 [TA] enable verifytypes
  sdk/textanalytics/azure-ai-textanalytics/azure/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_dict_mixin.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_lro.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_lro_async.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_actions_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_action_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_with_opinion_mining_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_actions.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_action.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_repr.py
  tools/azure-sdk-tools/ci_tools/environment_exclusions.py
Labels: Cognitive - Text Analytics

#27710 [QA] enable pyright/verifytypes/samples
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_client.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_operations/_patch.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_serialization.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_client.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/aio/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_client.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_operations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_patch.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_serialization.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/_version.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_client.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_operations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_patch.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/authoring/aio/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/models/__init__.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/models/_models.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/azure/ai/language/questionanswering/models/_patch.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/async_samples/sample_chat_async.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/async_samples/sample_query_knowledgebase_async.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/async_samples/sample_query_text_async.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/sample_chat.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/sample_query_knowledgebase.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/samples/sample_query_text.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/setup.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/swagger/README.md
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_query_knowledgebase.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_query_knowledgebase_async.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_query_text.py
  sdk/cognitivelanguage/azure-ai-language-questionanswering/tests/test_query_text_async.py
  shared_requirements.txt
  tools/azure-sdk-tools/ci_tools/environment_exclusions.py
Labels: Cognitive - QnA Maker

#27988 fix package scripting for multiapi combiner
  tools/azure-sdk-tools/packaging_tools/multiapi_combiner.py
  tools/azure-sdk-tools/setup.py
Labels: auto-merge

#27987 Increment version for monitor releases
  sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
  sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_version.py
Labels: auto-merge

#26202 [artifacts] cspell spelling errors in azure-synapse-artifacts
  .vscode/cspell.json
Labels: customer-reported, needs-author-feedback

#25900 [ServiceBus]: migration type annotations in ``servicebus/aio``
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_auto_lock_renewer.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/_async_utils.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/_base_handler_async.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/_servicebus_receiver_async.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_management_client_async.py
  sdk/servicebus/azure-servicebus/azure/servicebus/aio/management/_shared_key_policy_async.py
Labels: Service Bus, customer-reported, auto-merge

#27992 Sync eng/common directory with azure-sdk-tools for PR 4988
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
  eng/common/pipelines/templates/steps/prepare-pipelines.yml
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#22997 [Perfstress] Multiprocess support
  doc/dev/perfstress_tests.md
  tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_base.py
  tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_proc.py
  tools/azure-devtools/src/azure_devtools/perfstress_tests/_perf_stress_runner.py
  tools/azure-devtools/src/azure_devtools/perfstress_tests/_repeated_timer.py
  tools/azure-devtools/src/azure_devtools/perfstress_tests/system_perfstress/log_test.py
  tools/azure-devtools/src/azure_devtools/perfstress_tests/system_perfstress/sleep_test.py
Labels: pillar-performance

#27926 [Event Grid] Move recordings to assets repo
  sdk/eventgrid/azure-eventgrid/assets.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_base64_using_data.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_none.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_str.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_with_extensions.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events_async.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events_async.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_base64_using_data.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events_async.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events_async.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_none.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events_async.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_str.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_cncf_events_async.pyTestEventGridPublisherClientCncftest_send_cloud_event_data_with_extensions.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_NONE_credential.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_data_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_data_base64_using_data.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_data_bytes.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_data_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_data_none.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_data_str.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_data_with_extensions.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_cloud_event_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_custom_schema_event.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_custom_schema_event_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_event_grid_event_data_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_event_grid_event_data_bytes.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_event_grid_event_data_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_event_grid_event_data_str.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_event_grid_event_dict_data_bytes.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_event_grid_event_dict_data_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_event_grid_event_fails_without_full_url.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_signature_credential.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client.pyTestEventGridPublisherClienttest_send_token_credential.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_NONE_credential_async.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_and_close_async_session.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_cloud_event_data_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_cloud_event_data_bytes.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_cloud_event_data_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_cloud_event_data_none.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_cloud_event_data_str.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_cloud_event_data_with_extensions.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_cloud_event_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_custom_schema_event.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_custom_schema_event_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_event_grid_event_data_as_list.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_event_grid_event_data_bytes.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_event_grid_event_data_dict.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_event_grid_event_data_str.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_event_grid_event_dict_data_bytes.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_event_grid_event_fails_without_full_url.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_signature_credential.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_eg_publisher_client_async.pyTestEventGridPublisherClienttest_send_token_credential.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_exceptions.pyTestEventGridPublisherClientExceptionstest_raise_on_auth_error.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_exceptions.pyTestEventGridPublisherClientExceptionstest_raise_on_bad_resource.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_exceptions.pyTestEventGridPublisherClientExceptionstest_raise_on_large_payload.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_exceptions_async.pyTestEventGridPublisherClientExceptionsAsynctest_raise_on_auth_error.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_exceptions_async.pyTestEventGridPublisherClientExceptionsAsynctest_raise_on_bad_resource.json
  sdk/eventgrid/azure-eventgrid/tests/recordings/test_exceptions_async.pyTestEventGridPublisherClientExceptionsAsynctest_raise_on_large_payload.json
Labels: Event Grid, Client, MQ, test-enhancement

#27868 [ML] Fixed Various Schema Issues
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/environment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/model.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_entry.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/services.py
Labels: Machine Learning, ML-Jobs, ML-Assets

#28010 Sync eng/common directory with azure-sdk-tools for PR 4998
  eng/common/pipelines/templates/jobs/prepare-pipelines.yml
  eng/common/pipelines/templates/steps/install-pipeline-generation.yml
Labels: EngSys, Central-EngSys

#28001 Sync eng/common directory with azure-sdk-tools for PR 4880
  eng/common/pipelines/templates/jobs/docindex.yml
  eng/common/scripts/job-matrix/README.md
  eng/common/scripts/job-matrix/samples/matrix.json
  eng/common/scripts/job-matrix/tests/job-matrix-functions.filter.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.modification.tests.ps1
  eng/common/scripts/job-matrix/tests/job-matrix-functions.tests.ps1
Labels: EngSys, Central-EngSys

#27826 Migrate from win2019 to win2022
  eng/pipelines/aggregate-reports.yml
  eng/pipelines/templates/jobs/ci.yml
  eng/pipelines/templates/jobs/run-cli-tests.yml
  eng/pipelines/templates/jobs/smoke.tests.yml
  eng/pipelines/templates/jobs/tests-nightly-python.yml
  eng/pipelines/templates/stages/archetype-python-release.yml
  eng/pipelines/templates/stages/cosmos-sdk-client.yml
  eng/pipelines/templates/stages/platform-matrix-cryptography-dependency.json
  eng/pipelines/templates/stages/platform-matrix.json
  sdk/storage/platform-matrix-all-versions.json
Labels: Storage, Communication

#28004 [ML] Add enable_node_public_ip to Compute Instances and Aml Computes
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/aml_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
  sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml-no-public-ip.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-no-public-ip.yaml
Labels: Machine Learning

#28011 Update prepare-pipelines flags
  eng/pipelines/prepare-pipelines.yml
Labels: Central-EngSys

#26831 add sample guide
  doc/dev/sample_guide.md
  sdk/template/azure-template/samples/sample_simple.py
Labels: Docs

#27959 [formrecognizer] Update samples
  sdk/formrecognizer/azure-ai-formrecognizer/CHANGELOG.md
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_recognizer_client.py
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_recognizer_client_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/README.md
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_authentication_v3_1_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_convert_to_and_from_dict_v3_1_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_copy_model_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_differentiate_output_labeled_tables_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_get_bounding_boxes_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_manage_custom_models_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_recognize_custom_forms_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/async_samples/sample_strongly_typing_recognized_form_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_authentication_v3_1.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_convert_to_and_from_dict_v3_1.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_copy_model.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_differentiate_output_labeled_tables.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_get_bounding_boxes.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_recognize_custom_forms.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_strongly_typing_recognized_form.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/async_samples/sample_analyze_custom_documents_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/async_samples/sample_convert_to_and_from_dict_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/async_samples/sample_copy_model_to_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_analyze_custom_documents.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_convert_to_and_from_dict.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_copy_model_to.py
  tools/azure-sdk-tools/ci_tools/environment_exclusions.py
Labels: Cognitive - Form Recognizer

#27881 Increment version for anomalydetector releases
  sdk/anomalydetector/azure-ai-anomalydetector/CHANGELOG.md
  sdk/anomalydetector/azure-ai-anomalydetector/azure/ai/anomalydetector/_version.py
Labels: auto-merge

#27866 Fix test
  sdk/tables/azure-data-tables/tests/test_table_entity_async.py
Labels: Tables

#27085 clean up code -mgmt core
  sdk/core/azure-mgmt-core/azure/mgmt/core/__init__.py
  sdk/core/azure-mgmt-core/azure/mgmt/core/_pipeline_client.py
  sdk/core/azure-mgmt-core/azure/mgmt/core/policies/__init__.py
  sdk/core/azure-mgmt-core/tests/asynctests/test_async_arm_polling.py
  sdk/core/azure-mgmt-core/tests/conftest.py
  sdk/core/azure-mgmt-core/tests/test_arm_polling.py
  sdk/core/azure-mgmt-core/tests/test_authentication.py
  sdk/core/azure-mgmt-core/tests/test_policies.py
Labels: Azure.Core

#28024 Sync eng/common directory with azure-sdk-tools for PR 4985
  eng/common/scripts/Helpers/Package-Helpers.ps1
  eng/common/scripts/Update-DocsMsMetadata.ps1
  eng/common/scripts/Update-DocsMsPackages.ps1
  eng/common/scripts/common.ps1
Labels: EngSys, Central-EngSys

#28008 [ML][Pipeline] Remove private check for pipeline component
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
  sdk/ml/azure-ai-ml/tests/conftest.py
Labels: Machine Learning, ML-Pipelines

#28012 Validation for token generation with aml audience when using OBO flow
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
  sdk/ml/azure-ai-ml/tests/job_common/unittests/test_job_operations.py
  sdk/ml/azure-ai-ml/tests/test_configs/command_job/command_job_test_user_identity.yml
Labels: Machine Learning

#28016 [formrecognizer] Validate error messages in tests
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model.py
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url.py
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dac_analyze_custom_model_from_url_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model.py
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_copy_model_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt.py
  sdk/formrecognizer/azure-ai-formrecognizer/tests/test_dmac_mgmt_async.py
Labels: Cognitive - Form Recognizer

#27897 [Key Vault] Add `send_request` method to Keys clients
  sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-keyvault-keys/assets.json
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
  sdk/keyvault/azure-keyvault-keys/samples/README.md
  sdk/keyvault/azure-keyvault-keys/samples/send_request.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
  sdk/keyvault/azure-keyvault-keys/tests/test_key_client.py
  sdk/keyvault/azure-keyvault-keys/tests/test_keys_async.py
Labels: KeyVault, Client

#28041 [Asset sync] Update documentation
  doc/dev/recording_migration_guide.md
  doc/dev/test_proxy_migration_guide.md
  doc/dev/tests.md
Labels: Docs, EngSys

#28044 [Pipeline] Improve pipeline node name update logic
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
Labels: Machine Learning, ML-Pipelines

#28040 [Eventhub] Removed reconnect from send test
  sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
Labels: Event Hubs

#28047 [ML][Pipelines] feat: apply in-memory cache for pipeline component dependency resolution
  .vscode/cspell.json
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_cache_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_validation.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_component.py
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_helloworld_nested_pipeline_component.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_dsl_parallel_for_pipeline_unprovided_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_subgraph_unprovided_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_port_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_primitive_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_subgraph.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_simple_dsl_parallel_for_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_create_pipeline_with_parameter_group.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_pipeline_with_data_as_inputs_for_pipeline_component.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_pipeline_with_pipeline_component.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_with_specific_nodes.pyTestDSLPipelineWithSpecificNodestest_dsl_pipeline_sweep_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestDoWhiletest_do_while_pipeline_with_primitive_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestDoWhiletest_pipeline_with_do_while_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_component_job.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict0].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict1].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict2].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict3].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_with_pipeline_component.json
Labels: Machine Learning, ML-Pipelines

#28055 [AutoRelease] t2-containerinstance-2022-12-26-78905(can only be merged by SDK owner)
  sdk/containerinstance/azure-mgmt-containerinstance/CHANGELOG.md
  sdk/containerinstance/azure-mgmt-containerinstance/MANIFEST.in
  sdk/containerinstance/azure-mgmt-containerinstance/_meta.json
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/__init__.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/_configuration.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/_container_instance_management_client.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/_metadata.json
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/_serialization.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/_version.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/__init__.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/_configuration.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/_container_instance_management_client.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/operations/__init__.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/operations/_container_groups_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/operations/_containers_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/operations/_location_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/operations/_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/aio/operations/_subnet_service_association_link_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/models/__init__.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/models/_container_instance_management_client_enums.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/models/_models_py3.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/__init__.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/_container_groups_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/_containers_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/_location_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/azure/mgmt/containerinstance/operations/_subnet_service_association_link_operations.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/cached_images_list.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/capabilities_list.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_attach.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_exec.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_group_create_confidential.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_group_encryption_properties.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_group_extensions.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_group_usage.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_create_or_update.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_create_priority.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_delete.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_get_failed.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_get_priority.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_get_succeeded.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_list.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_list_by_resource_group.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_restart.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_start.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_groups_stop.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/container_list_logs.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/operations_list.py
  sdk/containerinstance/azure-mgmt-containerinstance/generated_samples/subnet_service_association_link_delete.py
  sdk/containerinstance/azure-mgmt-containerinstance/setup.py
  shared_requirements.txt
Labels: Container Instances

#28059 [ML][Pipelines]feat: apply local cache for pipeline component dependency resolution
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_cache_utils.py
Labels: Machine Learning, ML-Pipelines

#28061 [ML][Pipeline] Fix armid pipeline component compute validation
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/pipeline_job_with_registered_pipeline_component.yml
Labels: Machine Learning, ML-Pipelines, ML-Assets

#27966 [Eventhub] Add Transport Information into user-agent
  sdk/eventhub/azure-eventhub/azure/eventhub/_constants.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_base.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_uamqp_transport.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_utils.py
Labels: Event Hubs

#28075 Support asset property dictionary in environment REST methods
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/environment.py
  sdk/ml/azure-ai-ml/tests/environment/unittests/test_env_entity.py
Labels: Machine Learning, ML-Assets

#28077 [Eventhub] Removed reconnect from async send test
  sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
Labels: Event Hubs

#27899 [ACR] Close client
  sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_images_async.py
  sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_delete_tags_async.py
  sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_list_tags_async.py
  sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_set_image_properties_async.py
  sdk/containerregistry/azure-containerregistry/tests/test_anon_access.py
  sdk/containerregistry/azure-containerregistry/tests/test_anon_access_async.py
  sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py
  sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py
Labels: Container Registry, Client, MQ

#28074 [ML][Pipelines]feat: use origin name & version for anonymous internal components
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_data_as_node_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_data_as_pipeline_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[0-ls_command_component.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[1-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[2-batch_score.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[3-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[4-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[5-component.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[6-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[7-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[8-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_with_setting_node_output_mode.json
Labels: Machine Learning, ML-Pipelines

#28090 [ML][pipelines] fix component hash regex
  sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py
  sdk/ml/azure-ai-ml/tests/conftest.py
Labels: Machine Learning

#26801 [SchemaRegistry] add json format
  sdk/schemaregistry/azure-schemaregistry/CHANGELOG.md
  sdk/schemaregistry/azure-schemaregistry/README.md
  sdk/schemaregistry/azure-schemaregistry/assets.json
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_constants.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_common/_response_handlers.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/__init__.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/_client.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/_configuration.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/_version.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/aio/__init__.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/aio/_client.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/aio/_configuration.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/aio/operations/_operations.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/operations/_operations.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/rest/schema/_request_builders.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_generated/rest/schema_groups/_request_builders.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_schema_registry_client.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_utils.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/_version.py
  sdk/schemaregistry/azure-schemaregistry/azure/schemaregistry/aio/_schema_registry_client_async.py
  sdk/schemaregistry/azure-schemaregistry/conftest.py
  sdk/schemaregistry/azure-schemaregistry/samples/async_samples/sample_code_schemaregistry_async.py
  sdk/schemaregistry/azure-schemaregistry/samples/async_samples/schema_registry_async.py
  sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/sample_code_schemaregistry.py
  sdk/schemaregistry/azure-schemaregistry/samples/sync_samples/schema_registry.py
  sdk/schemaregistry/azure-schemaregistry/setup.py
  sdk/schemaregistry/azure-schemaregistry/swagger/README.md
  sdk/schemaregistry/azure-schemaregistry/tests/async_tests/test_schema_registry_async.py
  sdk/schemaregistry/azure-schemaregistry/tests/test_schema_registry.py
  sdk/schemaregistry/test-resources.json
Labels: Schema Registry

#28032 [ML] Allow AmlComputes to be created outside of Workspace Region
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_compute_operations.py
  sdk/ml/azure-ai-ml/tests/compute/e2etests/test_compute.py
  sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
  sdk/ml/azure-ai-ml/tests/recordings/compute/e2etests/test_compute.pyTestComputetest_aml_compute_create_and_delete.json
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml-no-identity.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci.yaml
Labels: Machine Learning

#28037 Add regex to validate online/batch endpoints name
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_endpoint/endpoint.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_endpoint.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/_endpoint_helpers.py
Labels: Machine Learning, ML-Inference

#27999 [ML][Pipelines] refactor: remove bytecode from setup.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_func_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/setup.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_persistent_locals.py
Labels: Machine Learning, ML-Pipelines

#28038 [ML]: Resolve the cross references for MLClient, Resource and OnlineDeployment
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_registry_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/automl/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/endpoint.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_endpoint/online_endpoint.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_resource.py
  sdk/ml/azure-ai-ml/azure/ai/ml/exceptions.py
  sdk/ml/azure-ai-ml/azure/ai/ml/identity/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py
Labels: Machine Learning, ML-Assets

#27896 [Tables] Merge samples to one code snippet
  sdk/tables/azure-data-tables/samples/async_samples/sample_query_table_async.py
  sdk/tables/azure-data-tables/samples/sample_query_table.py
Labels: Client, Tables, MQ

#28098 [Tables] Remove unnecessary python version checks
  sdk/tables/azure-data-tables/azure/data/tables/_error.py
  sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
  sdk/tables/azure-data-tables/samples/sample_batching.py
  sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
Labels: Client, Tables, MQ

#28072 [ML][Pipelines]feat: apply on-disk cache for component registration in pipeline component resolution
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_cache_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/code.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_operation_orchestrator.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_command_with_optional_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_dsl_pipeline_with_only_setting_binding_node.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_dsl_pipeline_with_only_setting_pipeline_level.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_dsl_pipeline_with_setting_binding_node_and_pipeline_level.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_multi_parallel_components_with_file_input_pipeline_output.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_parallel_components_with_file_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_parallel_job.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_automl_job_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_multi_parallel_components_with_file_input_pipeline_output.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_parallel_components.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_parallel_components_with_tabular_input_pipeline_output.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_multiple_parallel_job.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_parallel_job[file_component_input_e2e.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/schedule/e2etests/test_schedule.pyTestScheduletest_command_job_schedule.json
Labels: ML-Pipelines

#28099 Remove cgi from core
  sdk/core/azure-core/azure/core/rest/_helpers.py
Labels: Azure.Core

#28116 Fix a print bug when job id is empty
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_command_builder.py
Labels: Machine Learning

#28123 Fix release bug
  sdk/recoveryservices/azure-mgmt-recoveryservicesbackup/README.md
Labels: Recovery Services

#28120 [ML][Pipelines] hotfix: bytecode persistent locals will fail for instr Label
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_func_utils.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_persistent_locals.py
Labels: Machine Learning, ML-Pipelines

#28046 [ML][Pipelines]Support group output in @pipeline
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/_input_output_helpers.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/base.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/mixin.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_group.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_control_flow_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_dsl_condition_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_group_outputs_description_overwrite.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_group_outputs_mode_overwrite.json
  sdk/ml/azure-ai-ml/tests/test_configs/components/component_with_conditional_output/spec.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_set_binding_output_input/pipeline.py
Labels: Machine Learning, ML-Pipelines

#28127 Help mypy in FR samples
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.1/sample_manage_custom_models.py
Labels: Cognitive - Form Recognizer

#27894 [AppConfig] Opt in mypy for samples
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py
  sdk/appconfiguration/azure-appconfiguration/samples/conditional_operation_sample.py
  sdk/appconfiguration/azure-appconfiguration/samples/conditional_operation_sample_async.py
  sdk/appconfiguration/azure-appconfiguration/samples/sync_token_samples.py
  sdk/appconfiguration/azure-appconfiguration/samples/sync_token_samples_async.py
  tools/azure-sdk-tools/ci_tools/environment_exclusions.py
Labels: Client, MQ, App Configuration
