Repository Azure/azure-sdk-for-python, pull requests merged in 2022-11, with the labels that each got.

#27098 [Storage] Migrate `test_queue_encodings.py` and `test_queue_service_properties.py` (queue)
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.pyTestStorageQueueEncodingtest_message_base64_decode_fails.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.pyTestStorageQueueEncodingtest_message_bytes_base64.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.pyTestStorageQueueEncodingtest_message_bytes_fails.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.pyTestStorageQueueEncodingtest_message_text_base64.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.pyTestStorageQueueEncodingtest_message_text_xml.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.pyTestStorageQueueEncodingtest_message_text_xml_invalid_chars.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.pyTestStorageQueueEncodingtest_message_text_xml_whitespace.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_base64_decode_fails.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_bytes_base64.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_bytes_fails.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_text_base64.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_text_xml.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_text_xml_invalid_chars.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings.test_message_text_xml_whitespace.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.pyTestAsyncStorageQueueEncodingtest_message_base64_decode_fails.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.pyTestAsyncStorageQueueEncodingtest_message_bytes_base64.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.pyTestAsyncStorageQueueEncodingtest_message_bytes_fails.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.pyTestAsyncStorageQueueEncodingtest_message_text_base64.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.pyTestAsyncStorageQueueEncodingtest_message_text_xml.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.pyTestAsyncStorageQueueEncodingtest_message_text_xml_invalid_chars.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.pyTestAsyncStorageQueueEncodingtest_message_text_xml_whitespace.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.test_message_base64_decode_fails.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.test_message_bytes_base64.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.test_message_text_base64.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.test_message_text_xml.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.test_message_text_xml_invalid_chars.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_encodings_async.test_message_text_xml_whitespace.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.pyTestQueueServicePropertiestest_queue_service_properties.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.pyTestQueueServicePropertiestest_retention_too_long.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.pyTestQueueServicePropertiestest_set_cors.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.pyTestQueueServicePropertiestest_set_hour_metrics.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.pyTestQueueServicePropertiestest_set_logging.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.pyTestQueueServicePropertiestest_set_minute_metrics.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.pyTestQueueServicePropertiestest_too_many_cors_rules.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.test_queue_service_properties.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.test_retention_too_long.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.test_set_cors.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.test_set_hour_metrics.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.test_set_logging.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.test_set_minute_metrics.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties.test_too_many_cors_rules.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.pyTestAsyncQueueServicePropertiestest_queue_service_properties.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.pyTestAsyncQueueServicePropertiestest_retention_too_long.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.pyTestAsyncQueueServicePropertiestest_set_cors.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.pyTestAsyncQueueServicePropertiestest_set_hour_metrics.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.pyTestAsyncQueueServicePropertiestest_set_logging.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.pyTestAsyncQueueServicePropertiestest_set_minute_metrics.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.pyTestAsyncQueueServicePropertiestest_too_many_cors_rules.json
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.test_queue_service_properties.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.test_retention_too_long.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.test_set_cors.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.test_set_hour_metrics.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.test_set_logging.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.test_set_minute_metrics.yaml
  sdk/storage/azure-storage-queue/tests/recordings/test_queue_service_properties_async.test_too_many_cors_rules.yaml
  sdk/storage/azure-storage-queue/tests/test_queue_encodings.py
  sdk/storage/azure-storage-queue/tests/test_queue_encodings_async.py
  sdk/storage/azure-storage-queue/tests/test_queue_service_properties.py
  sdk/storage/azure-storage-queue/tests/test_queue_service_properties_async.py
Labels: Storage

#27195 [ML][Pipelines] Fix git path as code bug
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_command_component_entity.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_on_registry.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py
  sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
Labels: ML-Pipelines, ML-Assets

#27200 Increment version for communication releases
  sdk/communication/azure-communication-identity/CHANGELOG.md
  sdk/communication/azure-communication-identity/azure/communication/identity/_version.py
Labels: auto-merge

#27214 test: enable internal pipeline job e2e tests
  sdk/ml/azure-ai-ml/tests/batch_services/e2etests/test_batch_deployment.py
  sdk/ml/azure-ai-ml/tests/command_job/e2etests/test_command_job.py
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dataset/e2etests/test_data.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_on_registry.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py
  sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py
  sdk/ml/azure-ai-ml/tests/import_job/e2etests/test_import_job.py
  sdk/ml/azure-ai-ml/tests/internal/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/sweep_job/e2etests/test_sweep_job.py
  sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
Labels: ML-Pipelines

#27212 [ML][Pipelines] Avoid bool test for expression in do-while scenario
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/condition_node.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/do_while.py
Labels: ML-Pipelines

#27063 [Do_while] Fix pipeline component with do-while operator cannot be submitted.
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/do_while.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_control_flow_node_in_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_node_in_pipeline_job.pyTestConditionalNodeInPipelinetest_do_while_pipeline_with_primitive_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_node_in_pipeline_job.pyTestConditionalNodeInPipelinetest_pipeline_with_do_while_node.json
Labels: ML-Pipelines

#27165 [ServiceBus] Py311 Support & Bump uamqp Version
  sdk/servicebus/azure-servicebus/CHANGELOG.md
  sdk/servicebus/azure-servicebus/setup.py
  shared_requirements.txt
Labels: Service Bus

#27211 Sync eng/common directory with azure-sdk-tools for PR 4544
  eng/common/scripts/job-matrix/Create-JobMatrix.ps1
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
  eng/common/scripts/stress-testing/generate-scenario-matrix.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#27210 Sync eng/common directory with azure-sdk-tools for PR 4574
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#27232 [TA] update gen code to remove phrasesControl
  sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_models_py3.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_text_analytics_client_enums.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/swagger/README.md
  sdk/textanalytics/azure-ai-textanalytics/tests/mock_test_responses/action_error_with_targets.json
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Labels: Cognitive - Text Analytics

#27240 Sync eng/common directory with azure-sdk-tools for PR 4591
  eng/common/scripts/stress-testing/find-all-stress-packages.ps1
Labels: EngSys, Central-EngSys

#27226 ci: skip sleep when not is_live
  sdk/ml/azure-ai-ml/tests/command_job/e2etests/test_command_job.py
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dataset/e2etests/test_data.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py
  sdk/ml/azure-ai-ml/tests/internal_utils/e2etests/test_upload_download.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_experimental_utils.py
  sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/registry/e2etests/test_registry.py
  sdk/ml/azure-ai-ml/tests/sweep_job/e2etests/test_sweep_job.py
  sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
Labels: ML-Pipelines

#27234 Sync eng/common directory with azure-sdk-tools for PR 4586
  eng/common/scripts/Update-DocsMsToc.ps1
Labels: EngSys, Central-EngSys

#27233 [TA] py311 and beta updates
  sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
  sdk/textanalytics/azure-ai-textanalytics/README.md
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/samples/README.md
  sdk/textanalytics/azure-ai-textanalytics/setup.py
  shared_requirements.txt
Labels: Cognitive - Text Analytics

#27262 Sync eng/common directory with azure-sdk-tools for PR 4603
  eng/common/pipelines/templates/steps/check-spelling.yml
  eng/common/spelling/Invoke-Cspell.ps1
Labels: EngSys, Central-EngSys

#27034 [pyAMQP] Stress fixes for aiohttp and valueError
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
Labels: Event Hubs

#27040 [CLU] add LRO return types and tests
  .vscode/cspell.json
  sdk/cognitivelanguage/azure-ai-language-conversations/CHANGELOG.md
  sdk/cognitivelanguage/azure-ai-language-conversations/README.md
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/__init__.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_configuration.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/authoring/aio/_vendor.py
  sdk/cognitivelanguage/azure-ai-language-conversations/setup.py
  sdk/cognitivelanguage/azure-ai-language-conversations/swagger/README.md
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_sentiment.pyTestConversationalSentimentTasktest_conversational_sentiment_task.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_sentiment_async.pyTestConversationalSentimentTaskAsynctest_conversational_sentiment_task.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization.pyTestConversationalSummarizationtest_conv_summ_chapter_narrative.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/recordings/test_conv_summarization_async.pyTestConversationalSummarizationAsynctest_conv_summ_chapter_narrative.json
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_conv_sentiment.py
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_conv_sentiment_async.py
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_conv_summarization.py
  sdk/cognitivelanguage/azure-ai-language-conversations/tests/test_conv_summarization_async.py
  shared_requirements.txt
Labels: Cognitive - LUIS

#27278 Sync eng/common directory with azure-sdk-tools for PR 4606
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#27287 [AppConfig] Close async clients
  sdk/appconfiguration/azure-appconfiguration/tests/asynctestcase.py
  sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_aad_async.py
  sdk/appconfiguration/azure-appconfiguration/tests/test_azure_configuration_client_async.py
Labels: Client, App Configuration

#27316 [TA] docs sweep for the beta
  sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_base_client.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_base_client_async.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_abstract_summary_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_dynamic_classification_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstract_summary.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_dynamic_classification.py
Labels: Cognitive - Text Analytics

#27340 [TA] fix weekly pipeline
  sdk/textanalytics/test-resources.json
  sdk/textanalytics/tests.yml
Labels: Cognitive - Text Analytics

#27311 [AppConfig] Update tests.yml
  sdk/appconfiguration/tests.yml
Labels: Client, App Configuration

#27307 Sync eng/common directory with azure-sdk-tools for PR 4622
  eng/common/TestResources/clouds/AzureCloud.json
Labels: EngSys, Central-EngSys

#26084 add typing docs
  doc/dev/static_type_checking.md
  doc/dev/static_type_checking_cheat_sheet.md
Labels: Docs

#27275 [ML][Pipelines] Support expression in if-else
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_condition.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_expression.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/data/expression_component_template.yml
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
Labels: ML-Pipelines

#27365 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/azure/identity/_version.py
Labels: auto-merge

#27313 Sync eng/common directory with azure-sdk-tools for PR 4629
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#27359 Create sample code for conversational sentiment
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/README.md
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/sample_conv_sentiment_async.py
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/sample_conv_sentiment.py
Labels: Cognitive - Language

#27367 Increment version for search releases
  sdk/search/azure-search-documents/CHANGELOG.md
  sdk/search/azure-search-documents/azure/search/documents/_version.py
Labels: auto-merge

#27283 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/azure/core/_version.py
Labels: auto-merge

#27346 [CLU] update docs for beta release + add example of how to export project
  scripts/devops_tasks/test_run_samples.py
  sdk/cognitivelanguage/azure-ai-language-conversations/CHANGELOG.md
  sdk/cognitivelanguage/azure-ai-language-conversations/README.md
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/aio/_operations/_operations.py
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/README.md
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/authoring/sample_import_train_deploy_project_async.py
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/async/authoring/sample_manage_projects_async.py
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/authoring/sample_import_train_deploy_project.py
  sdk/cognitivelanguage/azure-ai-language-conversations/samples/authoring/sample_manage_projects.py
Labels: Cognitive - LUIS, Cognitive - Language

#27401 Updating check enforcer permissions to enable writing comments
  .github/workflows/event.yml
Labels: Central-EngSys

#27399 Increment version for monitor releases
  sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
  sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_version.py
Labels: auto-merge

#26814 [ML] Added datastore and job to allowed input types for Jobs
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_entry.py
Labels: ML-Jobs

#27416 [ML] Change GPU SKU when in East US 2 EUAP
  sdk/ml/test-resources.json
Labels: ML-Pipelines

#27432 Sync eng/common directory with azure-sdk-tools for PR 4623
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#27433 Sync eng/common directory with azure-sdk-tools for PR 4666
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#27434 Sync eng/common directory with azure-sdk-tools for PR 4631
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#27435 Increment version for cognitivelanguage releases
  sdk/cognitivelanguage/azure-ai-language-conversations/CHANGELOG.md
  sdk/cognitivelanguage/azure-ai-language-conversations/azure/ai/language/conversations/_version.py
Labels: auto-merge

#27440 Increment version for monitor releases
  sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
  sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_version.py
Labels: auto-merge

#27442 [TA] unskip tests + rerecord
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_autodetect_with_default.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_extract_summary_action_with_options.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_multiple_of_same_action.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_autodetect_with_default.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_extract_summary_action_with_options.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_multiple_of_same_action.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare.pyTestHealthtest_show_stats_and_model_version.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare.pyTestHealthtest_show_stats_and_model_version_v3_1.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare_async.pyTestHealthtest_show_stats_and_model_version.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_healthcare_async.pyTestHealthtest_show_stats_and_model_version_v3_1.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_detect_language.pyTestDetectLanguagetest_detect_language_script.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_detect_language_async.pyTestDetectLanguagetest_detect_language_script.json
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_auth.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_auth_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_detect_language_async.py
Labels: Cognitive - Text Analytics

#27452 [ML][Pipelines] Skip removing test resources for Pipelines live test
  sdk/ml/pipeline.tests.yml
Labels: ML-Pipelines

#27304 [DT] update python version for INT tests
  sdk/translation/tests.yml
Labels: Cognitive - Translator

#27457 Sync eng/common directory with azure-sdk-tools for PR 4687
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#27301 [ML][Pipelines] Enable skip tests during GitHub migration
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_anon_component_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_distribution_components.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_command_job_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_child_run_download.json
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/command_job_in_pipeline/.gitattributes
Labels: ML-Pipelines

#27323 [ML][Pipelines] fix: add environment_variable to CommandComponent schema
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/command.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/environment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/input_output.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/node.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/command.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/parallel.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/component/parallel_component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/input_output_fields_provider.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_command.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_parallel.py
  sdk/ml/azure-ai-ml/tests/internal/_utils.py
  sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/job_common/unittests/test_local_job_invoker.py
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[0-ls_command_component.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[1-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[2-batch_score.yaml].json
Labels: ML-Pipelines

#27446 [ML][Pipelines] Add private preview flag for unexposed fields in schema
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/settings.py
Labels: ML-Pipelines

#27031 Update README.rst file
  README.rst
Labels: customer-reported

#27117 [Tables] Update tests.yml
  .vscode/cspell.json
  sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
  sdk/tables/azure-data-tables/azure/data/tables/_constants.py
  sdk/tables/azure-data-tables/tests/_shared/testcase.py
  sdk/tables/azure-data-tables/tests/test_table_batch.py
  sdk/tables/azure-data-tables/tests/test_table_batch_async.py
  sdk/tables/azure-data-tables/tests/test_table_batch_cosmos.py
  sdk/tables/azure-data-tables/tests/test_table_batch_cosmos_async.py
  sdk/tables/azure-data-tables/tests/test_table_client.py
  sdk/tables/azure-data-tables/tests/test_table_client_async.py
  sdk/tables/azure-data-tables/tests/test_table_client_cosmos.py
  sdk/tables/azure-data-tables/tests/test_table_client_cosmos_async.py
  sdk/tables/test-resources.json
  sdk/tables/tests.yml
Labels: Client, Tables

#27475 [TA] skip tests for features not supported in other clouds
  eng/tox/environment_exclusion_list.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Labels: Cognitive - Text Analytics

#27478 Sync eng/common directory with azure-sdk-tools for PR 4632
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
  eng/common/scripts/Helpers/Service-Level-Readme-Automation-Helpers.ps1
  eng/common/scripts/Service-Level-Readme-Automation.ps1
Labels: EngSys, Central-EngSys

#27479 [TA] only run tests where features supported
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_dynamic_classification.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_dynamic_classification_async.py
Labels: Cognitive - Text Analytics

#27468 [ML][Pipelines] Fix breaking tests in live mode
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_anonymous_component_reuse.json
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_component_create_default_code.json
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_component_create_twice_same_code_arm_id.json
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_mpi_component.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_anonymous_component_reuse.json
Labels: ML-Pipelines

#27498 [ML][Pipelines] Fix flaky tests in live mode
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
Labels: ML-Pipelines

#27508 Sync eng/common directory with azure-sdk-tools for PR 4701
  eng/common/scripts/Queue-Pipeline.ps1
Labels: EngSys, Central-EngSys

#27487 Common-sense `tox` environment skipping
  .vscode/cspell.json
  CONTRIBUTING.md
  doc/dev/static_type_checking.md
  doc/dev/tests.md
  eng/pipelines/templates/steps/run_pylint.yml
  eng/tox/environment_exclusion_list.py
  eng/tox/run_mypy.py
  eng/tox/run_pylint.py
  eng/tox/run_pyright.py
  eng/tox/run_verifytypes.py
  eng/tox/tox.ini
  scripts/devops_tasks/setup_execute_tests.py
  scripts/devops_tasks/tox_harness.py
  scripts/pylint_custom_plugin/README.md
  sdk/media/azure-media-analytics-edge/docs/DevTips.md
  sdk/videoanalyzer/azure-media-videoanalyzer-edge/docs/DevTips.md
  tools/azure-sdk-tools/ci_tools/environment_exclusions.py
Labels: Central-EngSys

#27065 [EventHubs] kwargs/error testing
  sdk/eventhub/azure-eventhub/azure/eventhub/_client_base.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_consumer.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_eventprocessor/event_processor.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_connection.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/_transport.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_connection_async.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_pyamqp/aio/_transport_async.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_pyamqp_transport.py
  sdk/eventhub/azure-eventhub/azure/eventhub/_transport/_uamqp_transport.py
  sdk/eventhub/azure-eventhub/azure/eventhub/aio/_client_base_async.py
  sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_pyamqp_transport_async.py
  sdk/eventhub/azure-eventhub/azure/eventhub/aio/_transport/_uamqp_transport_async.py
  sdk/eventhub/azure-eventhub/conftest.py
  sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_auth_async.py
  sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_buffered_producer_async.py
  sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_negative_async.py
  sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_properties_async.py
  sdk/eventhub/azure-eventhub/tests/livetest/asynctests/test_send_async.py
  sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_auth.py
  sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_buffered_producer.py
  sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_negative.py
  sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_properties.py
  sdk/eventhub/azure-eventhub/tests/livetest/synctests/test_send.py
Labels: Event Hubs

#27499 [Key Vault] Add OKP support for service-side sign/verify operations
  .vscode/cspell.json
  sdk/keyvault/azure-keyvault-administration/assets.json
  sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-keyvault-keys/assets.json
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/client_base.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_enums.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/__init__.py
  sdk/keyvault/azure-keyvault-keys/tests/_async_test_case.py
  sdk/keyvault/azure-keyvault-keys/tests/_test_case.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
  sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py
  sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
  shared_requirements.txt
Labels: KeyVault, Client

#27376 Increment version for eventgrid releases
  sdk/eventgrid/azure-eventgrid/CHANGELOG.md
  sdk/eventgrid/azure-eventgrid/azure/eventgrid/_version.py
Labels: auto-merge

#27426 Increment version for devcenter releases
  sdk/devcenter/azure-developer-devcenter/CHANGELOG.md
  sdk/devcenter/azure-developer-devcenter/azure/developer/devcenter/_version.py
Labels: auto-merge

#27403 Increment version for batch releases
  sdk/batch/azure-batch/CHANGELOG.md
  sdk/batch/azure-batch/azure/batch/_version.py
Labels: auto-merge

#27541 Increment version for keyvault releases
  sdk/keyvault/azure-keyvault-administration/CHANGELOG.md
  sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_version.py
  sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_version.py
Labels: auto-merge

#27549 Sync eng/common directory with azure-sdk-tools for PR 4726
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#26991 [Storage] Change algorithm used to sort headers
  sdk/storage/azure-storage-blob/azure/storage/blob/_shared/authentication.py
  sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions.pyTestStorageBlobAccessConditionstest_header_metadata_sort_in_upload_blob.json
  sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions.pyTestStorageBlobAccessConditionstest_header_metadata_sort_in_upload_blob_fails.json
  sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions_async.pyTestStorageBlobAccessConditionsAsynctest_header_metadata_sort_in_upload_blob.json
  sdk/storage/azure-storage-blob/tests/recordings/test_blob_access_conditions_async.pyTestStorageBlobAccessConditionsAsynctest_header_metadata_sort_in_upload_blob_fails.json
  sdk/storage/azure-storage-blob/tests/test_blob_access_conditions.py
  sdk/storage/azure-storage-blob/tests/test_blob_access_conditions_async.py
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_shared/authentication.py
  sdk/storage/azure-storage-file-share/azure/storage/fileshare/_shared/authentication.py
  sdk/storage/azure-storage-queue/azure/storage/queue/_shared/authentication.py
Labels: Storage

#27453 [ML][Pipelines] Enable AutoML DSL tests
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_automl_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_classification_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_forecasting_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_regression_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_text_classification_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_text_classification_multilabel_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_text_ner_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_multiclass_node_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_multilabel_node_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_od_node_in_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_automl_dsl_pipeline.pyTestAutomlDSLPipelinetest_automl_vision_segmentation_node_in_pipeline.json
Labels: ML-Pipelines

#27492 fix non-pipeline-input with annotation and default value
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
Labels: ML-Pipelines

#27455 Sync eng/common directory with azure-sdk-tools for PR 4628
  eng/common/scripts/Create-APIReview.ps1
  eng/common/scripts/Helpers/ApiView-Helpers.ps1
  eng/common/scripts/Prepare-Release.ps1
Labels: EngSys, Central-EngSys

#27571 Sync eng/common directory with azure-sdk-tools for PR 4728
  eng/common/scripts/Helpers/Metadata-Helpers.ps1
Labels: EngSys, Central-EngSys

#26155 [Test Proxy] Add error response when start test proxy
  tools/azure-sdk-tools/devtools_testutils/proxy_startup.py
Labels: customer-reported

#27573 Enforce Package name approval for preview release
  eng/scripts/Create-ApiReview.ps1
Labels: Central-EngSys

#27486 [TA] regen on latest spec
  sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_models_py3.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_text_analytics_client_enums.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/swagger/README.md
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze.pyTestAnalyzetest_autodetect_lang_document.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_analyze_async.pyTestAnalyzeAsynctest_autodetect_lang_document.json
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
Labels: Cognitive - Text Analytics

#27583 Increment version for textanalytics releases
  sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_version.py
Labels: auto-merge

#27535 [ML][Pipelines]ci: enable test_dump_distribution
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py
Labels: ML-Pipelines

#27540 [ML][Pipelines] Enable Pipelines owned skip tests
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/internal/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/_util.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_component_create_get_list_from_registry.json
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_component_list.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_parallel_job.json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[0-ls_command_component.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[1-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[2-batch_score.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[3-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[4-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[5-component.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[6-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[7-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[8-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_parallel_job[file_component_input_e2e.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_parallel_job[file_input_e2e.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_parallel_job[tabular_input_e2e.yml].json
Labels: ML-Pipelines

#27539 [Pipeline] Convert mldesigner primitive annotation to Input type
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
Labels: ML-Pipelines

#27587 [ML][Pipelines] Fix NodeOutput bool test in download
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
Labels: ML-Pipelines

#27605 [MA] skip feedback tests
  sdk/metricsadvisor/azure-ai-metricsadvisor/tests/async_tests/test_metrics_advisor_client_live_async.py
  sdk/metricsadvisor/azure-ai-metricsadvisor/tests/test_metrics_advisor_client_live.py
Labels: Cognitive - Metrics Advisor

#27591 Sync eng/common directory with azure-sdk-tools for PR 4746
  eng/common/scripts/git-branch-push.ps1
Labels: EngSys, Central-EngSys

#27599 [ML][Pipelines] Fix sweep job optional input cannot be empty
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/sweep.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_schema.py
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[0-input_basic.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[1-input_literal_cross_type.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[10-run_settings_sweep_choice.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[11-run_settings_sweep_limits.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[2-input_literal_meta.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[3-input_path.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[4-input_path_concatenate.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[5-input_reason_expression.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[6-input_string_concatenate.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[7-run_settings_compute.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[8-run_settings_literal.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_data_binding_expression[9-run_settings_sweep_literal.yml].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict0].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict1].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict2].json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_sweep_node_early_termination_policy[policy_yaml_dict3].json
  sdk/ml/azure-ai-ml/tests/test_configs/components/helloworld_component_optional_input.yml
Labels: ML-Pipelines

#27494 [ML][Pipeline] Support schedule spark job
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/schedule/create_job.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/schedule/schedule.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
  sdk/ml/azure-ai-ml/tests/recordings/schedule/e2etests/test_schedule.pyTestScheduletest_spark_job_schedule.json
  sdk/ml/azure-ai-ml/tests/schedule/e2etests/test_schedule.py
  sdk/ml/azure-ai-ml/tests/schedule/unittests/test_schedule_entity.py
  sdk/ml/azure-ai-ml/tests/test_configs/schedule/local_cron_spark_job.yml
  sdk/ml/azure-ai-ml/tests/test_configs/schedule/local_cron_spark_job2.yml
Labels: ML-Pipelines

#27001 [dsl.pipeline] Pipeline support variable args as pipeline input
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/exceptions.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_component_operations.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
Labels: ML-Pipelines

#27619 [BUG] Support submits spark pipeline with reference component
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job_entry_mixin.py
Labels: ML-Pipelines

#27638 [ML][Pipelines] Always cancel submitted pipeline jobs
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/test_utilities/utils.py
Labels: ML-Pipelines

#27628 [TA] remove pinning specific model_version in tests
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities.pyTestRecognizeEntitiestest_all_successful_passing_dict.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities.pyTestRecognizeEntitiestest_all_successful_passing_text_document_input.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities_async.pyTestRecognizeEntitiestest_all_successful_passing_dict.json
  sdk/textanalytics/azure-ai-textanalytics/tests/recordings/test_recognize_entities_async.pyTestRecognizeEntitiestest_all_successful_passing_text_document_input.json
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_healthcare_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_recognize_entities_async.py
Labels: Cognitive - Text Analytics

#27643 [ML][Pipelines]Support parallel-for with subgraph
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/parallel_for.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/base.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/mixin.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_subgraph_unprovided_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_subgraph.json
Labels: ML-Pipelines

#27538 add component latest_version when running 'az ml component list -o table'
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_component_operations.py
Labels: ML-Pipelines

#27653 [ML][Pipelines] Avoid bool test for pipeline expression in non-pipeline scenarios
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_expression.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_io_builder.py
Labels: ML-Pipelines

#27568 Updating CODEOWNERS for Communication Identity & Common Packages
  .github/CODEOWNERS
Labels: Communication - Common, Communication - Identity

#27662 Enable test_command_job_with_invalid_mode_type_in_pipeline_deserialize
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/invalid/with_invalid_job_input_type_mode.json
Labels: ML-Pipelines

#27651 [ML][Pipelines] Update CHANGELOG
  sdk/ml/azure-ai-ml/CHANGELOG.md
Labels: ML-Pipelines

#27677 [Component] Additional includes support azure devops artifacts
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_artifact_cache.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py
  sdk/ml/azure-ai-ml/tests/test_configs/internal/component_with_additional_includes/artifacts_additional_includes_with_conflict.additional_includes
  sdk/ml/azure-ai-ml/tests/test_configs/internal/component_with_additional_includes/artifacts_additional_includes_with_conflict.yml
  sdk/ml/azure-ai-ml/tests/test_configs/internal/component_with_additional_includes/with_artifacts.additional_includes
  sdk/ml/azure-ai-ml/tests/test_configs/internal/component_with_additional_includes/with_artifacts.yml
Labels: ML-Pipelines

#27655 [Bug] Update validation for node entry in spark
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/spark.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/spark_job_entry_mixin.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_entity.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline_samples.pyTestDSLPipelineSamplestest_spark_job_with_builder_in_pipeline_without_entry.json
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/spark_job_in_pipeline/invalid_pipeline.py
Labels: ML-Pipelines

#27709 [Storage] Fix shard tests for changefeed
  sdk/storage/azure-storage-blob-changefeed/tests/recordings/test_change_feed.pyTestStorageChangeFeedtest_list_3_shards_events_works_with_1_shard_cursor.json
  sdk/storage/azure-storage-blob-changefeed/tests/recordings/test_change_feed.pyTestStorageChangeFeedtest_read_3_shards_change_feed_during_a_time_range_in_multiple_times_gives_same_result_as_reading_all.json
  sdk/storage/azure-storage-blob-changefeed/tests/recordings/test_change_feed.pyTestStorageChangeFeedtest_read_change_feed_tail_where_3_shards_have_data.json
  sdk/storage/azure-storage-blob-changefeed/tests/recordings/test_change_feed.pyTestStorageChangeFeedtest_read_change_feed_tail_where_only_1_shard_has_data.json
  sdk/storage/azure-storage-blob-changefeed/tests/recordings/test_change_feed.pyTestStorageChangeFeedtest_read_change_feed_with_3_shards_in_a_time_range.json
  sdk/storage/azure-storage-blob-changefeed/tests/test_change_feed.py
Labels: Storage

#27706 [Storage] Fix flaky upload tests
  sdk/storage/azure-storage-blob/tests/test_common_blob.py
  sdk/storage/azure-storage-blob/tests/test_common_blob_async.py
Labels: Storage

#27713 Increment version for ml releases
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
Labels: auto-merge

#27716 [ML][Pipelines] Skip parallel_for live test
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
Labels: ML-Pipelines

#27707 [Storage] Cleanup old test classes after test proxy migration
  sdk/storage/azure-storage-queue/tests/test_queue_service_stats.py
  tools/azure-sdk-tools/devtools_testutils/storage/__init__.py
  tools/azure-sdk-tools/devtools_testutils/storage/aio/__init__.py
  tools/azure-sdk-tools/devtools_testutils/storage/aio/asynctestcase.py
  tools/azure-sdk-tools/devtools_testutils/storage/testcase.py
Labels: Storage

#27725 Making attachments paths in email samples absolute
  sdk/communication/azure-communication-email/samples/send_email_with_attachments_sample.py
  sdk/communication/azure-communication-email/samples/send_email_with_attachments_sample_async.py
Labels: Communication

#27723 [Storage] Use `tempfile` for datalake package
  sdk/storage/azure-storage-file-datalake/tests/test_file.py
  sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
Labels: Storage

#27717 [InternalComponent] Add is_link_mode to internal component output
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_input_outputs.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/command.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/test_configs/internal/component_with_input_outputs/component_spec_with_attrs.yaml
Labels: ML-Pipelines

#27737 feat: support @1-preview & @1-legacy for InternalComponent
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/test_configs/internal/command-mode/legacy_distributed_component.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/internal/command-mode/preview_command_component.yaml
Labels: ML-Pipelines

#27754 Matrix Gen Stress Tests
  sdk/eventhub/azure-eventhub/stress/.gitignore
  sdk/eventhub/azure-eventhub/stress/.helmignore
  sdk/eventhub/azure-eventhub/stress/Chart.lock
  sdk/eventhub/azure-eventhub/stress/Chart.yaml
  sdk/eventhub/azure-eventhub/stress/Dockerfile38
  sdk/eventhub/azure-eventhub/stress/scenarios-matrix.yaml
  sdk/eventhub/azure-eventhub/stress/templates/testjob.yaml
  sdk/eventhub/azure-eventhub/stress/values.yaml
Labels: Event Hubs
