Repository Azure/azure-sdk-for-python, pull requests merged in 2023-02, with the labels that each got.

#28568 Sync eng/common directory with azure-sdk-tools for PR 4812
  eng/common/pipelines/templates/steps/cosmos-emulator.yml
  eng/common/scripts/Cosmos-Emulator.ps1
Labels: EngSys, Central-EngSys

#28559 Revert PR #27960
  sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_fileshare_storage_helper.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/code.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/code.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
  sdk/ml/azure-ai-ml/tests/internal/_utils.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_asset_utils.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_get_content_hash.py
Labels: Machine Learning

#28561 [Storage] Fix Datalake rename operations when new name contains `?`
  .vscode/cspell.json
  sdk/storage/azure-storage-file-datalake/CHANGELOG.md
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_directory_client.py
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_data_lake_file_client.py
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_path_client.py
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_directory_client_async.py
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_data_lake_file_client_async.py
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory.pyTestDirectorytest_rename_directory_special_chars.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory_async.pyTestDirectoryAsynctest_rename_directory_special_chars.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.pyTestFiletest_rename_file_different_filesystem_with_sas.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.pyTestFiletest_rename_file_special_chars.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.pyTestFileAsynctest_rename_file_different_filesystem_with_sas.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.pyTestFileAsynctest_rename_file_special_chars.json
  sdk/storage/azure-storage-file-datalake/tests/test_directory.py
  sdk/storage/azure-storage-file-datalake/tests/test_directory_async.py
  sdk/storage/azure-storage-file-datalake/tests/test_file.py
  sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
Labels: Storage

#28540 Add more e2e parameters test cases for aml workspace update operation
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_workspace_operations.py
  sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_uai_workspace_create_update_and_delete.json
  sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_update_sai_to_sai_and_uai_workspace_with_uai_deletion.json
  sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_workspace_create_update_and_delete.json
  sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace.pyTestWorkspacetest_workspace_diagnosis.json
  sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace.py
Labels: Machine Learning, ML-Workspace

#28580 Cleanup changelog
  sdk/search/azure-search-documents/CHANGELOG.md
Labels: Search

#28581 Fix the missing return type
  sdk/core/azure-core/azure/core/tracing/_abstract_span.py
Labels: Azure.Core

#28539 Add path erroneously removed from `CODEOWNERS`
  .github/CODEOWNERS
Labels: Central-EngSys

#28585 Fix typos in calling ValidationException and allow target to be over-writeable in UserException
  sdk/ml/azure-ai-ml/azure/ai/ml/exceptions.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
Labels: Machine Learning, ML-Assets

#28536 Added `WorkloadIdentityCredential`
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/azure/identity/__init__.py
  sdk/identity/azure-identity/azure/identity/_constants.py
  sdk/identity/azure-identity/azure/identity/_credentials/__init__.py
  sdk/identity/azure-identity/azure/identity/_credentials/default.py
  sdk/identity/azure-identity/azure/identity/_credentials/managed_identity.py
  sdk/identity/azure-identity/azure/identity/_credentials/workload_identity.py
  sdk/identity/azure-identity/azure/identity/aio/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/__init__.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/default.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/managed_identity.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/token_exchange.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/workload_identity.py
  sdk/identity/azure-identity/images/mermaidjs/DefaultAzureCredentialAuthFlow.md
  sdk/identity/azure-identity/images/mermaidjs/DefaultAzureCredentialAuthFlow.svg
Labels: Azure.Identity

#28291 [TA] beta updates
  sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
  sdk/textanalytics/azure-ai-textanalytics/assets.json
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_dict_mixin.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_models_py3.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_generated/v2022_10_01_preview/models/_patch.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_abstract_summary_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_summary_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstract_summary.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_summary.py
  sdk/textanalytics/azure-ai-textanalytics/swagger/README.md
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_summarization.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_summarization_async.py
Labels: Cognitive - Text Analytics

#28554 Sync eng/common directory with azure-sdk-tools for PR 5291
  doc/dev/recording_migration_guide.md
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
  eng/ignore-links.txt
Labels: EngSys, Central-EngSys

#28590 Sync eng/common directory with azure-sdk-tools for PR 5313
  eng/common/TestResources/New-TestResources.ps1
Labels: EngSys, Central-EngSys

#28588 [ml] Support of Environment promotion from workspace to registry
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/assets/workspace_asset_reference.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/workspace_asset_reference.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_environment_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
  sdk/ml/azure-ai-ml/tests/environment/unittests/test_environment_operations.py
Labels: Machine Learning, ML-Assets

#28584 [ML] Update paramtype tags
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
Labels: Machine Learning, ML-Assets

#28576 [ML][Pipelines] Singularity: bypass operations to Singularity compute
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_arm_id_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_operation_orchestrator.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_singularity_compute.json
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/helloworld_pipeline_job_with_singularity_compute.yml
Labels: Machine Learning, ML-Pipelines

#28311 Increment version for synapse releases
  sdk/synapse/azure-synapse-artifacts/CHANGELOG.md
  sdk/synapse/azure-synapse-artifacts/azure/synapse/artifacts/_version.py
Labels: Synapse, auto-merge

#28603 [ML] Add docstrings to JobService class
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py
Labels: Machine Learning

#28599 [ML] Add docstrings to JobService class
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/job_service.py
Labels: Machine Learning

#28605 [ml] Cherry pick #28559
  sdk/ml/azure-ai-ml/azure/ai/ml/_artifacts/_fileshare_storage_helper.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_additional_includes.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/code.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/_asset_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/code.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
  sdk/ml/azure-ai-ml/tests/internal/_utils.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_asset_utils.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_get_content_hash.py
Labels: Machine Learning, ML-Assets

#28594 Sync eng/common directory with azure-sdk-tools for PR 5318
  eng/common/testproxy/target_version.txt
Labels: EngSys, Central-EngSys

#28591 Sync eng/common directory with azure-sdk-tools for PR 5309
  eng/common/scripts/stress-testing/deploy-stress-tests.ps1
  eng/common/scripts/stress-testing/stress-test-deployment-lib.ps1
Labels: EngSys, Central-EngSys

#28606 Address the API Review comments for docstring.
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
Labels: Machine Learning, ML-Assets

#28505 [ML] Add Custom Applications to Compute Instances
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/custom_applications.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/setup_scripts.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_custom_applications.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
  sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-custom-app.yaml
Labels: Machine Learning

#28610 Sync eng/common directory with azure-sdk-tools for PR 5316
  eng/common/scripts/Helpers/Resource-Helpers.ps1
Labels: EngSys, Central-EngSys

#28611 [ML] Add Custom Applications to Compute Instances (#28505)
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute_instance.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/custom_applications.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/setup_scripts.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/_custom_applications.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
  sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-ci-custom-app.yaml
Labels: Machine Learning

#28613 [Storage] Fix datalake rename live tests
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory.pyTestDirectorytest_rename_dir_with_file_system_sas.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_directory_async.pyTestDirectoryAsynctest_rename_dir_with_file_system_sas.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_file.pyTestFiletest_rename_file_different_filesystem_with_sas.json
  sdk/storage/azure-storage-file-datalake/tests/recordings/test_file_async.pyTestFileAsynctest_rename_file_different_filesystem_with_sas.json
  sdk/storage/azure-storage-file-datalake/tests/test_directory.py
  sdk/storage/azure-storage-file-datalake/tests/test_directory_async.py
  sdk/storage/azure-storage-file-datalake/tests/test_file.py
  sdk/storage/azure-storage-file-datalake/tests/test_file_async.py
Labels: Storage

#28609 [Storage] Update release date for Storage release
  sdk/storage/azure-storage-blob/CHANGELOG.md
  sdk/storage/azure-storage-file-datalake/CHANGELOG.md
  sdk/storage/azure-storage-file-share/CHANGELOG.md
  sdk/storage/azure-storage-queue/CHANGELOG.md
Labels: Storage

#28616 Edit pass on Identity README
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/images/mermaidjs/DefaultAzureCredentialAuthFlow.md
  sdk/identity/azure-identity/images/mermaidjs/DefaultAzureCredentialAuthFlow.svg
Labels: Azure.Identity

#28619 Increment version for core releases
  sdk/core/azure-core/CHANGELOG.md
  sdk/core/azure-core/azure/core/_version.py
Labels: Azure.Core, auto-merge

#28627 [Tables] Fix failing tests in ci pipeline
  sdk/tables/azure-data-tables/assets.json
  sdk/tables/azure-data-tables/tests/_shared/asynctestcase.py
  sdk/tables/azure-data-tables/tests/_shared/testcase.py
  sdk/tables/azure-data-tables/tests/test_table_entity.py
  sdk/tables/azure-data-tables/tests/test_table_entity_async.py
Labels: Client, Tables

#28607 [QA] update readme to use correct deployment_name
  sdk/cognitivelanguage/azure-ai-language-questionanswering/README.md
Labels: Cognitive - QnA Maker

#28621 [ML] Clean up for Custom Applications on Compute Instances
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
Labels: Machine Learning

#28635 [ML] Clean up for Custom Applications on Compute Instances (#28621)
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
Labels: Machine Learning

#28638 [Storage] Bump versions for GA release
  sdk/storage/azure-storage-blob/CHANGELOG.md
  sdk/storage/azure-storage-blob/azure/storage/blob/_version.py
  sdk/storage/azure-storage-file-datalake/CHANGELOG.md
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/_version.py
  sdk/storage/azure-storage-file-datalake/setup.py
  sdk/storage/azure-storage-file-share/CHANGELOG.md
  sdk/storage/azure-storage-file-share/azure/storage/fileshare/_version.py
  sdk/storage/azure-storage-queue/CHANGELOG.md
  sdk/storage/azure-storage-queue/azure/storage/queue/_version.py
  shared_requirements.txt
Labels: Storage

#28645 [Test Proxy] Make `recorded_test` compatible with any pytest-asyncio version
  tools/azure-sdk-tools/devtools_testutils/proxy_fixtures.py
Labels: EngSys

#28624 Add VC get and list operations
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/azure_resource_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_virtual_cluster_operations.py
  sdk/ml/azure-ai-ml/setup.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_ml_client.py
  sdk/ml/azure-ai-ml/tests/recordings/virtual_cluster/e2etests/test_vc.pyTestVirtualClustertest_get_and_list.json
  sdk/ml/azure-ai-ml/tests/virtual_cluster/__init__.py
  sdk/ml/azure-ai-ml/tests/virtual_cluster/e2etests/__init__.py
  sdk/ml/azure-ai-ml/tests/virtual_cluster/e2etests/test_vc.py
  sdk/ml/azure-ai-ml/tests/virtual_cluster/unittests/__init__.py
  sdk/ml/azure-ai-ml/tests/virtual_cluster/unittests/test_vc_operations.py
Labels: Machine Learning

#28390 [ML][Pipelines] feat: handle corner serialization issues for internal components
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_setup.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_utils/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_utils/_yaml_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/internal/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_component.pyTestComponenttest_component_create[tests/test_configs/internal/ae365exepool-component/component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_component.pyTestComponenttest_component_load[tests/test_configs/internal/ae365exepool-component/component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_anonymous_internal_component[8-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/recordings/internal/e2etests/test_pipeline_job.pyTestPipelineJobtest_pipeline_job_with_registered_internal_component[8-component_spec.yaml].json
  sdk/ml/azure-ai-ml/tests/test_configs/internal/command-component-serialization-core-case/component_spec.yaml
  sdk/ml/azure-ai-ml/tests/test_configs/internal/loaded_from_rest/ae365exepool-component/component_spec.json
Labels: Machine Learning, ML-Pipelines

#28604 [ML][Pipelines] Add missing properties in schedule schema
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/schedule/schedule.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py
  sdk/ml/azure-ai-ml/tests/schedule/unittests/test_schedule_entity.py
Labels: Machine Learning, ML-Pipelines

#28548 Fix duplicate error msg bug for CLI marshmallow errors
  sdk/ml/azure-ai-ml/azure/ai/ml/_exception_helper.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline_samples.py
  sdk/ml/azure-ai-ml/tests/job_common/unittests/test_job_operations.py
Labels: Machine Learning

#28658 [DT] fix flaky cancel test for translation
  sdk/translation/azure-ai-translation-document/assets.json
  sdk/translation/azure-ai-translation-document/tests/test_cancel_translation.py
  sdk/translation/azure-ai-translation-document/tests/test_cancel_translation_async.py
Labels: Cognitive - Translator

#28667 [AppConfig] Prepare release
  sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py
  sdk/appconfiguration/azure-appconfiguration/setup.py
Labels: Client, App Configuration

#28656 [Cosmos] Test changes for failing pipelines
  sdk/cosmos/azure-cosmos/test/test_config.py
Labels: Cosmos

#28671 Increment version for ml releases
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
Labels: Machine Learning, auto-merge

#28669 Increment version for monitor releases
  sdk/monitor/azure-monitor-opentelemetry-exporter/CHANGELOG.md
  sdk/monitor/azure-monitor-opentelemetry-exporter/azure/monitor/opentelemetry/exporter/_version.py
Labels: auto-merge

#28666 [Tables] Prepare release
  sdk/tables/azure-data-tables/CHANGELOG.md
Labels: Client, Tables

#28653 Replace `_arg_name` with `_port_name` for Input and Output
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_component/pipeline_component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/utils.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_group.py
  sdk/ml/azure-ai-ml/tests/recordings/command_job/e2etests/test_command_job.pyTestCommandJobtest_command_job_register_output.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_register_output_yaml.json
Labels: Machine Learning, ML-Assets

#28676 [Cosmos] more issues with 409s in tests
  sdk/cosmos/azure-cosmos/test/test_env.py
  sdk/cosmos/azure-cosmos/test/test_headers.py
Labels: Cosmos

#28528 Adding in some functionality to use different clouds
  sdk/ml/azure-ai-ml/azure/ai/ml/_azure_environments.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_cloud_environments.py
Labels: Machine Learning, customer-reported

#28677 Increment version for identity releases
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/azure/identity/_version.py
Labels: Azure.Identity, auto-merge

#28679 Increment version for appconfiguration releases
  sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py
Labels: App Configuration, auto-merge

#28553 [ML] Bumping unreleased version to 1.5.0
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_version.py
Labels: Machine Learning

#28678 Increment version for search releases
  sdk/search/azure-search-documents/CHANGELOG.md
  sdk/search/azure-search-documents/azure/search/documents/_version.py
Labels: Search, auto-merge

#28684 Increment version for tables releases
  sdk/tables/azure-data-tables/CHANGELOG.md
  sdk/tables/azure-data-tables/azure/data/tables/_version.py
Labels: Tables, auto-merge

#28622 Restore Eng Sys rules in `CODEOWNERS` + assorted fixes
  .github/CODEOWNERS
Labels: Central-EngSys

#28690 Increment version for monitor releases
  sdk/monitor/azure-monitor-query/CHANGELOG.md
  sdk/monitor/azure-monitor-query/azure/monitor/query/_version.py
Labels: auto-merge

#28520 [ML][Pipelines] do-while: support while True scenario
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/job_limits.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/control_flow_job.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_do_while.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/do_while.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_control_flow_pipeline.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_controlflow_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestDoWhiletest_pipeline_with_do_while_node.json
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/control_flow/do_while/invalid_pipeline.yml
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/control_flow/do_while/pipeline.yml
Labels: Machine Learning, ML-Pipelines, ML-Jobs

#28692 [ML][Pipelines] ci fix: server-side return original name/version for anonymous component
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
  sdk/ml/azure-ai-ml/tests/recordings/component/e2etests/test_component.pyTestComponenttest_anonymous_registration_from_load_component.json
Labels: Machine Learning, ML-Pipelines

#28371 Add supports for data assets in Registry
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/_artifacts/data.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_data_operations.py
  sdk/ml/azure-ai-ml/tests/conftest.py
  sdk/ml/azure-ai-ml/tests/dataset/e2etests/test_data.py
  sdk/ml/azure-ai-ml/tests/dataset/unittests/test_data_operations.py
  sdk/ml/azure-ai-ml/tests/recordings/dataset/e2etests/test_data.pyTestDatatest_create_data_asset_in_registry.json
  sdk/ml/azure-ai-ml/tests/recordings/dataset/e2etests/test_data.pyTestDatatest_data_get_latest_label_in_registry.json
  sdk/ml/azure-ai-ml/tests/recordings/dataset/e2etests/test_data.pyTestDatatest_list_data_in_registry.json
Labels: Machine Learning

#28683 [ML] Update changelog to include added dependencies
  sdk/ml/azure-ai-ml/CHANGELOG.md
Labels: Machine Learning

#28661 [ML]: Update the path in the admonition example and minor docstring issues.
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/samples/ml_samples_authentication_sovereign_cloud.py
Labels: Machine Learning

#28689 [Feature store] Update machine learning services rest client version v2022_12_01_preview
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/_azure_machine_learning_workspaces_enums.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/_models.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_restclient/v2022_12_01_preview/models/_models_py3.py
  sdk/ml/azure-ai-ml/swagger/machinelearningservices/resource-manager/Microsoft.MachineLearningServices/preview/2022-12-01-preview/machineLearningServices.json
Labels: Machine Learning

#28620 [TA] add NER resolutions sample
  sdk/textanalytics/azure-ai-textanalytics/README.md
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/samples/README.md
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entity_resolutions_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entity_resolutions.py
Labels: Cognitive - Text Analytics

#28685 Trigger `keyvault` when proxy updates
  sdk/keyvault/ci.yml
Labels: Central-EngSys

#28695 [ML][Pipelines] fix: parse default for boolean inputs for internal components
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/code.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_utils/utils.py
  sdk/ml/azure-ai-ml/tests/internal/unittests/test_component.py
  sdk/ml/azure-ai-ml/tests/internal_utils/unittests/test_utils.py
  sdk/ml/azure-ai-ml/tests/test_configs/internal/command-component-serialization-core-case/component_spec.yaml
Labels: Machine Learning, ML-Pipelines

#28708 [ML][Pipeline] Refine test for live mode
  sdk/ml/azure-ai-ml/tests/component/e2etests/test_component.py
Labels: Machine Learning, ML-Pipelines

#28701 [EH] remove node-selector stress
  sdk/eventhub/azure-eventhub/stress/templates/testjob.yaml
Labels: Event Hubs

#28711 [TA] unified letter cases in sdk/textanalytics/azure-ai-textanalytics/README.md
  sdk/textanalytics/azure-ai-textanalytics/README.md
Labels: customer-reported, Cognitive - Text Analytics

#28714 [AppConfig] Prepare release
  sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py
  sdk/appconfiguration/azure-appconfiguration/setup.py
Labels: Client, App Configuration

#28715 Fix uppercase handling of deployment name under traffic/mirror_traffic
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_endpoint_operations.py
  sdk/ml/azure-ai-ml/tests/online_services/unittests/test_online_endpoints.py
Labels: Machine Learning, ML-Inference

#28399 [Service Bus] Performance Tests
  sdk/servicebus/azure-servicebus/tests/perf_tests/T1_legacy_tests/__init__.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/T1_legacy_tests/_test_base.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/T1_legacy_tests/receive_message_batch.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/T1_legacy_tests/send_message.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/T1_legacy_tests/send_message_batch.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/T1_legacy_tests/t1_test_requirements.txt
  sdk/servicebus/azure-servicebus/tests/perf_tests/_test_base.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/receive_message_batch.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/receive_queue_message_batch.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/receive_queue_message_stream.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/receive_subscription_message_batch.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/receive_subscription_message_stream.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/send_message.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/send_message_batch.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/send_queue_message.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/send_queue_message_batch.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/send_topic_message.py
  sdk/servicebus/azure-servicebus/tests/perf_tests/send_topic_message_batch.py
  sdk/servicebus/perf-resources.bicep
Labels: Service Bus

#28491 payload logging model data collector development
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/data_asset_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/data_collector_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/deployment_collection_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/event_hub_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/online_deployment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/oversize_data_config_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/payload_response_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/sampling_strategy_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_asset.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_collector.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/deployment_collection.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/destination.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/event_hub.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/online_deployment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/oversize_data_config.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/payload_response.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/sampling_strategy.py
Labels: Machine Learning, ML-Inference, ML-Assets

#28705 [TA] rename abstract -> abstractive
  sdk/textanalytics/azure-ai-textanalytics/CHANGELOG.md
  sdk/textanalytics/azure-ai-textanalytics/README.md
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/__init__.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_models.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_response_handlers.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_text_analytics_client.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/_validate.py
  sdk/textanalytics/azure-ai-textanalytics/azure/ai/textanalytics/aio/_text_analytics_client_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/README.md
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_abstractive_summary_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_actions_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_action_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_dynamic_classification_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_summary_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_model_version_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_multi_label_classify_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_custom_entities_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_single_label_classify_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstractive_summary.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_actions.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_action.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_dynamic_classification.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_summary.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_model_version.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_multi_label_classify.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_custom_entities.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_single_label_classify.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_analyze_async.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_summarization.py
  sdk/textanalytics/azure-ai-textanalytics/tests/test_summarization_async.py
Labels: Cognitive - Text Analytics

#28723 Sync eng/common directory with azure-sdk-tools for PR 5083
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#28462 [Perf] Refactor tests.yml into one file per package per language
  eng/pipelines/templates/jobs/perf.yml
  sdk/eventhub/perf-tests.yml
  sdk/eventhub/perf.yml
  sdk/keyvault/azure-keyvault-secrets/perf-tests.yml
  sdk/storage/azure-storage-blob/perf-tests.yml
  sdk/storage/azure-storage-blob/perf.yml
  sdk/storage/azure-storage-file-datalake/perf-tests.yml
  sdk/storage/azure-storage-file-datalake/perf.yml
  sdk/storage/azure-storage-file-share/perf-tests.yml
  sdk/storage/azure-storage-file-share/perf.yml
Labels: Storage

#28310 [ML][Pipelines] Feature: support serverless compute in pipeline job
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_common.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/_util.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/unittests/test_pipeline_job_validate.py
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/serverless_compute/component.yml
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/serverless_compute/none_pipeline_default_compute_invalid/pipeline.yml
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/serverless_compute/none_pipeline_default_compute_invalid/pipeline_component.yml
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/serverless_compute/none_pipeline_default_compute_valid/pipeline.yml
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/serverless_compute/none_pipeline_default_compute_valid/pipeline_component.yml
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/serverless_compute/serverless_pipeline_default_compute_valid/pipeline.yml
  sdk/ml/azure-ai-ml/tests/test_configs/pipeline_jobs/serverless_compute/serverless_pipeline_default_compute_valid/pipeline_component.yml
Labels: Machine Learning, ML-Pipelines, ML-Assets

#28675 [Internal] Enable ui_widget type as internal component input type
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_input_outputs.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_mldesigner/_constants.py
Labels: Machine Learning, ML-Pipelines

#28741 [AppConfig] Fix parameter types
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_azure_appconfiguration_client.py
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_models.py
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_sync_token.py
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_azure_configuration_client_async.py
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/aio/_sync_token_async.py
Labels: Client, App Configuration

#28687 Address `specific python version` warning that our CI jobs have been seeing
  eng/pipelines/templates/stages/platform-matrix.json
  scripts/devops_tasks/install_python_version.py
Labels: Central-EngSys

#28612 Local `tox` checks do not skip
  eng/pipelines/templates/jobs/ci.tests.yml
  eng/pipelines/templates/steps/analyze.yml
  eng/tox/run_bandit.py
  eng/tox/run_mypy.py
  eng/tox/run_pylint.py
  eng/tox/run_pyright.py
  eng/tox/run_verifytypes.py
  scripts/devops_tasks/set_tox_environment.py
  scripts/devops_tasks/tox_harness.py
  sdk/template/azure-template/pyproject.toml
  tools/azure-sdk-tools/ci_tools/ci_interactions.py
  tools/azure-sdk-tools/ci_tools/environment_exclusions.py
  tools/azure-sdk-tools/ci_tools/functions.py
  tools/azure-sdk-tools/ci_tools/variables.py
Labels: EngSys, Central-EngSys

#28736 [ML][Pipelines]Add source in controlflow nodes
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/pipeline/pipeline_component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_component.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/control_flow_node.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_control_flow_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_do_while_combined_if_else.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_dsl_condition_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_dsl_condition_pipeline_with_one_branch.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_dsl_condition_pipeline_with_primitive_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_dsl_parallel_for_pipeline_unprovided_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_subgraph_unprovided_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_asset_items.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_empty_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_port_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_primitive_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_subgraph.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_simple_dsl_parallel_for_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestControlFLowPipelineComponenttest_foreach.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestControlFLowPipelineComponenttest_if_else.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestDoWhiletest_do_while_pipeline_with_primitive_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestDoWhiletest_pipeline_with_do_while_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_happy_path_if_else.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_if_else_literal_condition.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_if_else_one_branch.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_assets_in_items.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_output_binding_foreach_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_path_on_datastore_in_items.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_simple_foreach_dict_item.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_simple_foreach_list_item.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_simple_foreach_string_item.json
Labels: Machine Learning, ML-Pipelines

#28770 [ML][Pipelines] Validate pipeline node IO name on reserved word
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_job/pipeline.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_keyword_in_node_io/downstream_node.yml
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_keyword_in_node_io/inner_node.yml
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_keyword_in_node_io/pipeline.py
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_keyword_in_node_io/upstream_node.yml
Labels: Machine Learning, ML-Pipelines

#28763 [AppConfig] Update release date
  sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
Labels: Client, App Configuration

#28755 Sync eng/common directory with azure-sdk-tools for PR 5412
  eng/common/scripts/copy-docs-to-blobstorage.ps1
Labels: EngSys, Central-EngSys

#28777 Correct use of time_stamp/timeStamp in metrics client. Fixes #28768
  sdk/monitor/azure-monitor-query/azure/monitor/query/_models.py
Labels: customer-reported

#28787 Increment version for appconfiguration releases
  sdk/appconfiguration/azure-appconfiguration/CHANGELOG.md
  sdk/appconfiguration/azure-appconfiguration/azure/appconfiguration/_version.py
Labels: App Configuration, auto-merge

#28769 [ML][Pipeline] Fix is_control field type for registered component
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_do_while_combined_if_else.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_dsl_condition_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_dsl_condition_pipeline_with_one_branch.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_dsl_condition_pipeline_with_primitive_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_registered_component_is_control.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_dsl_parallel_for_pipeline_unprovided_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_subgraph_unprovided_input.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_asset_items.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_empty_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_port_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_primitive_outputs.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_parallel_for_pipeline_with_subgraph.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestParallelForPipelinetest_simple_dsl_parallel_for_pipeline.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestControlFLowPipelineComponenttest_foreach.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestControlFLowPipelineComponenttest_if_else.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestDoWhiletest_do_while_pipeline_with_primitive_inputs.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestDoWhiletest_pipeline_with_do_while_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_happy_path_if_else.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_if_else_literal_condition.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestIfElsetest_if_else_one_branch.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_assets_in_items.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_output_binding_foreach_node.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_path_on_datastore_in_items.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_simple_foreach_dict_item.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_simple_foreach_list_item.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_control_flow_pipeline.pyTestParallelFortest_simple_foreach_string_item.json
Labels: Machine Learning, ML-Pipelines

#28795 Sync eng/common directory with azure-sdk-tools for PR 5427
  eng/common/scripts/Cadl-Project-Sync.ps1
Labels: EngSys, Central-EngSys

#28707 Support register NodeOutput
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/input.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_inputs_outputs/output.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/mixin.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_pipeline_job_helpers.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/pipeline_job/e2etests/test_pipeline_job.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_register_output_sdk.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_register_output_sdk_succeed.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_register_output_yaml.json
  sdk/ml/azure-ai-ml/tests/recordings/pipeline_job/e2etests/test_pipeline_job.pyTestPipelineJobtest_register_output_yaml_succeed.json
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/pipeline_with_pipeline_component/pipeline_register_output.yml
Labels: Machine Learning, ML-Pipelines

#28420 [Cosmos] Adds cross regional retries for Service Unavailable/Request Timeouts
  sdk/cosmos/azure-cosmos/CHANGELOG.md
  sdk/cosmos/azure-cosmos/azure/cosmos/_retry_utility.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_timeout_failover_retry_policy.py
  sdk/cosmos/azure-cosmos/test/test_retry_policy.py
Labels: Cosmos

#28759 Correct logic in `install_python_version.py`
  scripts/devops_tasks/install_python_version.py
Labels: Central-EngSys

#28794 Increment version for monitor releases
  sdk/monitor/azure-monitor-query/CHANGELOG.md
  sdk/monitor/azure-monitor-query/azure/monitor/query/_version.py
Labels: auto-merge

#28803 Sync eng/common directory with azure-sdk-tools for PR 5437
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#28810 `archetype-sdk-tests` analysis stage needs renaming
  eng/pipelines/templates/stages/archetype-sdk-tests.yml
Labels: Central-EngSys

#28716 [TA] move import inside code snippet
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_abstractive_summary_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_alternative_document_input_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_actions_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_action_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_entities_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_healthcare_entities_with_cancellation_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_analyze_sentiment_with_opinion_mining_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_authentication_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_detect_language_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_dynamic_classification_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_key_phrases_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_extract_summary_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_get_detailed_diagnostics_information_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_model_version_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_multi_label_classify_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_custom_entities_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_entities_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_linked_entities_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_recognize_pii_entities_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/async_samples/sample_single_label_classify_async.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_abstractive_summary.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_alternative_document_input.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_actions.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_action.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_entities.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_healthcare_entities_with_cancellation.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_analyze_sentiment_with_opinion_mining.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_authentication.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_detect_language.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_dynamic_classification.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_key_phrases.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_extract_summary.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_get_detailed_diagnostics_information.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_model_version.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_multi_label_classify.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_custom_entities.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_entities.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_linked_entities.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_recognize_pii_entities.py
  sdk/textanalytics/azure-ai-textanalytics/samples/sample_single_label_classify.py
Labels: Cognitive - Text Analytics

#28816 disable_instance_discovery
  sdk/identity/azure-identity/CHANGELOG.md
  sdk/identity/azure-identity/azure/identity/_internal/msal_credentials.py
  sdk/identity/azure-identity/tests/test_device_code_credential.py
  sdk/identity/azure-identity/tests/test_instance_discovery.py
  sdk/identity/azure-identity/tests/test_username_password_credential.py
Labels: Azure.Identity

#28808 [ML][Pipeline] Fix primitive pipeline component output
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_schema/input_output.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/_utils/_utils.py
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_registered_component_is_control.json
Labels: ML-Pipelines

#28806 [ML][Pipelines] Support output setting copy in SDK
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_component_builder.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_builders/pipeline.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/base.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/_io/mixin.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_job/pipeline/pipeline_job.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_util.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline_with_specific_nodes.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_command_function.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_dsl_pipeline_with_only_setting_binding_node.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_dsl_pipeline_with_setting_binding_node_and_pipeline_level.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_output_setting_path.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_parallel_run_function.json
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_dsl_pipeline.pyTestDSLPipelinetest_pipeline_component_output_setting.json
Labels: Machine Learning, ML-Pipelines

#28828 Sync eng/common directory with azure-sdk-tools for PR 5456
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#28834 [ML][Pipelines] feat: support use a single output node as sub-pipeline input
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_pipeline_decorator.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_pipeline_builder.py
  sdk/ml/azure-ai-ml/tests/test_configs/components/helloworld_component_multi_outputs.yml
Labels: Machine Learning, ML-Pipelines

#28752 Add Tags Support to Compute
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/compute/compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/aml_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/compute_instance.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/kubernetes_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/synapsespark_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/unsupported_compute.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_compute/virtual_machine_compute.py
  sdk/ml/azure-ai-ml/tests/compute/unittests/test_compute_entity.py
  sdk/ml/azure-ai-ml/tests/test_configs/compute/compute-aml.yaml
Labels: Machine Learning

#28813 Register Data Asset data storage online deployment
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/_deployment/online/data_asset_schema.py
  sdk/ml/azure-ai-ml/azure/ai/ml/constants/_deployment.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_deployment/data_asset.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
Labels: Machine Learning, ML-Inference, ML-Assets

#28830 [Perf] Add parameter TimeoutInMinutes, Increase timeout for storage-blob-perf to 12 hours
  eng/pipelines/templates/jobs/perf.yml
  sdk/storage/azure-storage-blob/perf.yml
Labels: Storage

#28829 Disable pylint in azure-template
  sdk/template/azure-template/pyproject.toml
Labels: EngSys

#28756 Resolve `black` not running properly in CI
  eng/pipelines/templates/steps/run_black.yml
  scripts/devops_tasks/validate_formatting.py
Labels: Central-EngSys

#28403 [ACR] Add OCI manifest and blob upload/download samples
  sdk/containerregistry/azure-containerregistry/samples/README.md
  sdk/containerregistry/azure-containerregistry/samples/sample_delete_images.py
  sdk/containerregistry/azure-containerregistry/samples/sample_delete_tags.py
  sdk/containerregistry/azure-containerregistry/samples/sample_hello_world.py
  sdk/containerregistry/azure-containerregistry/samples/sample_list_tags.py
  sdk/containerregistry/azure-containerregistry/samples/sample_set_image_properties.py
  sdk/containerregistry/azure-containerregistry/samples/sample_upload_download_blob.py
  sdk/containerregistry/azure-containerregistry/samples/sample_upload_download_manifest.py
Labels: Container Registry, Client

#28815 [Storage] Fix docstring typo
  sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
Labels: Storage

#28751 Enable CodeQL for scheduled CI jobs
  eng/pipelines/templates/jobs/ci.yml
  eng/pipelines/templates/stages/archetype-sdk-client.yml
  eng/pipelines/templates/stages/cosmos-sdk-client.yml
  eng/pipelines/templates/variables/globals.yml
Labels: Central-EngSys

#28812 App Config Min Feature Flags + Change Log and Readme Updated
  sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
  sdk/appconfiguration/azure-appconfiguration-provider/README.md
  sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_azureappconfigurationprovider.py
  sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_constants.py
  sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/aio/_azureappconfigurationproviderasync.py
  sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider.py
  sdk/appconfiguration/azure-appconfiguration-provider/tests/test_async_provider_aad.py
  sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider.py
  sdk/appconfiguration/azure-appconfiguration-provider/tests/test_provider_aad.py
Labels: App Configuration

#28786 [ml] support model next version for registry assets
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_model_operations.py
  sdk/ml/azure-ai-ml/tests/environment/e2etests/test_environment.py
  sdk/ml/azure-ai-ml/tests/environment/unittests/test_environment_operations.py
  sdk/ml/azure-ai-ml/tests/model/e2etests/test_model.py
  sdk/ml/azure-ai-ml/tests/model/unittests/test_model_operations.py
Labels: Machine Learning, ML-Assets

#28095 [Tables] Update method type hints to Python3 syntax
  sdk/tables/azure-data-tables/azure/data/tables/_authentication.py
  sdk/tables/azure-data-tables/azure/data/tables/_base_client.py
  sdk/tables/azure-data-tables/azure/data/tables/_deserialize.py
  sdk/tables/azure-data-tables/azure/data/tables/_entity.py
  sdk/tables/azure-data-tables/azure/data/tables/_models.py
  sdk/tables/azure-data-tables/azure/data/tables/_policies.py
  sdk/tables/azure-data-tables/azure/data/tables/_serialize.py
  sdk/tables/azure-data-tables/azure/data/tables/_shared_access_signature.py
  sdk/tables/azure-data-tables/azure/data/tables/_table_batch.py
  sdk/tables/azure-data-tables/azure/data/tables/_table_client.py
  sdk/tables/azure-data-tables/azure/data/tables/_table_service_client.py
  sdk/tables/azure-data-tables/azure/data/tables/_table_shared_access_signature.py
  sdk/tables/azure-data-tables/azure/data/tables/aio/_authentication_async.py
  sdk/tables/azure-data-tables/azure/data/tables/aio/_base_client_async.py
  sdk/tables/azure-data-tables/azure/data/tables/aio/_policies_async.py
  sdk/tables/azure-data-tables/azure/data/tables/aio/_table_batch_async.py
  sdk/tables/azure-data-tables/azure/data/tables/aio/_table_client_async.py
  sdk/tables/azure-data-tables/azure/data/tables/aio/_table_service_client_async.py
Labels: Client, Tables, MQ

#28598 [AutoRelease] t2-servicebus-2023-02-02-06416(can only be merged by SDK owner)
  sdk/servicebus/azure-mgmt-servicebus/CHANGELOG.md
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2015_08_01/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2017_04_01/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2018_01_01_preview/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2021_01_01_preview/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2021_06_01_preview/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2021_11_01/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2022_01_01_preview/_version.py
  sdk/servicebus/azure-mgmt-servicebus/azure/mgmt/servicebus/v2022_10_01_preview/_version.py
  sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_cli_mgmt_servicebus_queue.pyTestMgmtServiceBustest_queue.json
  sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_cli_mgmt_servicebus_topic.pyTestMgmtServiceBustest_subscrpition_and_rule.json
  sdk/servicebus/azure-mgmt-servicebus/tests/recordings/test_cli_mgmt_servicebus_topic.pyTestMgmtServiceBustest_topic.json
Labels: Service Bus

#28563 [AutoRelease] t2-recoveryservices-2023-02-01-17082(can only be merged by SDK owner)
  sdk/recoveryservices/azure-mgmt-recoveryservices/CHANGELOG.md
  sdk/recoveryservices/azure-mgmt-recoveryservices/README.md
  sdk/recoveryservices/azure-mgmt-recoveryservices/_meta.json
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/_configuration.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/_recovery_services_client.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/_serialization.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/_vendor.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/_version.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/_configuration.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/_recovery_services_client.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_private_link_resources_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_recovery_services_client_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_recovery_services_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_registered_identities_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_replication_usages_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_usages_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_vault_certificates_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_vault_extended_info_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/aio/operations/_vaults_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/models/_models_py3.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_private_link_resources_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_recovery_services_client_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_recovery_services_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_registered_identities_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_replication_usages_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_usages_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_vault_certificates_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_vault_extended_info_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/azure/mgmt/recoveryservices/operations/_vaults_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/capabilities.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/check_name_availability_available.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/check_name_availability_not_available.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/delete_registered_identities.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/delete_vault.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/get_operation_result.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/get_operation_status.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/get_private_link_resources.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/get_vault.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/get_vault_extended_info.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/list_by_subscription_ids.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/list_operations.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/list_private_link_resources.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/list_replication_usages.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/list_resources.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/list_usages.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/patch_vault.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/patch_vault_with_cmk.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/patch_vault_with_cmk2.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/patch_vault_with_cmk3.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/patch_vault_with_monitoring_settings.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/patch_vault_with_user_assigned_identity.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/put_vault.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/put_vault_cred.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/put_vault_with_cmk.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/put_vault_with_monitoring_settings.py
  sdk/recoveryservices/azure-mgmt-recoveryservices/generated_samples/put_vault_with_user_assigned_identity.py
Labels: Recovery Services

#28395 [AutoRelease] t2-synapse-2023-01-18-47765(can only be merged by SDK owner)
  sdk/synapse/azure-mgmt-synapse/CHANGELOG.md
  sdk/synapse/azure-mgmt-synapse/README.md
  sdk/synapse/azure-mgmt-synapse/_meta.json
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/_serialization.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/_synapse_management_client.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/_vendor.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/_version.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/aio/_synapse_management_client.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/aio/operations/__init__.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/aio/operations/_get_operations.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/aio/operations/_private_endpoint_connections_operations.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/models/__init__.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/models/_models_py3.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/models/_synapse_management_client_enums.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/operations/__init__.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/operations/_get_operations.py
  sdk/synapse/azure-mgmt-synapse/azure/mgmt/synapse/operations/_private_endpoint_connections_operations.py
  sdk/synapse/azure-mgmt-synapse/generated_samples/enable_interactivequery_integration_runtimes.py
  sdk/synapse/azure-mgmt-synapse/generated_samples/integration_runtimes_start_operation_status.py
  sdk/synapse/azure-mgmt-synapse/generated_samples/integration_runtimes_stop_operation_status.py
Labels: Synapse

#28804 [ML][Pipelines] fix: avoid raising OSError for invalid paths in LocalPathField deserialization
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/core/fields.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
  sdk/ml/azure-ai-ml/tests/component/unittests/test_component_schema.py
Labels: Machine Learning, ML-Pipelines

#28854 azure-communication-identity comment fix
  sdk/communication/azure-communication-identity/azure/communication/identity/_communication_identity_client.py
Labels: Communication

#28861 Increment version for appconfiguration releases
  sdk/appconfiguration/azure-appconfiguration-provider/CHANGELOG.md
  sdk/appconfiguration/azure-appconfiguration-provider/azure/appconfiguration/provider/_version.py
Labels: App Configuration, auto-merge

#28867 [Storage] Document deprecated methods on StorageStreamDownloader
  sdk/storage/azure-storage-blob/azure/storage/blob/_download.py
  sdk/storage/azure-storage-blob/azure/storage/blob/aio/_download_async.py
  sdk/storage/azure-storage-file-share/azure/storage/fileshare/_download.py
  sdk/storage/azure-storage-file-share/azure/storage/fileshare/aio/_download_async.py
Labels: Storage

#28870 Sync eng/common directory with azure-sdk-tools for PR 5103
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#28874 Increment version for monitor releases
  sdk/monitor/azure-monitor-ingestion/CHANGELOG.md
  sdk/monitor/azure-monitor-ingestion/azure/monitor/ingestion/_version.py
Labels: auto-merge

#28881 Sync eng/common directory with azure-sdk-tools for PR 5493
  eng/common/pipelines/templates/stages/archetype-sdk-tool-pwsh.yml
Labels: EngSys, Central-EngSys

#28776 [ML][Pipelines] Infer & update loop body input from do-while mapping
  sdk/ml/azure-ai-ml/azure/ai/ml/dsl/_do_while.py
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/dynamic_input_do_while/component.yml
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/dynamic_input_do_while/dummy_model/dummy_file
  sdk/ml/azure-ai-ml/tests/test_configs/dsl_pipeline/dynamic_input_do_while/pipeline.py
Labels: Machine Learning, ML-Pipelines

#28882 [Pipeline] Support pass pipeline input to environment_variables
  sdk/ml/azure-ai-ml/azure/ai/ml/_internal/entities/_input_outputs.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_command.py
  sdk/ml/azure-ai-ml/azure/ai/ml/_schema/job/parameterized_parallel.py
  sdk/ml/azure-ai-ml/tests/dsl/unittests/test_dsl_pipeline.py
Labels: Machine Learning, ML-Pipelines, ML-Jobs

#28886 change default mdc path for collections
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_online_deployment_operations.py
Labels: Machine Learning, ML-Inference

#28875 [ACR] Fix failing pipelines
  sdk/containerregistry/azure-containerregistry/assets.json
  sdk/containerregistry/azure-containerregistry/samples/async_samples/sample_hello_world_async.py
  sdk/containerregistry/azure-containerregistry/samples/sample_delete_images.py
  sdk/containerregistry/azure-containerregistry/samples/sample_delete_images_async.py
  sdk/containerregistry/azure-containerregistry/samples/sample_delete_tags.py
  sdk/containerregistry/azure-containerregistry/samples/sample_delete_tags_async.py
  sdk/containerregistry/azure-containerregistry/samples/sample_hello_world.py
  sdk/containerregistry/azure-containerregistry/samples/sample_hello_world_async.py
  sdk/containerregistry/azure-containerregistry/samples/sample_list_tags.py
  sdk/containerregistry/azure-containerregistry/samples/sample_list_tags_async.py
  sdk/containerregistry/azure-containerregistry/samples/sample_set_image_properties_async.py
  sdk/containerregistry/azure-containerregistry/samples/sample_upload_download_blob.py
  sdk/containerregistry/azure-containerregistry/samples/sample_upload_download_manifest.py
  sdk/containerregistry/azure-containerregistry/samples/utilities.py
  sdk/containerregistry/azure-containerregistry/tests/constants.py
  sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client.py
  sdk/containerregistry/azure-containerregistry/tests/test_container_registry_client_async.py
  sdk/containerregistry/azure-containerregistry/tests/testcase.py
Labels: Container Registry

#28900 Update azure-containerregistry sample readme for release error
  sdk/containerregistry/azure-containerregistry/samples/README.md
Labels: Container Registry

#28839 Don't break SDK public API for WorkspaceModelReference
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/__init__.py
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_assets/workspace_asset_reference.py
  sdk/ml/azure-ai-ml/tests/model/unittests/test_model_operations.py
Labels: Machine Learning

#28923 Sync eng/common directory with azure-sdk-tools for PR 5531
  eng/common/pipelines/templates/jobs/perf.yml
Labels: EngSys, Central-EngSys

#28927 [Storage] [STG86] GA Release Prep
  sdk/storage/azure-storage-blob/CHANGELOG.md
  sdk/storage/azure-storage-file-datalake/CHANGELOG.md
  sdk/storage/azure-storage-file-share/CHANGELOG.md
  sdk/storage/azure-storage-queue/CHANGELOG.md
Labels: Storage

#28929 Sync eng/common directory with azure-sdk-tools for PR 5537
  eng/common/pipelines/templates/steps/check-spelling.yml
Labels: EngSys, Central-EngSys

#28475 [Key Vault] Typing improvements for archboard feedback
  sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_access_control_client.py
  sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/async_challenge_auth_policy.py
  sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/_internal/http_challenge.py
  sdk/keyvault/azure-keyvault-administration/azure/keyvault/administration/aio/_access_control_client.py
  sdk/keyvault/azure-keyvault-administration/tests/test_settings_client.py
  sdk/keyvault/azure-keyvault-administration/tests/test_settings_client_async.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_client.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/async_challenge_auth_policy.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_shared/http_challenge.py
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/aio/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_models.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/async_challenge_auth_policy.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_shared/http_challenge.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/aio/_client.py
  sdk/keyvault/azure-keyvault-keys/dev_requirements.txt
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/async_challenge_auth_policy.py
  sdk/keyvault/azure-keyvault-secrets/azure/keyvault/secrets/_shared/http_challenge.py
Labels: KeyVault, Client

#28936 [ServiceBus] Updating Chart.yaml to fix breaking stress release pipeline
  sdk/servicebus/azure-servicebus/stress/Chart.lock
  sdk/servicebus/azure-servicebus/stress/Chart.yaml
  sdk/servicebus/azure-servicebus/stress/scenarios-matrix.yaml
  sdk/servicebus/azure-servicebus/stress/templates/testjob.yaml
Labels: Service Bus

#28954 [Key Vault] Remove OKP support
  sdk/keyvault/azure-keyvault-keys/CHANGELOG.md
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/_enums.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/aio/_client.py
  sdk/keyvault/azure-keyvault-keys/azure/keyvault/keys/crypto/_providers/__init__.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client.py
  sdk/keyvault/azure-keyvault-keys/tests/test_crypto_client_async.py
  sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys.py
  sdk/keyvault/azure-keyvault-keys/tests/test_samples_keys_async.py
Labels: KeyVault, Client

#28587 [Cosmos] API review updates for GA release
  sdk/cosmos/azure-cosmos/README.md
  sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_client_connection.py
  sdk/cosmos/azure-cosmos/azure/cosmos/_cosmos_http_logging_policy.py
  sdk/cosmos/azure-cosmos/azure/cosmos/aio/_container.py
  sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client.py
  sdk/cosmos/azure-cosmos/azure/cosmos/aio/_cosmos_client_connection_async.py
  sdk/cosmos/azure-cosmos/azure/cosmos/aio/_database.py
  sdk/cosmos/azure-cosmos/azure/cosmos/container.py
  sdk/cosmos/azure-cosmos/azure/cosmos/cosmos_client.py
  sdk/cosmos/azure-cosmos/azure/cosmos/database.py
  sdk/cosmos/azure-cosmos/azure/cosmos/http_constants.py
Labels: Cosmos

#28951 [ML] Add test sanitizer for emails and usernames
  sdk/ml/azure-ai-ml/tests/conftest.py
Labels: Machine Learning

#28966 [Key Vault] Correct type hints for `cer` attributes
  sdk/keyvault/azure-keyvault-certificates/CHANGELOG.md
  sdk/keyvault/azure-keyvault-certificates/azure/keyvault/certificates/_models.py
Labels: KeyVault, Client

#28538 Pipeline typing in azure-core
  sdk/core/azure-core/azure/core/_pipeline_client.py
  sdk/core/azure-core/azure/core/_pipeline_client_async.py
  sdk/core/azure-core/azure/core/pipeline/_base.py
  sdk/core/azure-core/azure/core/pipeline/_base_async.py
  sdk/core/azure-core/azure/core/pipeline/policies/_base.py
  sdk/core/azure-core/azure/core/pipeline/policies/_base_async.py
  sdk/core/azure-core/azure/core/pipeline/transport/_aiohttp.py
  sdk/core/azure-core/azure/core/pipeline/transport/_base_async.py
  sdk/core/azure-core/azure/core/pipeline/transport/_base_requests_async.py
  sdk/core/azure-core/setup.py
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_document_model_administration_client.py
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/_form_training_client.py
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_document_model_administration_client_async.py
  sdk/formrecognizer/azure-ai-formrecognizer/azure/ai/formrecognizer/aio/_form_training_client_async.py
  shared_requirements.txt
Labels: Azure.Core

#28970 [Cosmos] updating versions for release
  sdk/cosmos/azure-cosmos/CHANGELOG.md
  sdk/cosmos/azure-cosmos/azure/cosmos/_version.py
Labels: Cosmos

#28789 Sync eng/common directory with azure-sdk-tools for PR 5431
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#28971 [Identity] Typing adjustments
  sdk/identity/azure-identity/azure/identity/_credentials/azd_cli.py
  sdk/identity/azure-identity/azure/identity/_credentials/azure_arc.py
  sdk/identity/azure-identity/azure/identity/_credentials/default.py
  sdk/identity/azure-identity/azure/identity/_internal/aad_client_base.py
  sdk/identity/azure-identity/azure/identity/_internal/shared_token_cache.py
  sdk/identity/azure-identity/azure/identity/_internal/utils.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/azure_powershell.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/certificate.py
  sdk/identity/azure-identity/azure/identity/aio/_credentials/on_behalf_of.py
Labels: Azure.Identity

#28976 [Cosmos] Update versions for release
  sdk/cosmos/azure-cosmos/CHANGELOG.md
Labels: Cosmos

#28975 Joharrington/managed network outbound rule operations fix
  sdk/ml/azure-ai-ml/azure/ai/ml/_ml_client.py
  sdk/ml/azure-ai-ml/tests/recordings/workspace/e2etests/test_workspace_outbound_rule_operations.pyTestWorkspaceOutboundRulestest_workspace_create_with_managed_network_list_show_remove_rules.json
  sdk/ml/azure-ai-ml/tests/workspace/e2etests/test_workspace_outbound_rule_operations.py
Labels: Machine Learning

#28978 Sync eng/common directory with azure-sdk-tools for PR 5562
  eng/common/scripts/get-codeowners.ps1
Labels: EngSys, Central-EngSys

#28979 [Storage] Fix duplicate type annotations
  sdk/storage/azure-storage-file-datalake/azure/storage/filedatalake/aio/_file_system_client_async.py
  sdk/storage/azure-storage-file-share/azure/storage/fileshare/_file_client.py
Labels: Storage

#28917 [ML][Schedule] Fix schedule default experiment name
  sdk/ml/azure-ai-ml/CHANGELOG.md
  sdk/ml/azure-ai-ml/azure/ai/ml/entities/_schedule/schedule.py
  sdk/ml/azure-ai-ml/tests/dsl/e2etests/test_controlflow_pipeline.py
  sdk/ml/azure-ai-ml/tests/recordings/dsl/e2etests/test_controlflow_pipeline.pyTestIfElsetest_registered_component_is_control.json
  sdk/ml/azure-ai-ml/tests/recordings/schedule/e2etests/test_schedule.pyTestScheduletest_load_cron_schedule_with_arm_id.json
  sdk/ml/azure-ai-ml/tests/recordings/schedule/e2etests/test_schedule.pyTestScheduletest_load_cron_schedule_with_arm_id_and_updates.json
  sdk/ml/azure-ai-ml/tests/schedule/e2etests/test_schedule.py
  sdk/ml/azure-ai-ml/tests/schedule/unittests/test_schedule_entity.py
Labels: Machine Learning, ML-Pipelines

#28889 readme update to opt in code snippet tool
  sdk/appconfiguration/azure-appconfiguration/README.md
  sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample.py
  sdk/appconfiguration/azure-appconfiguration/samples/hello_world_advanced_sample_async.py
  sdk/appconfiguration/azure-appconfiguration/samples/hello_world_sample.py
  sdk/appconfiguration/azure-appconfiguration/samples/hello_world_sample_async.py
  sdk/cognitiveservices/azure-cognitiveservices-vision-computervision/README.md
  sdk/communication/azure-communication-chat/README.md
  sdk/communication/azure-communication-email/README.md
  sdk/communication/azure-communication-sms/README.md
  sdk/core/azure-core/CLIENT_LIBRARY_DEVELOPER.md
  sdk/cosmos/azure-cosmos/README.md
  sdk/digitaltwins/azure-digitaltwins-core/README.md
  sdk/digitaltwins/azure-digitaltwins-core/samples/Readme.md
  sdk/eventgrid/azure-eventgrid/README.md
  sdk/eventgrid/azure-eventgrid/migration_guide.md
  sdk/eventhub/azure-eventhub/README.md
  sdk/eventhub/azure-eventhub/samples/sync_samples/connection_string_authentication.py
  sdk/eventhub/azure-eventhub/samples/sync_samples/send.py
  sdk/formrecognizer/azure-ai-formrecognizer/README.md
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_analyze_general_documents.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_analyze_layout.py
  sdk/formrecognizer/azure-ai-formrecognizer/samples/v3.2/sample_analyze_receipts.py
  sdk/identity/azure-identity/README.md
  sdk/identity/azure-identity/migration_guide.md
  sdk/identity/azure-identity/samples/azure-aad-auth-with-redis-py.md
  sdk/identity/azure-identity/samples/client_certificate_credential.md
  sdk/keyvault/azure-keyvault-certificates/README.md
  sdk/keyvault/azure-keyvault-certificates/samples/hello_world.py
  sdk/keyvault/azure-keyvault-keys/README.md
  sdk/keyvault/azure-keyvault-keys/samples/hello_world.py
  sdk/keyvault/azure-keyvault-secrets/README.md
  sdk/keyvault/azure-keyvault-secrets/samples/hello_world.py
  sdk/metricsadvisor/azure-ai-metricsadvisor/README.md
  sdk/metricsadvisor/azure-ai-metricsadvisor/samples/sample_incidents.py
  sdk/monitor/azure-monitor-opentelemetry-exporter/README.md
  sdk/schemaregistry/azure-schemaregistry-avroencoder/README.md
  sdk/schemaregistry/azure-schemaregistry/README.md
  sdk/search/azure-search-documents/README.md
  sdk/search/azure-search-documents/samples/sample_index_alias_crud_operations.py
  sdk/servicebus/azure-servicebus/README.md
  sdk/servicebus/azure-servicebus/migration_guide.md
  sdk/storage/azure-storage-blob/README.md
  sdk/storage/azure-storage-file-datalake/README.md
  sdk/storage/azure-storage-file-share/README.md
  sdk/storage/azure-storage-queue/README.md
  sdk/textanalytics/azure-ai-textanalytics/README.md
  sdk/translation/azure-ai-translation-document/README.md
  sdk/translation/azure-ai-translation-document/samples/sample_translate_multiple_inputs.py
  tools/azure-sdk-tools/ci_tools/snippet_update/python_snippet_updater.py
Labels: App Configuration

#28977 Increment version for cosmos releases
  sdk/cosmos/azure-cosmos/CHANGELOG.md
  sdk/cosmos/azure-cosmos/azure/cosmos/_version.py
  sdk/cosmos/azure-cosmos/setup.py
Labels: Cosmos, auto-merge

#28712 [ML] Support batch cancel (internal only) by tags within a workspace
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
Labels: Machine Learning

#28944 Create methods and models for recognize, play, and cancelallmediaoperations
  sdk/communication/azure-communication-callautomation/azure/communication/callautomation/__init__.py
  sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_automation_client.py
  sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_connection.py
  sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_call_media.py
  sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_communication_identifier_serializer.py
  sdk/communication/azure-communication-callautomation/azure/communication/callautomation/_models.py
Labels: Communication

#28998 [ML] Update jobs.begin_cancel() to use kwargs.pop() to fetch tag instead of kwargs.get()
  sdk/ml/azure-ai-ml/azure/ai/ml/operations/_job_operations.py
Labels: Machine Learning

#29000 Sync eng/common directory with azure-sdk-tools for PR 5568
  eng/common/testproxy/transition-scripts/README.md
  eng/common/testproxy/transition-scripts/generate-assets-json.ps1
Labels: EngSys, Central-EngSys
